project:
  type: website
 
  

# Exclude all files in HTW_Analysis folder, recursively


bibliography: [Assets/Bib/Dissertation.bib]
csl: Assets/Bib/apa7.csl

profile:
  group: 
    -  [full,md]



# website:
#   title: "HTW Project"
#   reader-mode: true
#   navbar:
#     pinned: false
#    # background: "#EE6A24"
#     left:
#       - text: Analyses
#         menu: 
#           - Analysis/discrim.qmd
#           - Analysis/ME_Pool.qmd
#           - Analysis/analysis.qmd
#           - Visuals_Interactives/ojs_explore.qmd
#       - text: Simulations
#         menu: 
#           - Simulations/simParameterRecovery.qmd
#           - Simulations/DeLosh97_Sim.qmd
#           - Simulations/SimReplications.qmd
#           - Simulations/alm_learning.qmd
#       - text: Model 
#         menu: 
#             - Model/htw_exam.qmd
#             - Model/abc_htw.qmd
#             - Model/group_fits.qmd
#       - text: Interactive
#         menu: 
#           - Visuals_Interactives/ojs_alm.qmd
#           - Visuals_Interactives/quarto_shiny.qmd
#           - Visuals_Interactives/ALM_Shiny.qmd
#       - text: Misc
#         menu: 
#           - Misc/Task.qmd
#           - Visuals_Interactives/model_viz.qmd
#           - Misc/htw_dp.qmd
#           - Misc/External.qmd
#           - Misc/HTW_ToDo.qmd
#           - Misc/benchmarks.qmd
