project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    - "*.qmd"
    - "!_*" # ignore any file that starts with a _
    - "!quarto_shiny.qmd"
    - "!quartoP5.qmd"
    - "!htw_expGPT.qmd"
    - "!scratch/*"
    #- !htw_exam.qmd"
    - "!Misc/External.qmd"
    - "!Manuscript/"
    - "Simulations/htw_exam.qmd"
    #- "!Analysis/Results.qmd"
    - "!Model/dev*"
    - "!_working/*"
    - "!Assets/tmp_plots/*"
    - "!Assets/tmp_plots/**"
    - "!Model/abc_group.qmd"
    - "!Model/abc_hier.qmd"
    - "!Model/alm_ll.qmd"
    - "!Model/dev/*"
    - "!Analysis/e1_discrim.qmd"
    - "!Misc/alm_table.qmd"
    #- "!Model/htw_exam.qmd"
  resources: 
      - "Manuscript/output/"
      - "Manuscript/assets/"
    
exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","out.bib",
  "*.pdf","*.R",".obsidian","Rproj","R","Bib","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*"]


website:
  title: "HTW Project"
  repo-url: https://github.com/tegorman13/htw
  site-url: "https://tegorman13.github.io/htw/"
  repo-actions: [source, edit, issue]
  reader-mode: true
  page-navigation: true
  # page-footer:
  #   left: |
  #     View the source [on GitHub]({{< var website.repo-url >}})
  # page-footer: 
  #   center: 
  #     - text: © 2024 Thomas Gorman <br> site created with [R](https://cran.r-project.org/) and [quarto](https://quarto.org)

# navbar:
  #   background: light
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - icon: github
  #       href: https://github.com/tegorman13/htw
  #     aria-label: GitHub
  sidebar:
    style: "docked"
    border: false
    collapse-level: 2
    pinned: false
    target: _blank
    tools:
      - icon: github
        href: https://github.com/tegorman13/htw
        # menu:
        #   - text: Open Github Repo 
        #     url:  https://github.com/tegorman13/htw
   # background: "#EE6A24"
    contents:
      - index.qmd
      - text: "---"
      - paper.qmd
      - text: "---"
      - section: Sections
        contents: 
          # - Misc/Task.qmd
          # - Misc/data_dictionary.qmd
          # - Misc/data_organize.qmd
          - Sections/Intro.qmd
          - Sections/Methods.qmd
          - text: "Results"
            href: Sections/Results.qmd
          - Sections/Discussion.qmd
          - text: "Combo_all"
            href: Sections/combo1.qmd
          - Sections/htw_full.qmd
      - text: "---"
      - section: Analyses
        contents: # Analysis/* 
          - Analysis/e1.qmd
          - Analysis/e2.qmd
          - Analysis/e3.qmd
          - Analysis/combo_test.qmd
          - Analysis/e1_test.qmd
          - Analysis/e2_test.qmd
          - Analysis/e3_test.qmd
          - Analysis/e1_Analysis.qmd
          # - Analysis/test_analysis-all.qmd
          # - Analysis/discrim.qmd
          # - Analysis/analysis.qmd
      - text: "---"
      - section: Model 
        contents: 
            - Model/htw_exam.qmd
            - Model/htw_model.qmd
            - Model/htw_model_e1.qmd
            - Model/htw_model_e2.qmd
            - Model/htw_model_e3.qmd
            - Model/hybrid.qmd
      - text: "---"
      - section: Simulations
        contents: 
         # - Simulations/simParameterRecovery.qmd
          - Simulations/DeLosh97_Sim.qmd
          - Simulations/SimReplications.qmd
        #  - Simulations/alm_learning.qmd

      - text: "---"
      - section: Interactive
        contents: 
          - Misc/Visuals_Interactives/ojs_alm.qmd
          - Misc/Visuals_Interactives/quarto_shiny.qmd
          - Misc/Visuals_Interactives/ALM_Shiny.qmd
      - text: "---"
      - section: Misc
        contents: 
          - Analysis/combo_train.qmd
          - Misc/Visuals_Interactives/model_viz.qmd
          - Misc/htw_dp.qmd
          #- Misc/External.qmd
          - Misc/HTW_ToDo.qmd
          - Misc/benchmarks.qmd
      - section: Appendix
        contents: 
          - Sections/e1_model_appendix.qmd



format:
  html:
    # theme:
    #   light: spacelab #[default]
    #   dark: cyborg
    theme: Assets/Style/lux-modified.scss 
    #css: ["Assets/Style/lux-modified.scss", "Assets/Style/calloutTG.css"]
    css: ["Assets/Style/calloutTG.css"]
    page-layout: full
    tbl-cap-location: top
    fig-cap-location: bottom
    toc: true
    toc-location: right
    toc-depth: 2
    cold-fold: true
    cold-tools: true
    code-link: true
    code-line-numbers: false
    citations-hover: true
    #code-overflow: wrap
    code-copy: true
    number-depth: 3
    smooth-scroll: true
    code-block-bg: "#272822"
    highlight-style: monokai #github #a11y
    html-math-method: mathjax
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.tegorman13\.github\.io\/htw\/**'


bibliography: [Assets/Bib/Dissertation.bib]
csl: Assets/Bib/apa7.csl


execute:
  freeze: auto
 # cache: true





























# project:
#   type: website
 
  

# # Exclude all files in HTW_Analysis folder, recursively


# bibliography: [Assets/Bib/Dissertation.bib]
# csl: Assets/Bib/apa7.csl

# profile:
#   group: 
#     -  [full,md]
#    # -  [md]



# website:
#   title: "HTW Project"
#   reader-mode: true
#   navbar:
#     pinned: false
#    # background: "#EE6A24"
#     left:
#       - text: Analyses
#         menu: 
#           - Analysis/discrim.qmd
#           - Analysis/ME_Pool.qmd
#           - Analysis/analysis.qmd
#           - Visuals_Interactives/ojs_explore.qmd
#       - text: Simulations
#         menu: 
#           - Simulations/simParameterRecovery.qmd
#           - Simulations/DeLosh97_Sim.qmd
#           - Simulations/SimReplications.qmd
#           - Simulations/alm_learning.qmd
#       - text: Model 
#         menu: 
#             - Model/htw_exam.qmd
#             - Model/abc_htw.qmd
#             - Model/group_fits.qmd
#       - text: Interactive
#         menu: 
#           - Visuals_Interactives/ojs_alm.qmd
#           - Visuals_Interactives/quarto_shiny.qmd
#           - Visuals_Interactives/ALM_Shiny.qmd
#       - text: Misc
#         menu: 
#           - Misc/Task.qmd
#           - Visuals_Interactives/model_viz.qmd
#           - Misc/htw_dp.qmd
#           - Misc/External.qmd
#           - Misc/HTW_ToDo.qmd
#           - Misc/benchmarks.qmd
