
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!quarto_shiny.qmd"
    - "!quartoP5.qmd"
    - "!alm_hidden.qmd"
    - "!bayes*"
    - "!htw_expGPT.qmd"
    - "!RNN_ALM.qmd"
    - "!auto_sim.qmd"
    #- !htw_exam.qmd"

exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","out.bib",
"*.pdf","*.R",".obsidian","Rproj","R","Bib","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*","Manuscript*"]

# Exclude all files in HTW_Analysis folder, recursively
website:
  title: "HTW Project"
  navbar:
    pinned: false
   # background: "#EE6A24"
    left:
      - text: Analyses
        menu: 
          - Analysis/discrim.qmd
          - Analysis/ME_Pool.qmd
          - Analysis/analysis.qmd
          - Visuals_Interactives/ojs_explore.qmd
      - text: Simulations
        menu: 
          - Simulations/simParameterRecovery.qmd
          - Simulations/DeLosh97_Sim.qmd
          - Simulations/SimReplications.qmd
          - Simulations/alm_learning.qmd
      - text: Model Fitting
        menu: 
          - Model/htw_exam.qmd
          - Model/abc_htw.qmd
          - Model/group_fits.qmd
      - text: Interactive
        menu: 
          - Visuals_Interactives/ojs_alm.qmd
          - Visuals_Interactives/quarto_shiny.qmd
          - Visuals_Interactives/ALM_Shiny.qmd
          - Visuals_Interactives/quartoP5.qmd
      - text: Misc
        menu: 
          - Misc/Task.qmd
          - Visuals_Interactives/model_viz.qmd
          - Misc/htw_dp.qmd
          - Misc/External.qmd
          - Misc/HTW_ToDo.qmd
          - Misc/benchmarks.qmd


format:
  html:
    theme:
      light: spacelab #[default]
      dark: cyborg
    css: ["Style/style1.css", "Style/calloutTG.css"]
    toc: true
    toc-location: left
    cold-fold: true
    cold-tool: true
    smooth-scroll: true
    #html-math-method: mathjax

execute:
  freeze: true




# website:
#   title: "HTW Project"
#   navbar:
#     pinned: false
#    # background: "#EE6A24"
#     left:
#       - text: To-Do
#         file: HTW_ToDo.qmd
#       - text: Analyses
#         file: discrim.qmd
#       - text: Simulations
#         menu: 
#           - DeLosh97_Sim.qmd
#           - SimReplications.qmd
#           - ALM_Shiny.qmd
#           - ojs_alm.qmd
#           - alm_learning.qmd
#       - text: Model Fitting
#         menu: 
#           - htw_exam.qmd
#           - benchmarks.qmd
#       - text: Task
#         file: Task.qmd
#       - text: Proposal
#         file: htw_dp.qmd
#       - External.qmd