project:
  output-dir: _working
  render: 
    - "Model/htw_model.qmd"
    - "!manuscript.qmd"
    - "!test_igas.qmd"
    - "!igas_e1.qmd"


format:
  # gfm:
  #   output-file: dissertation-gfm.md
  #   fig-format: jpeg
  #   html-math-method: katex
  #   cite-method: citeproc
  gfm:
    html-math-method: mathjax
    output-file: htw_model-code.md
    fig-format: jpeg
    echo: true
    cite-method: citeproc
  
  # hugo:
  #   html-math-method: mathjax
  #   output-file: htw_model-nocode.md
  #   fig-format: jpeg
  #   echo: false
  #   cite-method: citeproc
  # docusaurus-md:
  #   output-file: htw_exam-docu.md
  #   cite-method: citeproc
  #   include: false
  #   echo: true
  #   fig-format: jpeg

# leaving freeze auto speeds things up - but stops from switching echo false to true 
# execute:
#   freeze: auto


# setting include to false will result in fast render. 
# - citations with still format, but crossrefs wont'. 
# - inline images still displayed


# echo false if you still want tables, but don't want code. 
# include false if you want no code or tables. 

# Table and figure captions are lost in all cases. 

# GFM - 65K tokens with code, 40K with include:false;  (12.7K reference tokens)
# - citations are formated - but in all caps - creating issues with line endings
# - citations formated correctly when cite-method set to citeproc
# - references at very end - ugly div id interleaving each
# - crossrefs work
# - tables - converted to markdown - but not visible in obsidian due to div
# - figures attempt to display with img-src
# - under defaults figures do display with standard markdown
# - appendix figures don't work (blocks dont' executre)
# - images - displayed in standard markdown
# - equations - all work (with katex) apart for | issue in table
# - skinnier columns
# - well formated in all respects when viewed on github (except table equation issue)
# https://github.com/tegorman13/Dissertation/blob/main/Manuscript/output/md/dissertation-gfm.md

# Hugo - 65K with code, 47K no code,  (9.3K reference tokens)
# formats latex components more similiar to my pdf system
# - citations are formated - but in all caps
# - biblatex will results in raw @format citations shown in md file, no reference section rendered
# - citeproc results in perfect references section. 
# - references at very end
# - crossrefs work
# - tables - displayed nicely in standard markdown
# - figures display with standard markdown
# - Appendix figures work. 
# - images - displayed in standard markdown
# - equations - all work apart for | issue in table
# - wider column than others
# - digraph in svg - lots of tokens
# - well formated in all respects when viewed on github (except table equation issue)
# https://github.com/tegorman13/Dissertation/blob/main/Manuscript/output/md/dissertation-gfm.md

# docusaurus- 54K with code, 36K no code
# - formats latex components more similiar to my pdf system
# - section headings have addition {#section-id} added
# - no citation formating or references
# - setting citation to citeproc results in citations in biblatex form (no references)
# - crossrefs work 
# - figures and images work - standard markdown for both
# - appendix figures work 
# - tables look nice - same as hugo
# - equations same as others
# - skinnier column
# https://github.com/tegorman13/Dissertation/blob/main/Manuscript/output/md/dissertation-docu.md