project:
  title: "Manuscript"


bibliography: [../Assets/Bib/Dissertation.bib]
csl: ../Assets/Bib/apa7.csl

#profile: 
  #default: nice

profile:
  group: 
    - [nice, ms, basic]

# execute:
#   freeze: auto