project:
  output-dir: output/basic
  render: - manuscript2.qmd



format:
  # docx:
  #   prefer-html: true
  #   output-file: "htw_ms1.docx"
  #   toc: true
  # html:
  #   toc: true
  #   language: 
  #     title-block-published: "Latest version"
  #   shift-heading-level-by: 1
  #   theme: 
  #      #- ../Assets/Style/lux-modified.scss 
  #      - zephyr
  #      - custom.scss
  #   citeproc: false
  #   filters: 
  #     - "_extensions/wordcount/citeproc.lua"
  #     - "_extensions/wordcount/wordcount.lua"
  #   lightbox: auto
  #   knitr:
  #     opts_chunk:
  #       dev: "ragg_png"
  #       dpi: 300


  pdf:
    cite-method: citeproc
    #keep-md: true
    output-file: "htw_basic.pdf"
    # mathfont: "Libertinus Math"
    #       # Document styling
    # geometry:
    #   - top=1in     
    #   - bottom=1in  
    #   - left=1in    
    #   - right=1in  
    #   - heightrounded
      
    #   # Citations and links
    # # lot: true
    # # lof: true
    # colorlinks: true
    # linkcolor: DarkSlateBlue
    # urlcolor: DarkSlateBlue
    # citecolor: DarkSlateBlue
    # link-citations: true
    # # linestretch: 1.05

    # include-in-header:
    #   # The \everydisplay thing makes all math blocks use \small font
    #   text: |
    #     \usepackage{mathtools}
    #     \everydisplay\expandafter{\the\everydisplay\small}
    #     \usepackage{float}
    #     \floatplacement{figure}{H}
    #     \floatplacement{table}{H}
    #     \usepackage{setspace}
    #     \pagenumbering{arabic}

    # knitr:
    #   opts_chunk:
    #     dev: "cairo_pdf"
 
