project:
  output-dir: output
  render: 
    - "manuscript.qmd"
    - "!igas_e1.qmd"
    - "!test_igas.qmd"

execute: 
  warning: false
  eval: true
  include: true
  echo: false

format:
  docx:
    prefer-html: true
    output-file: "htw_manuscript.docx"
    toc: true
  html:
    toc: true
    language: 
      title-block-published: "Latest version"
    shift-heading-level-by: 0
    toc-depth: 4
    link-citations: true
    page-layout: full
    format-links: [pdf, gfm, docx]
    theme: 
       #- ../Assets/Style/lux-modified.scss 
       - cosmo
       - custom.scss
       - Assets/Style/style.scss
    css: Assets/Style/calloutTG.css
    citeproc: false
    filters: 
      - "_extensions/wordcount/citeproc.lua"
      - "_extensions/wordcount/wordcount.lua"
    lightbox: auto
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
  pdf:
    cite-method: citeproc
    output-file: "htw_manuscript.pdf"
    mathfont: "Libertinus Math"
    documentclass: article
    papersize: letter
    fontsize: 11pt
    linestretch: 1.5
          # Document styling
    geometry:
      - top=1in     
      - bottom=1in  
      - left=1in    
      - right=1in  
      - heightrounded
      
      # Citations and links
    # lot: true
    # lof: true
    colorlinks: true
    linkcolor: DarkSlateBlue
    urlcolor: DarkSlateBlue
    citecolor: DarkSlateBlue
    link-citations: true
    # linestretch: 1.05

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small}
        \usepackage{float}
        \floatplacement{figure}{H}
        \floatplacement{table}{H}
        \usepackage{setspace}
        \pagenumbering{arabic}
  # hugo:
  #   html-math-method: mathjax
  #   output-file: htw_manuscript-hugo.md
  #   fig-format: jpeg
  #   echo: true
  #   cite-method: citeproc
  gfm:
    echo: false
    #output: false
    output-file: htw_manuscript_gfm.md


    # knitr:
    #   opts_chunk:
    #     dev: "cairo_pdf"
 


  # hikmah-manuscript-odt:
  #   output-file: "manuscript-ms.odt"
  #   prefer-html: true
#  docx:
#     knitr:
#       opts_chunk:
#         dev: "ragg_png"
#         dpi: 300