project:
  title: "Manuscript"


execute: 
  warning: false
  eval: true
  include: true
  echo: false

bibliography: [../Assets/Bib/Dissertation.bib]
csl: ../Assets/Bib/apa7.csl

#profile: 
  #default: nice

profile:
  group: 
    - [nice, ms, basic]

# execute:
#   freeze: auto