project:
  title: "Manuscript"

# execute:
#   freeze: auto

  render: 
    - "manuscript.qmd"
   #- "!submissions/*.qmd"

bibliography: [../Assets/Bib/Dissertation.bib]
csl: ../Assets/Bib/apa7.csl

#profile: 
  #default: nice

profile:
  group: 
    - [nice, ms]