---
title: "`r params$title`"
author: Thomas Gorman
date: "`r Sys.Date()`"
output: html_document
code-fold: true
code-tools: true
execute: 
  warning: false
  eval: true
params:
    file_name: file_name
    title: title
   #ind_fits: ind_fits
   
---

```{r}
#| results: asis

pacman::p_load(dplyr,purrr,tidyr,ggplot2, data.table, here, patchwork, conflicted, stringr)
conflict_prefer_all("dplyr", quiet = TRUE)

walk(c("Display_Functions"), ~ source(here::here(paste0("Functions/", .x, ".R"))))
ds <- readRDS(here::here("data/e1_md_11-06-23.rds"))  |> as.data.table()
ids <- c(1,2,4,5,6,7,8, 10,11,12,13)
ids2 <- c(1,66,36)
ids3 <- c(20,71,101,4,76,192)
idsBad <- c(76,192, 101)

source(here::here("Functions/fun_indv_fit.R"))

raw_name <- tools::file_path_sans_ext(basename(params$file_name))



cat(glue::glue('## {raw_name}'))

```


## `{r} raw_name`

#| eval: false

```{r}
#| eval: false

ind_fits <- readRDS(here::here(params$file_name))


ind_fits_df <- imap_dfr(ind_fits |> list_assign(runInfo = zap()), ~imap_dfr(.x, ~{
  teter_data <- .x[["teter_results"]] %>% mutate(result_type = "teter_results")
  te_data <- .x[["te_results"]] %>% mutate(result_type = "te_results")
  tr_data <- .x[["tr_results"]] %>% mutate(result_type = "tr_results")
  combined_data <- bind_rows(teter_data, te_data, tr_data)
}, .id = "id"))

ids2 <- c(1,66,36)
ids3 <- c(20,71,101,4,76,192)
idsBad <- c(76,192, 101)

#head(ind_fits$runInfo$systemInfo)

post_dat <- ind_fits_df |> select(sim_dat,rank) |> unnest(sim_dat) |> as.data.table()
post_dat_l <- setorder(melt(setcolorder(post_dat[expMode2 == "Test"][, `:=`(avg_y = mean(y)), 
        by = .(id, condit, x)], c("id", "condit", "Model", "Fit_Method", 
    "expMode2", "tr", "rank", "c", "lr", "x", "y", "avg_y", "pred", 
    "resid")), measure.vars = c("pred", "y"), variable.name = "Resp", 
        value.name = "val", variable.factor = FALSE)[, `:=`(Resp = fcase(Resp == 
        "y", "Observed", Model == "ALM", "ALM", Model == "EXAM", 
        "EXAM")), by = .(id, condit, x)], tr, id, Resp, na.last = TRUE)


```


##  Posterior Average `{r} raw_name`
```{r fig.width=12, fig.height=17}
#| eval: false
post_tabs <- abc_tables(post_dat_l)

post_tabs$et_sum |> gt::gt()
post_tabs$et_sum_x |> kable()

```


## Distributions `{r} raw_name`
```{r, fig.width=12, fig.height=17}
#| eval: false
plot_sampled_posterior(ind_fits)
plot_indv_posterior(ind_fits_df)

```

## Posterior Predictive
```{r, fig.width=12, fig.height=14}
#| eval: false
group_predictive_plots(post_dat_l)
group_best_plots(post_dat_l)
```



## Individual Plots
```{r, fig.width=12, fig.height=17}
#| eval: false
indv_best_plots(post_dat_l)
indv_predictive_plots(post_dat_l, ids2)
indv_predictive_plots(post_dat_l, idsBad)

```



