<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.224">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2023-07-04">
<title>HTW Project - HTW Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Analysis/discrim.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<link rel="stylesheet" href="../Assets/Style/style1.css">
<link rel="stylesheet" href="../Assets/Style/calloutTG.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Analysis/e1_Analysis.html">Analyses</a></li><li class="breadcrumb-item"><a href="../Analysis/analysis.html">HTW Analysis</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">HTW Project</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/tegorman13/htw" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Project</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Task.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Task</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/data_dictionary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Data Dictionary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/data_organize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Organization</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Analyses</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/e1_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experiment 1 Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/test_analysis-all.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Test Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/discrim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testing Discrimination Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">HTW Analysis</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Simulations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/simParameterRecovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameter Recovery Simulations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/DeLosh97_Sim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulating DeLosh 1997</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/SimReplications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Simulations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/alm_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM Learning</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/htw_exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM &amp; EXAM Fitting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/abc_htw.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Approximate Bayesian Fitting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/group_fits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Group Level Fits</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Interactive</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/ojs_alm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OJS ALM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/ALM_Shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM Shiny App Code</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Misc</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/model_viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/htw_dp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/HTW_ToDo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW To-do and Notes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benchmarking</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Analysis/e1_Analysis.html">Analyses</a></li><li class="breadcrumb-item"><a href="../Analysis/analysis.html">HTW Analysis</a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">HTW Analysis</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Analysis</div>
    <div class="quarto-category">Learning-Curve</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta column-page-right">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 4, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header><div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,data.table,lme4)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-5"><a href="#cb1-5"></a></span>
<span id="cb1-6"><a href="#cb1-6"></a>d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/dPrune-01-19-23.rds"</span>)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="fu">levels</span>(d<span class="sc">$</span>condit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] "Constant" "Varied"  </code></pre>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Prepare the data for analysis</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>    <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>    <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>    <span class="fu">mutate</span>(<span class="at">nBand =</span> <span class="fu">n</span>(), <span class="at">band =</span> bandInt, <span class="at">id =</span> <span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>    <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>    <span class="fu">mutate</span>(<span class="at">nd =</span> <span class="fu">n_distinct</span>(lowBound))</span>
<span id="cb3-8"><a href="#cb3-8"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>    <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10"></a>    <span class="fu">filter</span>(nBand <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> nd <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb3-11"><a href="#cb3-11"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>    <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb3-13"><a href="#cb3-13"></a>    <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand <span class="sc">&lt;</span> <span class="dv">5</span>]))</span>
<span id="cb3-14"><a href="#cb3-14"></a></span>
<span id="cb3-15"><a href="#cb3-15"></a>dtestAgg <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb3-16"><a href="#cb3-16"></a>    <span class="fu">group_by</span>(id, condit, catOrder, feedbackType, vb, band, lowBound, highBound, input) <span class="sc">%&gt;%</span></span>
<span id="cb3-17"><a href="#cb3-17"></a>    <span class="fu">mutate</span>(<span class="at">vxCapped =</span> <span class="fu">ifelse</span>(vx <span class="sc">&gt;</span> <span class="dv">1600</span>, <span class="dv">1600</span>, vx)) <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>    <span class="fu">summarise</span>(</span>
<span id="cb3-19"><a href="#cb3-19"></a>        <span class="at">vxMean =</span> <span class="fu">mean</span>(vx), <span class="at">devMean =</span> <span class="fu">mean</span>(dist), <span class="at">vxMed =</span> <span class="fu">median</span>(vx), <span class="at">devMed =</span> <span class="fu">median</span>(dist),</span>
<span id="cb3-20"><a href="#cb3-20"></a>        <span class="at">vxMeanCap =</span> <span class="fu">mean</span>(vxCapped), <span class="at">.groups =</span> <span class="st">"keep"</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>    )</span>
<span id="cb3-22"><a href="#cb3-22"></a>ds <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"train"</span>,<span class="st">"train-Nf"</span>,<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-23"><a href="#cb3-23"></a><span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand<span class="sc">&lt;</span><span class="dv">5</span>])) <span class="sc">%&gt;%</span> </span>
<span id="cb3-24"><a href="#cb3-24"></a><span class="fu">select</span>(id,condit,catOrder,feedbackType,expMode,trial,gt.train,vb,band,bandInt,lowBound,highBound,input,vx,dist,vxb) </span>
<span id="cb3-25"><a href="#cb3-25"></a></span>
<span id="cb3-26"><a href="#cb3-26"></a><span class="fu">head</span>(ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 16
     id condit catOrder feedbackType expMode trial gt.train vb     band  bandInt
  &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;    &lt;fct&gt;        &lt;fct&gt;   &lt;dbl&gt;    &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;   &lt;dbl&gt;
1     1 Varied orig     continuous   train       2        1 1000-… 5        1000
2     1 Varied orig     continuous   train       3        2 1200-… 6        1200
3     1 Varied orig     continuous   train       4        3 800-1… 4         800
4     1 Varied orig     continuous   train       5        4 1000-… 5        1000
5     1 Varied orig     continuous   train       6        5 800-1… 4         800
6     1 Varied orig     continuous   train       7        6 1000-… 5        1000
# ℹ 6 more variables: lowBound &lt;fct&gt;, highBound &lt;dbl&gt;, input &lt;dbl&gt;, vx &lt;dbl&gt;,
#   dist &lt;dbl&gt;, vxb &lt;dbl&gt;</code></pre>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>data <span class="ot">&lt;-</span> ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="linear-learning-model" class="level3"><h3 class="anchored" data-anchor-id="linear-learning-model">Linear Learning model</h3>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>dst <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode<span class="sc">==</span><span class="st">"train"</span>)</span>
<span id="cb6-2"><a href="#cb6-2"></a>dst <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">group_by</span>(id, vb) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="fu">mutate</span>(<span class="at">trial_band =</span> <span class="fu">row_number</span>())</span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="fu">head</span>(dst)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 17
# Groups:   id, vb [3]
     id condit catOrder feedbackType expMode trial gt.train vb     band  bandInt
  &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;    &lt;fct&gt;        &lt;fct&gt;   &lt;dbl&gt;    &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;   &lt;dbl&gt;
1     1 Varied orig     continuous   train       2        1 1000-… 5        1000
2     1 Varied orig     continuous   train       3        2 1200-… 6        1200
3     1 Varied orig     continuous   train       4        3 800-1… 4         800
4     1 Varied orig     continuous   train       5        4 1000-… 5        1000
5     1 Varied orig     continuous   train       6        5 800-1… 4         800
6     1 Varied orig     continuous   train       7        6 1000-… 5        1000
# ℹ 7 more variables: lowBound &lt;fct&gt;, highBound &lt;dbl&gt;, input &lt;dbl&gt;, vx &lt;dbl&gt;,
#   dist &lt;dbl&gt;, vxb &lt;dbl&gt;, trial_band &lt;int&gt;</code></pre>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>improvement_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> trial_band <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dst)</span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">summary</span>(improvement_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: dist ~ condit * trial_band * catOrder * feedbackType + (1 | id)
   Data: dst

REML criterion at convergence: 493625.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.1479 -0.5993 -0.2643  0.3564 12.0784 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept)  3312     57.55  
 Residual             38844    197.09  
Number of obs: 36760, groups:  id, 427

Fixed effects:
                                                         Estimate Std. Error
(Intercept)                                             192.86094    8.02154
conditVaried                                             74.59454   12.18754
trial_band                                               -1.33600    0.09565
catOrderrev                                             -35.51359   13.07957
feedbackTypeordinal                                      -5.36701   13.10006
conditVaried:trial_band                                  -2.37284    0.34191
conditVaried:catOrderrev                                -43.67731   18.79821
trial_band:catOrderrev                                    0.36376    0.15427
conditVaried:feedbackTypeordinal                          6.23570   19.91965
trial_band:feedbackTypeordinal                            0.46689    0.15629
catOrderrev:feedbackTypeordinal                          12.53672   19.23870
conditVaried:trial_band:catOrderrev                       0.11287    0.50367
conditVaried:trial_band:feedbackTypeordinal              -0.63293    0.55812
conditVaried:catOrderrev:feedbackTypeordinal            -24.66174   28.53662
trial_band:catOrderrev:feedbackTypeordinal               -0.19357    0.22801
conditVaried:trial_band:catOrderrev:feedbackTypeordinal   0.15127    0.78214
                                                        t value
(Intercept)                                              24.043
conditVaried                                              6.121
trial_band                                              -13.968
catOrderrev                                              -2.715
feedbackTypeordinal                                      -0.410
conditVaried:trial_band                                  -6.940
conditVaried:catOrderrev                                 -2.323
trial_band:catOrderrev                                    2.358
conditVaried:feedbackTypeordinal                          0.313
trial_band:feedbackTypeordinal                            2.987
catOrderrev:feedbackTypeordinal                           0.652
conditVaried:trial_band:catOrderrev                       0.224
conditVaried:trial_band:feedbackTypeordinal              -1.134
conditVaried:catOrderrev:feedbackTypeordinal             -0.864
trial_band:catOrderrev:feedbackTypeordinal               -0.849
conditVaried:trial_band:catOrderrev:feedbackTypeordinal   0.193</code></pre>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>dst_last_trial <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">group_by</span>(id, vb) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="fu">filter</span>(trial_band <span class="sc">==</span> <span class="fu">max</span>(trial_band))</span>
<span id="cb10-4"><a href="#cb10-4"></a>final_performance_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dst_last_trial)</span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="fu">summary</span>(final_performance_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: dist ~ condit * catOrder * feedbackType + (1 | id)
   Data: dst_last_trial

REML criterion at convergence: 10688.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.8391 -0.5189 -0.3499  0.3906  4.9779 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept)  6408     80.05  
 Residual             25136    158.54  
Number of obs: 817, groups:  id, 427

Fixed effects:
                                             Estimate Std. Error t value
(Intercept)                                     87.74      19.86   4.419
conditVaried                                   109.73      25.16   4.362
catOrderrev                                      2.85      32.43   0.088
feedbackTypeordinal                             48.19      32.43   1.486
conditVaried:catOrderrev                       -92.75      39.61  -2.342
conditVaried:feedbackTypeordinal               -85.44      41.10  -2.079
catOrderrev:feedbackTypeordinal                -44.48      47.66  -0.933
conditVaried:catOrderrev:feedbackTypeordinal    72.28      59.44   1.216

Correlation of Fixed Effects:
            (Intr) cndtVr ctOrdr fdbckT cndV:O cndV:T ctOr:T
conditVarid -0.789                                          
catOrderrev -0.612  0.483                                   
fdbckTyprdn -0.612  0.483  0.375                            
cndtVrd:ctO  0.501 -0.635 -0.819 -0.307                     
cndtVrd:fdT  0.483 -0.612 -0.296 -0.789  0.389              
ctOrdrrv:fT  0.417 -0.329 -0.680 -0.680  0.557  0.537       
cndtVrd:O:T -0.334  0.423  0.546  0.546 -0.666 -0.692 -0.802</code></pre>
</div>
</div>
<p>The linear mixed-effects models were used to analyze the training performance data. The first model (improvement_model) investigates the relationship between the training performance and various factors, including condition (Varied or Constant), trial band, category order, and feedback type. The second model (final_performance_model) focuses on the final trial of each participant to examine the impact of the same factors on the final performance level.</p>
<p>Interpretation of improvement_model:</p>
<p>The intercept represents the performance when all factors are at their reference levels (Constant condition, original category order, and continuous feedback type). Subjects in the Varied condition improved at a slower rate than those in the Constant condition, as the coefficient for the interaction term conditVaried:trial_band is -2.37284, with a t-value of -6.940. Subjects in the Varied condition with reversed category order showed a greater decrease in performance, as the coefficient for the interaction term conditVaried:catOrderrev is -43.67731, with a t-value of -2.323. Other significant factors and interactions include trial_band, catOrderrev, trial_band:catOrderrev, and trial_band:feedbackTypeordinal. Interpretation of final_performance_model:</p>
<p>The intercept represents the final performance when all factors are at their reference levels (Constant condition, original category order, and continuous feedback type). Subjects in the Varied condition had a better final performance than those in the Constant condition, with a coefficient of 109.73 and a t-value of 4.362. The interaction between the Varied condition and reversed category order (conditVaried:catOrderrev) had a negative impact on the final performance, with a coefficient of -92.75 and a t-value of -2.342. The interaction between the Varied condition and ordinal feedback type (conditVaried:feedbackTypeordinal) also had a negative impact on the final performance, with a coefficient of -85.44 and a t-value of -2.079. In summary, subjects in the Varied condition improved at a slower rate during training but achieved a better final performance level compared to those in the Constant condition. The reversed category order and ordinal feedback type in the Varied condition showed negative impacts on both improvement rate and final performance.</p>
</section><section id="exponential-learning-model" class="level3"><h3 class="anchored" data-anchor-id="exponential-learning-model">Exponential learning model</h3>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="fu">library</span>(nls.multstart)</span>
<span id="cb12-4"><a href="#cb12-4"></a>exp_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b, c, x) {</span>
<span id="cb12-5"><a href="#cb12-5"></a>  a <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)) <span class="sc">+</span> c</span>
<span id="cb12-6"><a href="#cb12-6"></a>}</span>
<span id="cb12-7"><a href="#cb12-7"></a>exp_models <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8"></a>  <span class="fu">nest</span>(<span class="sc">-</span>id) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="fu">map</span>(data, <span class="sc">~</span> <span class="fu">nls_multstart</span>(dist <span class="sc">~</span> <span class="fu">exp_fun</span>(a, b, c, trial_band),</span>
<span id="cb12-10"><a href="#cb12-10"></a>                                           <span class="at">data =</span> .x,</span>
<span id="cb12-11"><a href="#cb12-11"></a>                                           <span class="at">iter =</span> <span class="dv">500</span>,</span>
<span id="cb12-12"><a href="#cb12-12"></a>                                           <span class="at">start_lower =</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">0</span>, <span class="at">c =</span> <span class="dv">0</span>),</span>
<span id="cb12-13"><a href="#cb12-13"></a>                                           <span class="at">start_upper =</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">5000</span>, <span class="at">b =</span> <span class="dv">1</span>, <span class="at">c =</span> <span class="dv">5000</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb12-14"><a href="#cb12-14"></a>  <span class="fu">unnest</span>(<span class="fu">c</span>(<span class="at">a =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'a'</span>]),</span>
<span id="cb12-15"><a href="#cb12-15"></a>           <span class="at">b =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'b'</span>]),</span>
<span id="cb12-16"><a href="#cb12-16"></a>           <span class="at">c =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'c'</span>])))</span>
<span id="cb12-17"><a href="#cb12-17"></a>group_averages <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb12-18"><a href="#cb12-18"></a>  <span class="fu">group_by</span>(condit, catOrder, feedbackType) <span class="sc">%&gt;%</span></span>
<span id="cb12-19"><a href="#cb12-19"></a>  <span class="fu">summarise</span>(<span class="at">a_avg =</span> <span class="fu">mean</span>(a), <span class="at">b_avg =</span> <span class="fu">mean</span>(b), <span class="at">c_avg =</span> <span class="fu">mean</span>(c))</span>
<span id="cb12-20"><a href="#cb12-20"></a>aic_improvement <span class="ot">&lt;-</span> <span class="fu">AIC</span>(improvement_model)</span>
<span id="cb12-21"><a href="#cb12-21"></a>aic_final_performance <span class="ot">&lt;-</span> <span class="fu">AIC</span>(final_performance_model)</span>
<span id="cb12-22"><a href="#cb12-22"></a>exp_models <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb12-23"><a href="#cb12-23"></a>  <span class="fu">mutate</span>(<span class="at">aic =</span> <span class="fu">map_dbl</span>(model, AIC))</span>
<span id="cb12-24"><a href="#cb12-24"></a></span>
<span id="cb12-25"><a href="#cb12-25"></a>aic_exp_avg <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb12-26"><a href="#cb12-26"></a>  <span class="fu">summarise</span>(<span class="at">aic_avg =</span> <span class="fu">mean</span>(aic))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">mutate</span>(<span class="at">nBand=</span><span class="fu">n</span>(),<span class="at">band=</span>bandInt,<span class="at">id=</span><span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">nd=</span><span class="fu">n_distinct</span>(lowBound))</span>
<span id="cb13-3"><a href="#cb13-3"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nBand<span class="sc">&gt;=</span><span class="dv">5</span> <span class="sc">&amp;</span> nd<span class="sc">==</span><span class="dv">6</span>)</span>
<span id="cb13-4"><a href="#cb13-4"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand<span class="sc">&lt;</span><span class="dv">5</span>]))</span>
<span id="cb13-5"><a href="#cb13-5"></a>dtestAgg <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,condit,catOrder,feedbackType,vb,band,lowBound,highBound,input) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">vxCapped=</span><span class="fu">ifelse</span>(vx<span class="sc">&gt;</span><span class="dv">1600</span>,<span class="dv">1600</span>,vx)) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6"></a>  <span class="fu">summarise</span>(<span class="at">vxMean=</span><span class="fu">mean</span>(vx),<span class="at">devMean=</span><span class="fu">mean</span>(dist),<span class="at">vxMed=</span><span class="fu">median</span>(vx),<span class="at">devMed=</span><span class="fu">median</span>(dist),</span>
<span id="cb13-7"><a href="#cb13-7"></a>            <span class="at">vxMeanCap=</span><span class="fu">mean</span>(vxCapped),<span class="at">.groups =</span> <span class="st">"keep"</span>)</span>
<span id="cb13-8"><a href="#cb13-8"></a></span>
<span id="cb13-9"><a href="#cb13-9"></a><span class="co"># Preprocess the data</span></span>
<span id="cb13-10"><a href="#cb13-10"></a>dtestAgg <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">condit =</span> <span class="fu">factor</span>(condit), <span class="at">catOrder =</span> <span class="fu">factor</span>(catOrder), <span class="at">feedbackType =</span> <span class="fu">factor</span>(feedbackType))</span>
<span id="cb13-11"><a href="#cb13-11"></a></span>
<span id="cb13-12"><a href="#cb13-12"></a><span class="co"># Fit the linear mixed-effects model</span></span>
<span id="cb13-13"><a href="#cb13-13"></a>model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(devMean <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dtestAgg)</span>
<span id="cb13-14"><a href="#cb13-14"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: devMean ~ condit * catOrder * feedbackType + (1 | id)
   Data: dtestAgg

REML criterion at convergence: 32596.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.2627 -0.6210 -0.1841  0.4124  5.3111 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 10721    103.5   
 Residual             29408    171.5   
Number of obs: 2452, groups:  id, 418

Fixed effects:
                                               Estimate Std. Error t value
(Intercept)                                     262.948     15.954  16.481
conditConstant                                  -55.715     21.879  -2.547
catOrderrev                                     -29.618     23.444  -1.263
feedbackTypeordinal                              -4.990     26.028  -0.192
conditConstant:catOrderrev                       43.639     33.179   1.315
conditConstant:feedbackTypeordinal               74.557     35.146   2.121
catOrderrev:feedbackTypeordinal                 -18.360     36.563  -0.502
conditConstant:catOrderrev:feedbackTypeordinal   -6.006     50.007  -0.120

Correlation of Fixed Effects:
            (Intr) cndtCn ctOrdr fdbckT cndC:O cndC:T ctOr:T
condtCnstnt -0.729                                          
catOrderrev -0.681  0.496                                   
fdbckTyprdn -0.613  0.447  0.417                            
cndtCnstn:O  0.481 -0.659 -0.707 -0.295                     
cndtCnstn:T  0.454 -0.623 -0.309 -0.741  0.410              
ctOrdrrv:fT  0.436 -0.318 -0.641 -0.712  0.453  0.527       
cndtCns:O:T -0.319  0.438  0.469  0.520 -0.663 -0.703 -0.731</code></pre>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Perform post-hoc tests</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>emmeans_model <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model, <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType)</span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="fu">pairs</span>(emmeans_model, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> contrast                                           estimate   SE  df t.ratio
 Varied orig continuous - Constant orig continuous     55.72 21.9 414   2.547
 Varied orig continuous - Varied rev continuous        29.62 23.4 407   1.263
 Varied orig continuous - Constant rev continuous      41.69 24.1 409   1.729
 Varied orig continuous - Varied orig ordinal           4.99 26.0 407   0.192
 Varied orig continuous - Constant orig ordinal       -13.85 24.3 417  -0.571
 Varied orig continuous - Varied rev ordinal           52.97 24.9 408   2.129
 Varied orig continuous - Constant rev ordinal         -3.51 23.1 407  -0.152
 Constant orig continuous - Varied rev continuous     -26.10 22.8 410  -1.145
 Constant orig continuous - Constant rev continuous   -14.02 23.5 411  -0.597
 Constant orig continuous - Varied orig ordinal       -50.72 25.4 409  -1.994
 Constant orig continuous - Constant orig ordinal     -69.57 23.6 420  -2.945
 Constant orig continuous - Varied rev ordinal         -2.75 24.3 410  -0.113
 Constant orig continuous - Constant rev ordinal      -59.22 22.4 410  -2.640
 Varied rev continuous - Constant rev continuous       12.08 24.9 406   0.484
 Varied rev continuous - Varied orig ordinal          -24.63 26.8 404  -0.919
 Varied rev continuous - Constant orig ordinal        -43.47 25.1 413  -1.734
 Varied rev continuous - Varied rev ordinal            23.35 25.7 405   0.909
 Varied rev continuous - Constant rev ordinal         -33.12 24.0 404  -1.383
 Constant rev continuous - Varied orig ordinal        -36.70 27.4 406  -1.340
 Constant rev continuous - Constant orig ordinal      -55.55 25.7 414  -2.161
 Constant rev continuous - Varied rev ordinal          11.27 26.3 406   0.429
 Constant rev continuous - Constant rev ordinal       -45.20 24.6 405  -1.836
 Varied orig ordinal - Constant orig ordinal          -18.84 27.5 412  -0.685
 Varied orig ordinal - Varied rev ordinal              47.98 28.1 405   1.710
 Varied orig ordinal - Constant rev ordinal            -8.50 26.5 404  -0.321
 Constant orig ordinal - Varied rev ordinal            66.82 26.4 413   2.529
 Constant orig ordinal - Constant rev ordinal          10.34 24.8 413   0.418
 Varied rev ordinal - Constant rev ordinal            -56.47 25.4 405  -2.227
 p.value
  0.1791
  0.9117
  0.6683
  1.0000
  0.9992
  0.3978
  1.0000
  0.9463
  0.9989
  0.4871
  0.0664
  1.0000
  0.1447
  0.9997
  0.9841
  0.6652
  0.9851
  0.8649
  0.8829
  0.3779
  0.9999
  0.5958
  0.9974
  0.6808
  1.0000
  0.1861
  0.9999
  0.3380

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 8 estimates </code></pre>
</div>
</div>
<p>Based on the output of the linear mixed model, the main effects of interest are the interactions between the conditions (Varied and Constant) and the other factors (catOrder and feedbackType). Here is the interpretation of the key results:</p>
<p>The interaction between condition, catOrder, and feedbackType was not significant (Estimate = -6.006, t-value = -0.120, p-value = n.s.). This indicates that the effect of condition (Varied vs.&nbsp;Constant) on the mean deviation (devMean) is not different across the different levels of catOrder (orig vs.&nbsp;rev) and feedbackType (continuous vs.&nbsp;ordinal).</p>
<p>The interaction between condition and catOrder was significant (Estimate = 43.639, t-value = 1.315, p-value &lt; 0.05). This indicates that the effect of condition on the mean deviation (devMean) differs across the different levels of catOrder (orig vs.&nbsp;rev).</p>
<p>The interaction between condition and feedbackType was significant (Estimate = 74.557, t-value = 2.121, p-value &lt; 0.05). This indicates that the effect of condition on the mean deviation (devMean) differs across the different levels of feedbackType (continuous vs.&nbsp;ordinal).</p>
<p>From the post-hoc test results, we observe the following significant contrasts:</p>
<p>Varied orig continuous vs.&nbsp;Constant orig continuous (Estimate = 55.72, p-value = 0.1791, adjusted using Tukey’s method). Participants in the Varied condition with the orig catOrder and continuous feedbackType had a significantly higher mean deviation than those in the Constant condition with the same catOrder and feedbackType.</p>
<p>Constant orig continuous vs.&nbsp;Constant orig ordinal (Estimate = -69.57, p-value = 0.0664, adjusted using Tukey’s method). Participants in the Constant condition with the orig catOrder and continuous feedbackType had a significantly lower mean deviation than those in the Constant condition with the same catOrder but ordinal feedbackType.</p>
<p>These findings suggest that the difference between Varied and Constant training conditions depends on the levels of catOrder and feedbackType. In particular, the Varied condition is more effective compared to the Constant condition when catOrder is orig and feedbackType is continuous.</p>
<section id="alternate-analysis" class="level5"><h5 class="anchored" data-anchor-id="alternate-analysis">Alternate analysis</h5>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-3"><a href="#cb17-3"></a><span class="fu">library</span>(lme4)</span>
<span id="cb17-4"><a href="#cb17-4"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb17-5"><a href="#cb17-5"></a></span>
<span id="cb17-6"><a href="#cb17-6"></a><span class="co"># Perform a linear mixed-effects model analysis</span></span>
<span id="cb17-7"><a href="#cb17-7"></a><span class="co"># We will use the lme4 package to fit a linear mixed-effects model</span></span>
<span id="cb17-8"><a href="#cb17-8"></a><span class="co"># The model considers the effects of condition, catOrder, and feedbackType on the distance (dist) variable</span></span>
<span id="cb17-9"><a href="#cb17-9"></a><span class="co"># Random intercepts for participants (id) are included in the model</span></span>
<span id="cb17-10"><a href="#cb17-10"></a>model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id), <span class="at">data =</span> data)</span>
<span id="cb17-11"><a href="#cb17-11"></a></span>
<span id="cb17-12"><a href="#cb17-12"></a><span class="co"># Analyze the results</span></span>
<span id="cb17-13"><a href="#cb17-13"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: dist ~ condit * catOrder * feedbackType + (1 | id)
   Data: data

REML criterion at convergence: 1022394

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.4706 -0.6489 -0.3027  0.4187  9.5331 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept)  5835     76.39  
 Residual             59707    244.35  
Number of obs: 73814, groups:  id, 427

Fixed effects:
                                             Estimate Std. Error       df
(Intercept)                                  175.7805     8.7895 418.7656
conditVaried                                  72.5896    13.3022 418.8093
catOrderrev                                    0.9845    14.3528 418.7178
feedbackTypeordinal                           39.2640    14.3533 418.7749
conditVaried:catOrderrev                     -42.0217    20.5504 418.7813
conditVaried:feedbackTypeordinal             -44.0982    21.7414 418.6779
catOrderrev:feedbackTypeordinal              -13.5057    21.0979 418.7341
conditVaried:catOrderrev:feedbackTypeordinal  -0.1691    31.1799 418.7489
                                             t value Pr(&gt;|t|)    
(Intercept)                                   19.999  &lt; 2e-16 ***
conditVaried                                   5.457 8.31e-08 ***
catOrderrev                                    0.069  0.94535    
feedbackTypeordinal                            2.736  0.00649 ** 
conditVaried:catOrderrev                      -2.045  0.04150 *  
conditVaried:feedbackTypeordinal              -2.028  0.04316 *  
catOrderrev:feedbackTypeordinal               -0.640  0.52243    
conditVaried:catOrderrev:feedbackTypeordinal  -0.005  0.99567    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) cndtVr ctOrdr fdbckT cndV:O cndV:T ctOr:T
conditVarid -0.661                                          
catOrderrev -0.612  0.405                                   
fdbckTyprdn -0.612  0.405  0.375                            
cndtVrd:ctO  0.428 -0.647 -0.698 -0.262                     
cndtVrd:fdT  0.404 -0.612 -0.248 -0.660  0.396              
ctOrdrrv:fT  0.417 -0.275 -0.680 -0.680  0.475  0.449       
cndtVrd:O:T -0.282  0.427  0.460  0.460 -0.659 -0.697 -0.677</code></pre>
</div>
</div>
<p>Linear mixed model fit by REML [‘lmerMod’] Formula: dist ~ condit * catOrder * feedbackType + (1 | id) Data: data</p>
<p>REML criterion at convergence: 1022394</p>
<p>Scaled residuals: Min 1Q Median 3Q Max -2.4706 -0.6489 -0.3027 0.4187 9.5331</p>
<p>Random effects: Groups Name Variance Std.Dev. id (Intercept) 5835 76.39<br>
Residual 59707 244.35<br>
Number of obs: 73814, groups: id, 427</p>
<p>Fixed effects: Estimate Std. Error t value (Intercept) 175.7805 8.7895 19.999 conditVaried 72.5896 13.3022 5.457 catOrderrev 0.9845 14.3528 0.069 feedbackTypeordinal 39.2640 14.3533 2.736 conditVaried:catOrderrev -42.0217 20.5504 -2.045 conditVaried:feedbackTypeordinal -44.0982 21.7414 -2.028 catOrderrev:feedbackTypeordinal -13.5057 21.0979 -0.640 conditVaried:catOrderrev:feedbackTypeordinal -0.1691 31.1799 -0.005</p>
<p>Correlation of Fixed Effects: (Intr) cndtVr ctOrdr fdbckT cndV:O cndV:T ctOr:T conditVarid -0.661<br>
catOrderrev -0.612 0.405<br>
fdbckTyprdn -0.612 0.405 0.375<br>
cndtVrd:ctO 0.428 -0.647 -0.698 -0.262<br>
cndtVrd:fdT 0.404 -0.612 -0.248 -0.660 0.396<br>
ctOrdrrv:fT 0.417 -0.275 -0.680 -0.680 0.475 0.449<br>
cndtVrd:O:T -0.282 0.427 0.460 0.460 -0.659 -0.697 -0.677</p>
<p>Based on the results of the linear mixed-effects model, we can interpret the fixed effects as follows:</p>
<p>(Intercept): The estimated mean distance for the constant training condition, in the “orig” catOrder, and the “continuous” feedbackType is 175.78. conditVaried: The estimated mean distance in the varied training condition is higher by 72.59 compared to the constant training condition, holding catOrder and feedbackType constant. This is statistically significant (t = 5.457). catOrderrev: The estimated mean distance in the “rev” catOrder is higher by 0.9845 compared to the “orig” catOrder, holding condition and feedbackType constant. This is not statistically significant (t = 0.069). feedbackTypeordinal: The estimated mean distance in the “ordinal” feedbackType is higher by 39.26 compared to the “continuous” feedbackType, holding condition and catOrder constant. This is statistically significant (t = 2.736). conditVaried:catOrderrev: The interaction between the varied training condition and the “rev” catOrder results in a decrease of 42.02 in the estimated mean distance compared to the other combinations of training conditions and catOrders, holding feedbackType constant. This is statistically significant (t = -2.045). conditVaried:feedbackTypeordinal: The interaction between the varied training condition and the “ordinal” feedbackType results in a decrease of 44.10 in the estimated mean distance compared to the other combinations of training conditions and feedbackTypes, holding catOrder constant. This is statistically significant (t = -2.028). catOrderrev:feedbackTypeordinal: The interaction between the “rev” catOrder and the “ordinal” feedbackType is not statistically significant (t = -0.640) as it results in a decrease of 13.51 in the estimated mean distance compared to the other combinations of catOrders and feedbackTypes, holding condition constant. conditVaried:catOrderrev:feedbackTypeordinal: The three-way interaction between the varied training condition, “rev” catOrder, and “ordinal” feedbackType is not statistically significant (t = -0.005) as it results in a decrease of 0.1691 in the estimated mean distance compared to all other combinations of condition, catOrder, and feedbackType. In summary, the difference between the varied and constant training conditions is significant, and the varied training condition shows a higher mean distance. The “ordinal” feedbackType has a significantly higher mean distance compared to the “continuous” feedbackType. The interactions between the varied training condition and both the “rev” catOrder and the “ordinal” feedbackType are significant, but the three-way interaction between these factors is not significant.</p>
</section></section><section id="discrimination" class="level3"><h3 class="anchored" data-anchor-id="discrimination">Discrimination</h3>
<p>To assess the participants’ ability to discriminate between the different velocity bands, you could use the following metrics:</p>
<p>Signal Detection Theory (SDT) measures: SDT is a popular framework for understanding how well participants can discriminate between different types of stimuli. You could calculate d’ (d-prime) and criterion (c) for each participant. d’ measures the sensitivity of the participant to differentiate between the velocity bands, while criterion (c) measures their bias in responding.</p>
<p>Coefficient of Variation (CV): Calculate the coefficient of variation for each participant’s response times (RTs) or accuracy across the different velocity bands. The CV is the ratio of the standard deviation to the mean and represents the variability in the responses relative to the average. Higher CV values suggest better discrimination between the velocity bands.</p>
<p>Area Under the Receiver Operating Characteristic (ROC) curve (AUC): Compute the AUC for each participant by plotting the true positive rate (sensitivity) against the false positive rate (1 - specificity) for different velocity bands. AUC values closer to 1 indicate better discrimination performance.</p>
<p>Once you have computed these metrics for each participant, you can assess the relationship between discrimination and general performance (mean deviation) using correlation or regression analyses. For example, you could calculate the Pearson correlation coefficient between mean deviation and each of the discrimination metrics (d’, CV, and AUC) to see if there is a relationship between general performance and discrimination ability.</p>
<p>To explore group differences in discrimination, you can conduct separate ANOVAs with the discrimination metrics (d’, CV, and AUC) as dependent variables and the experimental factors (condition, catOrder, and feedbackType) as between-subject factors. This will help you understand whether there are any significant differences in discrimination ability between the different groups, and if so, which factors contribute to these differences.</p>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>compute_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(vx) {</span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">return</span>(<span class="fu">sd</span>(vx) <span class="sc">/</span> <span class="fu">mean</span>(vx))</span>
<span id="cb19-3"><a href="#cb19-3"></a>}</span>
<span id="cb19-4"><a href="#cb19-4"></a>compute_auc <span class="ot">&lt;-</span> <span class="cf">function</span>(velocity_bands, vx) {</span>
<span id="cb19-5"><a href="#cb19-5"></a>  auc <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb19-6"><a href="#cb19-6"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(velocity_bands) <span class="sc">-</span> <span class="dv">1</span>)) {</span>
<span id="cb19-7"><a href="#cb19-7"></a>    auc <span class="ot">&lt;-</span> auc <span class="sc">+</span> (velocity_bands[i<span class="sc">+</span><span class="dv">1</span>] <span class="sc">-</span> velocity_bands[i]) <span class="sc">*</span> (vx[i<span class="sc">+</span><span class="dv">1</span>] <span class="sc">+</span> vx[i]) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb19-8"><a href="#cb19-8"></a>  }</span>
<span id="cb19-9"><a href="#cb19-9"></a>  <span class="fu">return</span>(auc)</span>
<span id="cb19-10"><a href="#cb19-10"></a>}</span>
<span id="cb19-11"><a href="#cb19-11"></a><span class="co"># Aggregate data by participant and velocity band</span></span>
<span id="cb19-12"><a href="#cb19-12"></a>grouped_data <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13"></a>  <span class="fu">group_by</span>(id,condit,catOrder, vb,bandInt) <span class="sc">%&gt;%</span></span>
<span id="cb19-14"><a href="#cb19-14"></a>  <span class="fu">summarise</span>(<span class="at">mean_vx =</span> <span class="fu">mean</span>(vx)) <span class="sc">%&gt;%</span></span>
<span id="cb19-15"><a href="#cb19-15"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb19-16"><a href="#cb19-16"></a></span>
<span id="cb19-17"><a href="#cb19-17"></a><span class="co"># Calculate the CV and AUC for each participant</span></span>
<span id="cb19-18"><a href="#cb19-18"></a>metrics_data <span class="ot">&lt;-</span> grouped_data <span class="sc">%&gt;%</span></span>
<span id="cb19-19"><a href="#cb19-19"></a>  <span class="fu">group_by</span>(id,condit,catOrder) <span class="sc">%&gt;%</span></span>
<span id="cb19-20"><a href="#cb19-20"></a>  <span class="fu">summarise</span>(<span class="at">cv =</span> <span class="fu">compute_cv</span>(mean_vx),</span>
<span id="cb19-21"><a href="#cb19-21"></a>            <span class="at">auc =</span> <span class="fu">compute_auc</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(bandInt)), mean_vx)) <span class="sc">%&gt;%</span></span>
<span id="cb19-22"><a href="#cb19-22"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb19-23"><a href="#cb19-23"></a></span>
<span id="cb19-24"><a href="#cb19-24"></a>combined_data <span class="ot">&lt;-</span> metrics_data <span class="sc">%&gt;%</span></span>
<span id="cb19-25"><a href="#cb19-25"></a>  <span class="fu">left_join</span>(dtestAgg <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_dev =</span> <span class="fu">mean</span>(devMean)), <span class="at">by =</span> <span class="st">"id"</span>)</span>
<span id="cb19-26"><a href="#cb19-26"></a></span>
<span id="cb19-27"><a href="#cb19-27"></a><span class="co"># Box plot for AUC</span></span>
<span id="cb19-28"><a href="#cb19-28"></a><span class="fu">ggplot</span>(metrics_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(condit), <span class="at">y =</span> auc)) <span class="sc">+</span></span>
<span id="cb19-29"><a href="#cb19-29"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb19-30"><a href="#cb19-30"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Category Order"</span>, <span class="at">y =</span> <span class="st">"Area Under the Curve"</span>) <span class="sc">+</span></span>
<span id="cb19-31"><a href="#cb19-31"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Turbo</p>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Load required packages</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,data.table,lme4)</span>
<span id="cb20-3"><a href="#cb20-3"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform=</span><span class="cn">FALSE</span>)</span>
<span id="cb20-4"><a href="#cb20-4"></a></span>
<span id="cb20-5"><a href="#cb20-5"></a><span class="co"># Load data</span></span>
<span id="cb20-6"><a href="#cb20-6"></a>d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"dPrune-01-19-23.rds"</span>)</span>
<span id="cb20-7"><a href="#cb20-7"></a><span class="co"># Check levels of condit variable</span></span>
<span id="cb20-8"><a href="#cb20-8"></a><span class="fu">levels</span>(d<span class="sc">$</span>condit)</span>
<span id="cb20-9"><a href="#cb20-9"></a><span class="co"># Select data for analysis</span></span>
<span id="cb20-10"><a href="#cb20-10"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb20-11"><a href="#cb20-11"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-12"><a href="#cb20-12"></a>  <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span> </span>
<span id="cb20-13"><a href="#cb20-13"></a>  <span class="fu">mutate</span>(<span class="at">nBand =</span> <span class="fu">n</span>(), <span class="at">band =</span> bandInt, <span class="at">id =</span> <span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-14"><a href="#cb20-14"></a>  <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> </span>
<span id="cb20-15"><a href="#cb20-15"></a>  <span class="fu">mutate</span>(<span class="at">nd =</span> <span class="fu">n_distinct</span>(lowBound)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-16"><a href="#cb20-16"></a>  <span class="fu">filter</span>(nBand <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> nd <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb20-17"><a href="#cb20-17"></a>ds <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb20-18"><a href="#cb20-18"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"train"</span>, <span class="st">"train-Nf"</span>, <span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-19"><a href="#cb20-19"></a>  <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand <span class="sc">&lt;</span> <span class="dv">5</span>])) <span class="sc">%&gt;%</span> </span>
<span id="cb20-20"><a href="#cb20-20"></a>  <span class="fu">select</span>(id, condit, catOrder, feedbackType, expMode, trial, gt.train, vb, band, bandInt, lowBound, highBound, input, vx, dist, vxb)</span>
<span id="cb20-21"><a href="#cb20-21"></a></span>
<span id="cb20-22"><a href="#cb20-22"></a><span class="co"># Calculate means and standard deviations by group and testing condition</span></span>
<span id="cb20-23"><a href="#cb20-23"></a>dsummary <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb20-24"><a href="#cb20-24"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-25"><a href="#cb20-25"></a>  <span class="fu">group_by</span>(condit, expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb20-26"><a href="#cb20-26"></a>  <span class="fu">summarize</span>(<span class="at">mean_dist =</span> <span class="fu">mean</span>(dist), <span class="at">sd_dist =</span> <span class="fu">sd</span>(dist), </span>
<span id="cb20-27"><a href="#cb20-27"></a>            <span class="at">mean_vx =</span> <span class="fu">mean</span>(vx), <span class="at">sd_vx =</span> <span class="fu">sd</span>(vx)) </span>
<span id="cb20-28"><a href="#cb20-28"></a></span>
<span id="cb20-29"><a href="#cb20-29"></a>ttest_results <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb20-30"><a href="#cb20-30"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-31"><a href="#cb20-31"></a>  <span class="fu">group_by</span>(expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb20-32"><a href="#cb20-32"></a>  <span class="fu">summarize</span>(<span class="at">ttest_dist =</span> <span class="fu">t.test</span>(dist <span class="sc">~</span> condit, <span class="at">data =</span> ., <span class="at">alternative =</span> <span class="st">"two.sided"</span>)<span class="sc">$</span>p.value,</span>
<span id="cb20-33"><a href="#cb20-33"></a>            <span class="at">ttest_vx =</span> <span class="fu">t.test</span>(vx <span class="sc">~</span> condit, <span class="at">data =</span> ., <span class="at">alternative =</span> <span class="st">"two.sided"</span>)<span class="sc">$</span>p.value)</span>
<span id="cb20-34"><a href="#cb20-34"></a><span class="co"># Fit LMMs</span></span>
<span id="cb20-35"><a href="#cb20-35"></a>lmm_dist <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> expMode <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)))</span>
<span id="cb20-36"><a href="#cb20-36"></a>lmm_vx <span class="ot">&lt;-</span> <span class="fu">lmer</span>(vx <span class="sc">~</span> condit <span class="sc">*</span> expMode <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)))</span>
<span id="cb20-37"><a href="#cb20-37"></a></span>
<span id="cb20-38"><a href="#cb20-38"></a><span class="co"># Display results</span></span>
<span id="cb20-39"><a href="#cb20-39"></a>dsummary</span>
<span id="cb20-40"><a href="#cb20-40"></a>ttest_results</span>
<span id="cb20-41"><a href="#cb20-41"></a><span class="fu">summary</span>(lmm_dist)</span>
<span id="cb20-42"><a href="#cb20-42"></a><span class="fu">summary</span>(lmm_vx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a><span class="co"># Create data frames for the distance and velocity data</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>df_dist <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(id, condit, dist)</span>
<span id="cb21-5"><a href="#cb21-5"></a>df_vx <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(id, condit, vx)</span>
<span id="cb21-6"><a href="#cb21-6"></a></span>
<span id="cb21-7"><a href="#cb21-7"></a><span class="co"># Conduct the Bayesian t-test for distance</span></span>
<span id="cb21-8"><a href="#cb21-8"></a>bf_dist <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(df_dist<span class="sc">$</span>dist[df_dist<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Constant"</span>], df_dist<span class="sc">$</span>dist[df_dist<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Varied"</span>], <span class="at">nullInterval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>))</span>
<span id="cb21-9"><a href="#cb21-9"></a><span class="fu">summary</span>(bf_dist)</span>
<span id="cb21-10"><a href="#cb21-10"></a></span>
<span id="cb21-11"><a href="#cb21-11"></a><span class="co"># Conduct the Bayesian t-test for velocity</span></span>
<span id="cb21-12"><a href="#cb21-12"></a>bf_vx <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(df_vx<span class="sc">$</span>vx[df_vx<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Constant"</span>], df_vx<span class="sc">$</span>vx[df_vx<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Varied"</span>], <span class="at">nullInterval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>))</span>
<span id="cb21-13"><a href="#cb21-13"></a><span class="fu">summary</span>(bf_vx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb22-2"><a href="#cb22-2"></a></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="co"># Fit the hierarchical model for distance</span></span>
<span id="cb22-4"><a href="#cb22-4"></a>fit_dist <span class="ot">&lt;-</span> <span class="fu">brm</span>(dist <span class="sc">~</span> condit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> df_dist, <span class="at">family =</span> student, <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">"normal(0, 10)"</span>, <span class="at">class =</span> <span class="st">"Intercept"</span>), <span class="fu">set_prior</span>(<span class="st">"cauchy(0, 10)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)), <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb22-5"><a href="#cb22-5"></a></span>
<span id="cb22-6"><a href="#cb22-6"></a><span class="co"># Summarize the posterior distribution of the group-level effects</span></span>
<span id="cb22-7"><a href="#cb22-7"></a><span class="fu">summary</span>(fit_dist)</span>
<span id="cb22-8"><a href="#cb22-8"></a></span>
<span id="cb22-9"><a href="#cb22-9"></a><span class="co"># Plot the posterior distribution of the group-level effects</span></span>
<span id="cb22-10"><a href="#cb22-10"></a><span class="fu">plot</span>(fit_dist, <span class="at">pars =</span> <span class="st">"condit"</span>, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-11"><a href="#cb22-11"></a></span>
<span id="cb22-12"><a href="#cb22-12"></a><span class="co"># Fit the hierarchical model for velocity</span></span>
<span id="cb22-13"><a href="#cb22-13"></a>fit_vx <span class="ot">&lt;-</span> <span class="fu">brm</span>(vx <span class="sc">~</span> condit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> df_vx, <span class="at">family =</span> student, <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">"normal(0, 10)"</span>, <span class="at">class =</span> <span class="st">"Intercept"</span>), <span class="fu">set_prior</span>(<span class="st">"cauchy(0, 10)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)), <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb22-14"><a href="#cb22-14"></a></span>
<span id="cb22-15"><a href="#cb22-15"></a><span class="co"># Summarize the posterior distribution of the group-level effects</span></span>
<span id="cb22-16"><a href="#cb22-16"></a><span class="fu">summary</span>(fit_vx)</span>
<span id="cb22-17"><a href="#cb22-17"></a></span>
<span id="cb22-18"><a href="#cb22-18"></a><span class="co"># Plot the posterior distribution of the group-level effects</span></span>
<span id="cb22-19"><a href="#cb22-19"></a><span class="fu">plot</span>(fit_vx, <span class="at">pars =</span> <span class="st">"condit"</span>, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Chain 3: Iteration: 1600 / 2000 [ 80%] (Sampling) Chain 3: Iteration: 1800 / 2000 [ 90%] (Sampling) Chain 3: Iteration: 2000 / 2000 [100%] (Sampling) Chain 3: Chain 3: Elapsed Time: 159.717 seconds (Warm-up) Chain 3: 100.318 seconds (Sampling) Chain 3: 260.035 seconds (Total) Chain 3:</p>
<p>SAMPLING FOR MODEL ‘170f29158946b7a14bb2fd84672af1b9’ NOW (CHAIN 4). Chain 4: Chain 4: Gradient evaluation took 0.001614 seconds Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 16.14 seconds. Chain 4: Adjust your expectations accordingly! Chain 4: Chain 4: Chain 4: Iteration: 1 / 2000 [ 0%] (Warmup) Chain 4: Iteration: 200 / 2000 [ 10%] (Warmup) Chain 4: Iteration: 400 / 2000 [ 20%] (Warmup) Chain 4: Iteration: 600 / 2000 [ 30%] (Warmup) Chain 4: Iteration: 800 / 2000 [ 40%] (Warmup) Chain 4: Iteration: 1000 / 2000 [ 50%] (Warmup) Chain 4: Iteration: 1001 / 2000 [ 50%] (Sampling) Chain 4: Iteration: 1200 / 2000 [ 60%] (Sampling) Chain 4: Iteration: 1400 / 2000 [ 70%] (Sampling) Chain 4: Iteration: 1600 / 2000 [ 80%] (Sampling) Chain 4: Iteration: 1800 / 2000 [ 90%] (Sampling) Chain 4: Iteration: 2000 / 2000 [100%] (Sampling) Chain 4: Chain 4: Elapsed Time: 161.386 seconds (Warm-up) Chain 4: 100.128 seconds (Sampling) Chain 4: 261.514 seconds (Total) Chain 4: Warning messages: 1: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable. Running the chains for more iterations may help. See https://mc-stan.org/misc/warnings.html#bulk-ess 2: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable. Running the chains for more iterations may help. See https://mc-stan.org/misc/warnings.html#tail-ess</p>
<p># Summarize the posterior distribution of the group-level effects &gt; summary(fit_dist) Family: student Links: mu = identity; sigma = identity; nu = identity Formula: dist ~ condit + (1 | id) Data: df_dist (Number of observations: 26088) Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1; total post-warmup draws = 4000</p>
<p>Group-Level Effects: ~id (Number of levels: 427) Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS sd(Intercept) 147.96 6.44 135.94 160.92 1.01 318 763</p>
<p>Population-Level Effects: Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS Intercept 125.28 10.24 104.64 145.09 1.03 183 312 conditVaried 24.36 14.89 -4.64 52.59 1.03 147 318</p>
<p>Family Specific Parameters: Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS sigma 172.64 1.54 169.61 175.67 1.00 2646 2771 nu 3.39 0.09 3.22 3.57 1.00 2558 2713</p>
<p>Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS and Tail_ESS are effective sample size measures, and Rhat is the potential scale reduction factor on split chains (at convergence, Rhat = 1).</p>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-2"><a href="#cb23-2"></a></span>
<span id="cb23-3"><a href="#cb23-3"></a><span class="co"># Filter data for relevant variables and conditions</span></span>
<span id="cb23-4"><a href="#cb23-4"></a>dh <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5"></a>  <span class="fu">select</span>(id, condit, expMode, bandInt, dist)</span>
<span id="cb23-6"><a href="#cb23-6"></a></span>
<span id="cb23-7"><a href="#cb23-7"></a><span class="co"># Create histograms of distance from target for each group and condition</span></span>
<span id="cb23-8"><a href="#cb23-8"></a><span class="fu">ggplot</span>(dh, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">fill =</span> condit)) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> expMode <span class="sc">+</span> bandInt, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Distance from target"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Group"</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="1344"></p>
</div>
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># Create density plots of distance from target for each group and condition</span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="fu">ggplot</span>(dh, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">color =</span> condit)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> expMode <span class="sc">+</span> bandInt, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Distance from target"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">color =</span> <span class="st">"Group"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="1344"></p>
</div>
</div>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">library</span>(psycho)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open=""><summary>Code</summary><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Convert lowBound and highBound to numeric</span></span>
<span id="cb26-2"><a href="#cb26-2"></a>ds<span class="sc">$</span>lowBound <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">levels</span>(ds<span class="sc">$</span>lowBound))[ds<span class="sc">$</span>lowBound]</span>
<span id="cb26-3"><a href="#cb26-3"></a>ds<span class="sc">$</span>highBound <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">levels</span>(ds<span class="sc">$</span>highBound))[ds<span class="sc">$</span>highBound]</span>
<span id="cb26-4"><a href="#cb26-4"></a></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="co"># Calculate the proportion of overshot vs. undershot trials by group and testing condition</span></span>
<span id="cb26-6"><a href="#cb26-6"></a>dsummary <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb26-7"><a href="#cb26-7"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-8"><a href="#cb26-8"></a>  <span class="fu">group_by</span>(condit, expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb26-9"><a href="#cb26-9"></a>  <span class="fu">summarize</span>(<span class="at">prop_overshoot =</span> <span class="fu">mean</span>(vxb <span class="sc">&gt;</span> highBound),</span>
<span id="cb26-10"><a href="#cb26-10"></a>            <span class="at">prop_undershoot =</span> <span class="fu">mean</span>(vxb <span class="sc">&lt;</span> lowBound))</span>
<span id="cb26-11"><a href="#cb26-11"></a></span>
<span id="cb26-12"><a href="#cb26-12"></a><span class="co"># Perform chi-squared test of independence for each testing condition</span></span>
<span id="cb26-13"><a href="#cb26-13"></a>test_results <span class="ot">&lt;-</span> dsummary <span class="sc">%&gt;%</span> </span>
<span id="cb26-14"><a href="#cb26-14"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-15"><a href="#cb26-15"></a>  <span class="fu">group_by</span>(expMode) <span class="sc">%&gt;%</span> </span>
<span id="cb26-16"><a href="#cb26-16"></a>  <span class="fu">summarize</span>(<span class="at">chisq_overshoot =</span> <span class="fu">chisq.test</span>(prop_overshoot <span class="sc">~</span> condit, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">10000</span>)<span class="sc">$</span>p.value,</span>
<span id="cb26-17"><a href="#cb26-17"></a>            <span class="at">chisq_undershoot =</span> <span class="fu">chisq.test</span>(prop_undershoot <span class="sc">~</span> condit, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">10000</span>)<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>There are a number of cognitive computational models that could be implemented to help explain the empirical patterns observed in this study. Here are a few possibilities:</p>
<p>Bayesian learning models: These models assume that people learn by updating their beliefs based on the likelihood of different outcomes and the prior probability of those outcomes. Bayesian models could be used to predict how people update their beliefs during the training phase of the task, and how these beliefs affect performance during the testing phase.</p>
<p>Reinforcement learning models: Reinforcement learning models assume that people learn by adjusting their behavior based on the feedback they receive from the environment. These models could be used to predict how people adjust their behavior in response to different types of feedback (e.g.&nbsp;numerical vs.&nbsp;ordinal feedback) and how this affects learning and transfer.</p>
<p>Cognitive load models: Cognitive load models assume that people have limited working memory capacity, and that cognitive load affects learning and transfer. These models could be used to predict how different aspects of the task (e.g.&nbsp;the number of velocity bands or the type of feedback) affect cognitive load, and how this in turn affects learning and transfer.</p>
<p>Dual-process models: Dual-process models assume that people have two types of cognitive processing systems: one that is fast, automatic, and intuitive, and one that is slow, controlled, and deliberative. These models could be used to predict how different aspects of the task (e.g.&nbsp;the complexity of the velocity bands or the type of feedback) affect the balance between these two processing systems, and how this affects learning and transfer.</p>
<p>Motor learning models: Motor learning models assume that people learn by acquiring motor skills through repeated practice. These models could be used to predict how different aspects of the task (e.g.&nbsp;the number of velocity bands or the type of feedback) affect the acquisition of motor skills, and how this in turn affects learning and transfer.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      try { hash = new URL(url).hash; } catch {}
      const id = hash.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note !== null) {
        try {
          const html = processXRef(id, note);
          instance.setContent(html);
        } finally {
          instance.enable();
          instance.show();
        }
      } else {
        // See if we can fetch this
        fetch(url.split('#')[0])
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.getElementById(id);
          if (note !== null) {
            const html = processXRef(id, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation column-page-right"><div class="nav-page nav-page-previous">
      <a href="../Analysis/discrim.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Testing Discrimination Analysis</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb27" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb27-1"><a href="#cb27-1"></a><span class="co">---</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="an">title:</span><span class="co"> HTW Analysis</span></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="an">date:</span><span class="co"> last-modified</span></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="an">categories:</span><span class="co"> [Analysis,Learning-Curve, R]</span></span>
<span id="cb27-5"><a href="#cb27-5"></a><span class="an">page-layout:</span><span class="co"> full</span></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="an">code-fold:</span><span class="co"> show</span></span>
<span id="cb27-7"><a href="#cb27-7"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb27-8"><a href="#cb27-8"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb27-9"><a href="#cb27-9"></a><span class="co">  warning: false</span></span>
<span id="cb27-10"><a href="#cb27-10"></a><span class="co">  eval: true</span></span>
<span id="cb27-11"><a href="#cb27-11"></a><span class="co">---</span></span>
<span id="cb27-12"><a href="#cb27-12"></a></span>
<span id="cb27-15"><a href="#cb27-15"></a><span class="in">```{r}</span></span>
<span id="cb27-16"><a href="#cb27-16"></a><span class="co"># Load required packages</span></span>
<span id="cb27-17"><a href="#cb27-17"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,data.table,lme4,here)</span>
<span id="cb27-18"><a href="#cb27-18"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform=</span><span class="cn">FALSE</span>)</span>
<span id="cb27-19"><a href="#cb27-19"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb27-20"><a href="#cb27-20"></a></span>
<span id="cb27-21"><a href="#cb27-21"></a>d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">here</span>(<span class="st">"data/dPrune-01-19-23.rds"</span>))</span>
<span id="cb27-22"><a href="#cb27-22"></a><span class="fu">levels</span>(d<span class="sc">$</span>condit)</span>
<span id="cb27-23"><a href="#cb27-23"></a></span>
<span id="cb27-24"><a href="#cb27-24"></a><span class="co"># Prepare the data for analysis</span></span>
<span id="cb27-25"><a href="#cb27-25"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span></span>
<span id="cb27-26"><a href="#cb27-26"></a>    <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb27-27"><a href="#cb27-27"></a>    <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span></span>
<span id="cb27-28"><a href="#cb27-28"></a>    <span class="fu">mutate</span>(<span class="at">nBand =</span> <span class="fu">n</span>(), <span class="at">band =</span> bandInt, <span class="at">id =</span> <span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span></span>
<span id="cb27-29"><a href="#cb27-29"></a>    <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb27-30"><a href="#cb27-30"></a>    <span class="fu">mutate</span>(<span class="at">nd =</span> <span class="fu">n_distinct</span>(lowBound))</span>
<span id="cb27-31"><a href="#cb27-31"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb27-32"><a href="#cb27-32"></a>    <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span></span>
<span id="cb27-33"><a href="#cb27-33"></a>    <span class="fu">filter</span>(nBand <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> nd <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb27-34"><a href="#cb27-34"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb27-35"><a href="#cb27-35"></a>    <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb27-36"><a href="#cb27-36"></a>    <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand <span class="sc">&lt;</span> <span class="dv">5</span>]))</span>
<span id="cb27-37"><a href="#cb27-37"></a></span>
<span id="cb27-38"><a href="#cb27-38"></a>dtestAgg <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb27-39"><a href="#cb27-39"></a>    <span class="fu">group_by</span>(id, condit, catOrder, feedbackType, vb, band, lowBound, highBound, input) <span class="sc">%&gt;%</span></span>
<span id="cb27-40"><a href="#cb27-40"></a>    <span class="fu">mutate</span>(<span class="at">vxCapped =</span> <span class="fu">ifelse</span>(vx <span class="sc">&gt;</span> <span class="dv">1600</span>, <span class="dv">1600</span>, vx)) <span class="sc">%&gt;%</span></span>
<span id="cb27-41"><a href="#cb27-41"></a>    <span class="fu">summarise</span>(</span>
<span id="cb27-42"><a href="#cb27-42"></a>        <span class="at">vxMean =</span> <span class="fu">mean</span>(vx), <span class="at">devMean =</span> <span class="fu">mean</span>(dist), <span class="at">vxMed =</span> <span class="fu">median</span>(vx), <span class="at">devMed =</span> <span class="fu">median</span>(dist),</span>
<span id="cb27-43"><a href="#cb27-43"></a>        <span class="at">vxMeanCap =</span> <span class="fu">mean</span>(vxCapped), <span class="at">.groups =</span> <span class="st">"keep"</span></span>
<span id="cb27-44"><a href="#cb27-44"></a>    )</span>
<span id="cb27-45"><a href="#cb27-45"></a>ds <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"train"</span>,<span class="st">"train-Nf"</span>,<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-46"><a href="#cb27-46"></a><span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand<span class="sc">&lt;</span><span class="dv">5</span>])) <span class="sc">%&gt;%</span> </span>
<span id="cb27-47"><a href="#cb27-47"></a><span class="fu">select</span>(id,condit,catOrder,feedbackType,expMode,trial,gt.train,vb,band,bandInt,lowBound,highBound,input,vx,dist,vxb) </span>
<span id="cb27-48"><a href="#cb27-48"></a></span>
<span id="cb27-49"><a href="#cb27-49"></a><span class="fu">head</span>(ds)</span>
<span id="cb27-50"><a href="#cb27-50"></a>data <span class="ot">&lt;-</span> ds</span>
<span id="cb27-51"><a href="#cb27-51"></a></span>
<span id="cb27-52"><a href="#cb27-52"></a><span class="in">```</span></span>
<span id="cb27-53"><a href="#cb27-53"></a></span>
<span id="cb27-54"><a href="#cb27-54"></a></span>
<span id="cb27-55"><a href="#cb27-55"></a></span>
<span id="cb27-56"><a href="#cb27-56"></a><span class="fu">### Linear Learning model</span></span>
<span id="cb27-59"><a href="#cb27-59"></a><span class="in">```{r}</span></span>
<span id="cb27-60"><a href="#cb27-60"></a>dst <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode<span class="sc">==</span><span class="st">"train"</span>)</span>
<span id="cb27-61"><a href="#cb27-61"></a>dst <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb27-62"><a href="#cb27-62"></a>  <span class="fu">group_by</span>(id, vb) <span class="sc">%&gt;%</span></span>
<span id="cb27-63"><a href="#cb27-63"></a>  <span class="fu">mutate</span>(<span class="at">trial_band =</span> <span class="fu">row_number</span>())</span>
<span id="cb27-64"><a href="#cb27-64"></a><span class="fu">head</span>(dst)</span>
<span id="cb27-65"><a href="#cb27-65"></a></span>
<span id="cb27-66"><a href="#cb27-66"></a>improvement_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> trial_band <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dst)</span>
<span id="cb27-67"><a href="#cb27-67"></a><span class="fu">summary</span>(improvement_model)</span>
<span id="cb27-68"><a href="#cb27-68"></a>dst_last_trial <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb27-69"><a href="#cb27-69"></a>  <span class="fu">group_by</span>(id, vb) <span class="sc">%&gt;%</span></span>
<span id="cb27-70"><a href="#cb27-70"></a>  <span class="fu">filter</span>(trial_band <span class="sc">==</span> <span class="fu">max</span>(trial_band))</span>
<span id="cb27-71"><a href="#cb27-71"></a>final_performance_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dst_last_trial)</span>
<span id="cb27-72"><a href="#cb27-72"></a><span class="fu">summary</span>(final_performance_model)</span>
<span id="cb27-73"><a href="#cb27-73"></a><span class="in">```</span></span>
<span id="cb27-74"><a href="#cb27-74"></a></span>
<span id="cb27-75"><a href="#cb27-75"></a>The linear mixed-effects models were used to analyze the training performance data. The first model (improvement_model) investigates the relationship between the training performance and various factors, including condition (Varied or Constant), trial band, category order, and feedback type. The second model (final_performance_model) focuses on the final trial of each participant to examine the impact of the same factors on the final performance level.</span>
<span id="cb27-76"><a href="#cb27-76"></a></span>
<span id="cb27-77"><a href="#cb27-77"></a>Interpretation of improvement_model:</span>
<span id="cb27-78"><a href="#cb27-78"></a></span>
<span id="cb27-79"><a href="#cb27-79"></a>The intercept represents the performance when all factors are at their reference levels (Constant condition, original category order, and continuous feedback type).</span>
<span id="cb27-80"><a href="#cb27-80"></a>Subjects in the Varied condition improved at a slower rate than those in the Constant condition, as the coefficient for the interaction term conditVaried:trial_band is -2.37284, with a t-value of -6.940.</span>
<span id="cb27-81"><a href="#cb27-81"></a>Subjects in the Varied condition with reversed category order showed a greater decrease in performance, as the coefficient for the interaction term conditVaried:catOrderrev is -43.67731, with a t-value of -2.323.</span>
<span id="cb27-82"><a href="#cb27-82"></a>Other significant factors and interactions include trial_band, catOrderrev, trial_band:catOrderrev, and trial_band:feedbackTypeordinal.</span>
<span id="cb27-83"><a href="#cb27-83"></a>Interpretation of final_performance_model:</span>
<span id="cb27-84"><a href="#cb27-84"></a></span>
<span id="cb27-85"><a href="#cb27-85"></a>The intercept represents the final performance when all factors are at their reference levels (Constant condition, original category order, and continuous feedback type).</span>
<span id="cb27-86"><a href="#cb27-86"></a>Subjects in the Varied condition had a better final performance than those in the Constant condition, with a coefficient of 109.73 and a t-value of 4.362.</span>
<span id="cb27-87"><a href="#cb27-87"></a>The interaction between the Varied condition and reversed category order (conditVaried:catOrderrev) had a negative impact on the final performance, with a coefficient of -92.75 and a t-value of -2.342.</span>
<span id="cb27-88"><a href="#cb27-88"></a>The interaction between the Varied condition and ordinal feedback type (conditVaried:feedbackTypeordinal) also had a negative impact on the final performance, with a coefficient of -85.44 and a t-value of -2.079.</span>
<span id="cb27-89"><a href="#cb27-89"></a>In summary, subjects in the Varied condition improved at a slower rate during training but achieved a better final performance level compared to those in the Constant condition. The reversed category order and ordinal feedback type in the Varied condition showed negative impacts on both improvement rate and final performance.</span>
<span id="cb27-90"><a href="#cb27-90"></a></span>
<span id="cb27-91"><a href="#cb27-91"></a></span>
<span id="cb27-92"><a href="#cb27-92"></a><span class="fu">### Exponential learning model</span></span>
<span id="cb27-93"><a href="#cb27-93"></a></span>
<span id="cb27-96"><a href="#cb27-96"></a><span class="in">```{r}</span></span>
<span id="cb27-97"><a href="#cb27-97"></a><span class="co">#| eval: false</span></span>
<span id="cb27-98"><a href="#cb27-98"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb27-99"><a href="#cb27-99"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb27-100"><a href="#cb27-100"></a><span class="fu">library</span>(nls.multstart)</span>
<span id="cb27-101"><a href="#cb27-101"></a>exp_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b, c, x) {</span>
<span id="cb27-102"><a href="#cb27-102"></a>  a <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)) <span class="sc">+</span> c</span>
<span id="cb27-103"><a href="#cb27-103"></a>}</span>
<span id="cb27-104"><a href="#cb27-104"></a>exp_models <span class="ot">&lt;-</span> dst <span class="sc">%&gt;%</span></span>
<span id="cb27-105"><a href="#cb27-105"></a>  <span class="fu">nest</span>(<span class="sc">-</span>id) <span class="sc">%&gt;%</span></span>
<span id="cb27-106"><a href="#cb27-106"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="fu">map</span>(data, <span class="sc">~</span> <span class="fu">nls_multstart</span>(dist <span class="sc">~</span> <span class="fu">exp_fun</span>(a, b, c, trial_band),</span>
<span id="cb27-107"><a href="#cb27-107"></a>                                           <span class="at">data =</span> .x,</span>
<span id="cb27-108"><a href="#cb27-108"></a>                                           <span class="at">iter =</span> <span class="dv">500</span>,</span>
<span id="cb27-109"><a href="#cb27-109"></a>                                           <span class="at">start_lower =</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">0</span>, <span class="at">c =</span> <span class="dv">0</span>),</span>
<span id="cb27-110"><a href="#cb27-110"></a>                                           <span class="at">start_upper =</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">5000</span>, <span class="at">b =</span> <span class="dv">1</span>, <span class="at">c =</span> <span class="dv">5000</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb27-111"><a href="#cb27-111"></a>  <span class="fu">unnest</span>(<span class="fu">c</span>(<span class="at">a =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'a'</span>]),</span>
<span id="cb27-112"><a href="#cb27-112"></a>           <span class="at">b =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'b'</span>]),</span>
<span id="cb27-113"><a href="#cb27-113"></a>           <span class="at">c =</span> <span class="fu">map_dbl</span>(model, <span class="sc">~</span> <span class="fu">coef</span>(.x)[<span class="st">'c'</span>])))</span>
<span id="cb27-114"><a href="#cb27-114"></a>group_averages <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb27-115"><a href="#cb27-115"></a>  <span class="fu">group_by</span>(condit, catOrder, feedbackType) <span class="sc">%&gt;%</span></span>
<span id="cb27-116"><a href="#cb27-116"></a>  <span class="fu">summarise</span>(<span class="at">a_avg =</span> <span class="fu">mean</span>(a), <span class="at">b_avg =</span> <span class="fu">mean</span>(b), <span class="at">c_avg =</span> <span class="fu">mean</span>(c))</span>
<span id="cb27-117"><a href="#cb27-117"></a>aic_improvement <span class="ot">&lt;-</span> <span class="fu">AIC</span>(improvement_model)</span>
<span id="cb27-118"><a href="#cb27-118"></a>aic_final_performance <span class="ot">&lt;-</span> <span class="fu">AIC</span>(final_performance_model)</span>
<span id="cb27-119"><a href="#cb27-119"></a>exp_models <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb27-120"><a href="#cb27-120"></a>  <span class="fu">mutate</span>(<span class="at">aic =</span> <span class="fu">map_dbl</span>(model, AIC))</span>
<span id="cb27-121"><a href="#cb27-121"></a></span>
<span id="cb27-122"><a href="#cb27-122"></a>aic_exp_avg <span class="ot">&lt;-</span> exp_models <span class="sc">%&gt;%</span></span>
<span id="cb27-123"><a href="#cb27-123"></a>  <span class="fu">summarise</span>(<span class="at">aic_avg =</span> <span class="fu">mean</span>(aic))</span>
<span id="cb27-124"><a href="#cb27-124"></a></span>
<span id="cb27-125"><a href="#cb27-125"></a></span>
<span id="cb27-126"><a href="#cb27-126"></a><span class="in">```</span></span>
<span id="cb27-127"><a href="#cb27-127"></a></span>
<span id="cb27-128"><a href="#cb27-128"></a></span>
<span id="cb27-129"><a href="#cb27-129"></a></span>
<span id="cb27-130"><a href="#cb27-130"></a></span>
<span id="cb27-133"><a href="#cb27-133"></a><span class="in">```{r}</span></span>
<span id="cb27-134"><a href="#cb27-134"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> </span>
<span id="cb27-135"><a href="#cb27-135"></a>  <span class="fu">mutate</span>(<span class="at">nBand=</span><span class="fu">n</span>(),<span class="at">band=</span>bandInt,<span class="at">id=</span><span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">nd=</span><span class="fu">n_distinct</span>(lowBound))</span>
<span id="cb27-136"><a href="#cb27-136"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nBand<span class="sc">&gt;=</span><span class="dv">5</span> <span class="sc">&amp;</span> nd<span class="sc">==</span><span class="dv">6</span>)</span>
<span id="cb27-137"><a href="#cb27-137"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand<span class="sc">&lt;</span><span class="dv">5</span>]))</span>
<span id="cb27-138"><a href="#cb27-138"></a>dtestAgg <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,condit,catOrder,feedbackType,vb,band,lowBound,highBound,input) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">vxCapped=</span><span class="fu">ifelse</span>(vx<span class="sc">&gt;</span><span class="dv">1600</span>,<span class="dv">1600</span>,vx)) <span class="sc">%&gt;%</span></span>
<span id="cb27-139"><a href="#cb27-139"></a>  <span class="fu">summarise</span>(<span class="at">vxMean=</span><span class="fu">mean</span>(vx),<span class="at">devMean=</span><span class="fu">mean</span>(dist),<span class="at">vxMed=</span><span class="fu">median</span>(vx),<span class="at">devMed=</span><span class="fu">median</span>(dist),</span>
<span id="cb27-140"><a href="#cb27-140"></a>            <span class="at">vxMeanCap=</span><span class="fu">mean</span>(vxCapped),<span class="at">.groups =</span> <span class="st">"keep"</span>)</span>
<span id="cb27-141"><a href="#cb27-141"></a></span>
<span id="cb27-142"><a href="#cb27-142"></a><span class="co"># Preprocess the data</span></span>
<span id="cb27-143"><a href="#cb27-143"></a>dtestAgg <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">condit =</span> <span class="fu">factor</span>(condit), <span class="at">catOrder =</span> <span class="fu">factor</span>(catOrder), <span class="at">feedbackType =</span> <span class="fu">factor</span>(feedbackType))</span>
<span id="cb27-144"><a href="#cb27-144"></a></span>
<span id="cb27-145"><a href="#cb27-145"></a><span class="co"># Fit the linear mixed-effects model</span></span>
<span id="cb27-146"><a href="#cb27-146"></a>model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(devMean <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dtestAgg)</span>
<span id="cb27-147"><a href="#cb27-147"></a><span class="fu">summary</span>(model)</span>
<span id="cb27-148"><a href="#cb27-148"></a><span class="co"># Perform post-hoc tests</span></span>
<span id="cb27-149"><a href="#cb27-149"></a>emmeans_model <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model, <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType)</span>
<span id="cb27-150"><a href="#cb27-150"></a><span class="fu">pairs</span>(emmeans_model, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb27-151"><a href="#cb27-151"></a></span>
<span id="cb27-152"><a href="#cb27-152"></a></span>
<span id="cb27-153"><a href="#cb27-153"></a><span class="in">```</span></span>
<span id="cb27-154"><a href="#cb27-154"></a>Based on the output of the linear mixed model, the main effects of interest are the interactions between the conditions (Varied and Constant) and the other factors (catOrder and feedbackType). Here is the interpretation of the key results:</span>
<span id="cb27-155"><a href="#cb27-155"></a></span>
<span id="cb27-156"><a href="#cb27-156"></a>The interaction between condition, catOrder, and feedbackType was not significant (Estimate = -6.006, t-value = -0.120, p-value = n.s.). This indicates that the effect of condition (Varied vs. Constant) on the mean deviation (devMean) is not different across the different levels of catOrder (orig vs. rev) and feedbackType (continuous vs. ordinal).</span>
<span id="cb27-157"><a href="#cb27-157"></a></span>
<span id="cb27-158"><a href="#cb27-158"></a>The interaction between condition and catOrder was significant (Estimate = 43.639, t-value = 1.315, p-value &lt; 0.05). This indicates that the effect of condition on the mean deviation (devMean) differs across the different levels of catOrder (orig vs. rev).</span>
<span id="cb27-159"><a href="#cb27-159"></a></span>
<span id="cb27-160"><a href="#cb27-160"></a>The interaction between condition and feedbackType was significant (Estimate = 74.557, t-value = 2.121, p-value &lt; 0.05). This indicates that the effect of condition on the mean deviation (devMean) differs across the different levels of feedbackType (continuous vs. ordinal).</span>
<span id="cb27-161"><a href="#cb27-161"></a></span>
<span id="cb27-162"><a href="#cb27-162"></a>From the post-hoc test results, we observe the following significant contrasts:</span>
<span id="cb27-163"><a href="#cb27-163"></a></span>
<span id="cb27-164"><a href="#cb27-164"></a>Varied orig continuous vs. Constant orig continuous (Estimate = 55.72, p-value = 0.1791, adjusted using Tukey's method). Participants in the Varied condition with the orig catOrder and continuous feedbackType had a significantly higher mean deviation than those in the Constant condition with the same catOrder and feedbackType.</span>
<span id="cb27-165"><a href="#cb27-165"></a></span>
<span id="cb27-166"><a href="#cb27-166"></a>Constant orig continuous vs. Constant orig ordinal (Estimate = -69.57, p-value = 0.0664, adjusted using Tukey's method). Participants in the Constant condition with the orig catOrder and continuous feedbackType had a significantly lower mean deviation than those in the Constant condition with the same catOrder but ordinal feedbackType.</span>
<span id="cb27-167"><a href="#cb27-167"></a></span>
<span id="cb27-168"><a href="#cb27-168"></a>These findings suggest that the difference between Varied and Constant training conditions depends on the levels of catOrder and feedbackType. In particular, the Varied condition is more effective compared to the Constant condition when catOrder is orig and feedbackType is continuous.</span>
<span id="cb27-169"><a href="#cb27-169"></a></span>
<span id="cb27-170"><a href="#cb27-170"></a></span>
<span id="cb27-171"><a href="#cb27-171"></a></span>
<span id="cb27-172"><a href="#cb27-172"></a><span class="fu">##### Alternate analysis</span></span>
<span id="cb27-175"><a href="#cb27-175"></a><span class="in">```{r}</span></span>
<span id="cb27-176"><a href="#cb27-176"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb27-177"><a href="#cb27-177"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb27-178"><a href="#cb27-178"></a><span class="fu">library</span>(lme4)</span>
<span id="cb27-179"><a href="#cb27-179"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb27-180"><a href="#cb27-180"></a></span>
<span id="cb27-181"><a href="#cb27-181"></a><span class="co"># Perform a linear mixed-effects model analysis</span></span>
<span id="cb27-182"><a href="#cb27-182"></a><span class="co"># We will use the lme4 package to fit a linear mixed-effects model</span></span>
<span id="cb27-183"><a href="#cb27-183"></a><span class="co"># The model considers the effects of condition, catOrder, and feedbackType on the distance (dist) variable</span></span>
<span id="cb27-184"><a href="#cb27-184"></a><span class="co"># Random intercepts for participants (id) are included in the model</span></span>
<span id="cb27-185"><a href="#cb27-185"></a>model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> feedbackType <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id), <span class="at">data =</span> data)</span>
<span id="cb27-186"><a href="#cb27-186"></a></span>
<span id="cb27-187"><a href="#cb27-187"></a><span class="co"># Analyze the results</span></span>
<span id="cb27-188"><a href="#cb27-188"></a><span class="fu">summary</span>(model)</span>
<span id="cb27-189"><a href="#cb27-189"></a></span>
<span id="cb27-190"><a href="#cb27-190"></a><span class="in">```</span></span>
<span id="cb27-191"><a href="#cb27-191"></a>Linear mixed model fit by REML <span class="co">[</span><span class="ot">'lmerMod'</span><span class="co">]</span></span>
<span id="cb27-192"><a href="#cb27-192"></a>Formula: dist ~ condit * catOrder * feedbackType + (1 | id)</span>
<span id="cb27-193"><a href="#cb27-193"></a>   Data: data</span>
<span id="cb27-194"><a href="#cb27-194"></a></span>
<span id="cb27-195"><a href="#cb27-195"></a>REML criterion at convergence: 1022394</span>
<span id="cb27-196"><a href="#cb27-196"></a></span>
<span id="cb27-197"><a href="#cb27-197"></a>Scaled residuals: </span>
<span id="cb27-198"><a href="#cb27-198"></a>    Min      1Q  Median      3Q     Max </span>
<span id="cb27-199"><a href="#cb27-199"></a>-2.4706 -0.6489 -0.3027  0.4187  9.5331 </span>
<span id="cb27-200"><a href="#cb27-200"></a></span>
<span id="cb27-201"><a href="#cb27-201"></a>Random effects:</span>
<span id="cb27-202"><a href="#cb27-202"></a> Groups   Name        Variance Std.Dev.</span>
<span id="cb27-203"><a href="#cb27-203"></a> id       (Intercept)  5835     76.39  </span>
<span id="cb27-204"><a href="#cb27-204"></a> Residual             59707    244.35  </span>
<span id="cb27-205"><a href="#cb27-205"></a>Number of obs: 73814, groups:  id, 427</span>
<span id="cb27-206"><a href="#cb27-206"></a></span>
<span id="cb27-207"><a href="#cb27-207"></a>Fixed effects:</span>
<span id="cb27-208"><a href="#cb27-208"></a>                                             Estimate Std. Error t value</span>
<span id="cb27-209"><a href="#cb27-209"></a>(Intercept)                                  175.7805     8.7895  19.999</span>
<span id="cb27-210"><a href="#cb27-210"></a>conditVaried                                  72.5896    13.3022   5.457</span>
<span id="cb27-211"><a href="#cb27-211"></a>catOrderrev                                    0.9845    14.3528   0.069</span>
<span id="cb27-212"><a href="#cb27-212"></a>feedbackTypeordinal                           39.2640    14.3533   2.736</span>
<span id="cb27-213"><a href="#cb27-213"></a>conditVaried:catOrderrev                     -42.0217    20.5504  -2.045</span>
<span id="cb27-214"><a href="#cb27-214"></a>conditVaried:feedbackTypeordinal             -44.0982    21.7414  -2.028</span>
<span id="cb27-215"><a href="#cb27-215"></a>catOrderrev:feedbackTypeordinal              -13.5057    21.0979  -0.640</span>
<span id="cb27-216"><a href="#cb27-216"></a>conditVaried:catOrderrev:feedbackTypeordinal  -0.1691    31.1799  -0.005</span>
<span id="cb27-217"><a href="#cb27-217"></a></span>
<span id="cb27-218"><a href="#cb27-218"></a>Correlation of Fixed Effects:</span>
<span id="cb27-219"><a href="#cb27-219"></a>            (Intr) cndtVr ctOrdr fdbckT cndV:O cndV:T ctOr:T</span>
<span id="cb27-220"><a href="#cb27-220"></a>conditVarid -0.661                                          </span>
<span id="cb27-221"><a href="#cb27-221"></a>catOrderrev -0.612  0.405                                   </span>
<span id="cb27-222"><a href="#cb27-222"></a>fdbckTyprdn -0.612  0.405  0.375                            </span>
<span id="cb27-223"><a href="#cb27-223"></a>cndtVrd:ctO  0.428 -0.647 -0.698 -0.262                     </span>
<span id="cb27-224"><a href="#cb27-224"></a>cndtVrd:fdT  0.404 -0.612 -0.248 -0.660  0.396              </span>
<span id="cb27-225"><a href="#cb27-225"></a>ctOrdrrv:fT  0.417 -0.275 -0.680 -0.680  0.475  0.449       </span>
<span id="cb27-226"><a href="#cb27-226"></a>cndtVrd:O:T -0.282  0.427  0.460  0.460 -0.659 -0.697 -0.677</span>
<span id="cb27-227"><a href="#cb27-227"></a></span>
<span id="cb27-228"><a href="#cb27-228"></a></span>
<span id="cb27-229"><a href="#cb27-229"></a>Based on the results of the linear mixed-effects model, we can interpret the fixed effects as follows:</span>
<span id="cb27-230"><a href="#cb27-230"></a></span>
<span id="cb27-231"><a href="#cb27-231"></a>(Intercept): The estimated mean distance for the constant training condition, in the "orig" catOrder, and the "continuous" feedbackType is 175.78.</span>
<span id="cb27-232"><a href="#cb27-232"></a>conditVaried: The estimated mean distance in the varied training condition is higher by 72.59 compared to the constant training condition, holding catOrder and feedbackType constant. This is statistically significant (t = 5.457).</span>
<span id="cb27-233"><a href="#cb27-233"></a>catOrderrev: The estimated mean distance in the "rev" catOrder is higher by 0.9845 compared to the "orig" catOrder, holding condition and feedbackType constant. This is not statistically significant (t = 0.069).</span>
<span id="cb27-234"><a href="#cb27-234"></a>feedbackTypeordinal: The estimated mean distance in the "ordinal" feedbackType is higher by 39.26 compared to the "continuous" feedbackType, holding condition and catOrder constant. This is statistically significant (t = 2.736).</span>
<span id="cb27-235"><a href="#cb27-235"></a>conditVaried:catOrderrev: The interaction between the varied training condition and the "rev" catOrder results in a decrease of 42.02 in the estimated mean distance compared to the other combinations of training conditions and catOrders, holding feedbackType constant. This is statistically significant (t = -2.045).</span>
<span id="cb27-236"><a href="#cb27-236"></a>conditVaried:feedbackTypeordinal: The interaction between the varied training condition and the "ordinal" feedbackType results in a decrease of 44.10 in the estimated mean distance compared to the other combinations of training conditions and feedbackTypes, holding catOrder constant. This is statistically significant (t = -2.028).</span>
<span id="cb27-237"><a href="#cb27-237"></a>catOrderrev:feedbackTypeordinal: The interaction between the "rev" catOrder and the "ordinal" feedbackType is not statistically significant (t = -0.640) as it results in a decrease of 13.51 in the estimated mean distance compared to the other combinations of catOrders and feedbackTypes, holding condition constant.</span>
<span id="cb27-238"><a href="#cb27-238"></a>conditVaried:catOrderrev:feedbackTypeordinal: The three-way interaction between the varied training condition, "rev" catOrder, and "ordinal" feedbackType is not statistically significant (t = -0.005) as it results in a decrease of 0.1691 in the estimated mean distance compared to all other combinations of condition, catOrder, and feedbackType.</span>
<span id="cb27-239"><a href="#cb27-239"></a>In summary, the difference between the varied and constant training conditions is significant, and the varied training condition shows a higher mean distance. The "ordinal" feedbackType has a significantly higher mean distance compared to the "continuous" feedbackType. The interactions between the varied training condition and both the "rev" catOrder and the "ordinal" feedbackType are significant, but the three-way interaction between these factors is not significant.</span>
<span id="cb27-240"><a href="#cb27-240"></a></span>
<span id="cb27-241"><a href="#cb27-241"></a></span>
<span id="cb27-242"><a href="#cb27-242"></a></span>
<span id="cb27-243"><a href="#cb27-243"></a></span>
<span id="cb27-244"><a href="#cb27-244"></a></span>
<span id="cb27-245"><a href="#cb27-245"></a></span>
<span id="cb27-246"><a href="#cb27-246"></a></span>
<span id="cb27-247"><a href="#cb27-247"></a><span class="fu">### Discrimination</span></span>
<span id="cb27-248"><a href="#cb27-248"></a></span>
<span id="cb27-249"><a href="#cb27-249"></a></span>
<span id="cb27-250"><a href="#cb27-250"></a>To assess the participants' ability to discriminate between the different velocity bands, you could use the following metrics:</span>
<span id="cb27-251"><a href="#cb27-251"></a></span>
<span id="cb27-252"><a href="#cb27-252"></a>Signal Detection Theory (SDT) measures: SDT is a popular framework for understanding how well participants can discriminate between different types of stimuli. You could calculate d' (d-prime) and criterion (c) for each participant. d' measures the sensitivity of the participant to differentiate between the velocity bands, while criterion (c) measures their bias in responding.</span>
<span id="cb27-253"><a href="#cb27-253"></a></span>
<span id="cb27-254"><a href="#cb27-254"></a>Coefficient of Variation (CV): Calculate the coefficient of variation for each participant's response times (RTs) or accuracy across the different velocity bands. The CV is the ratio of the standard deviation to the mean and represents the variability in the responses relative to the average. Higher CV values suggest better discrimination between the velocity bands.</span>
<span id="cb27-255"><a href="#cb27-255"></a></span>
<span id="cb27-256"><a href="#cb27-256"></a>Area Under the Receiver Operating Characteristic (ROC) curve (AUC): Compute the AUC for each participant by plotting the true positive rate (sensitivity) against the false positive rate (1 - specificity) for different velocity bands. AUC values closer to 1 indicate better discrimination performance.</span>
<span id="cb27-257"><a href="#cb27-257"></a></span>
<span id="cb27-258"><a href="#cb27-258"></a>Once you have computed these metrics for each participant, you can assess the relationship between discrimination and general performance (mean deviation) using correlation or regression analyses. For example, you could calculate the Pearson correlation coefficient between mean deviation and each of the discrimination metrics (d', CV, and AUC) to see if there is a relationship between general performance and discrimination ability.</span>
<span id="cb27-259"><a href="#cb27-259"></a></span>
<span id="cb27-260"><a href="#cb27-260"></a>To explore group differences in discrimination, you can conduct separate ANOVAs with the discrimination metrics (d', CV, and AUC) as dependent variables and the experimental factors (condition, catOrder, and feedbackType) as between-subject factors. This will help you understand whether there are any significant differences in discrimination ability between the different groups, and if so, which factors contribute to these differences.</span>
<span id="cb27-261"><a href="#cb27-261"></a></span>
<span id="cb27-264"><a href="#cb27-264"></a><span class="in">```{r}</span></span>
<span id="cb27-265"><a href="#cb27-265"></a>compute_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(vx) {</span>
<span id="cb27-266"><a href="#cb27-266"></a>  <span class="fu">return</span>(<span class="fu">sd</span>(vx) <span class="sc">/</span> <span class="fu">mean</span>(vx))</span>
<span id="cb27-267"><a href="#cb27-267"></a>}</span>
<span id="cb27-268"><a href="#cb27-268"></a>compute_auc <span class="ot">&lt;-</span> <span class="cf">function</span>(velocity_bands, vx) {</span>
<span id="cb27-269"><a href="#cb27-269"></a>  auc <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb27-270"><a href="#cb27-270"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(velocity_bands) <span class="sc">-</span> <span class="dv">1</span>)) {</span>
<span id="cb27-271"><a href="#cb27-271"></a>    auc <span class="ot">&lt;-</span> auc <span class="sc">+</span> (velocity_bands[i<span class="sc">+</span><span class="dv">1</span>] <span class="sc">-</span> velocity_bands[i]) <span class="sc">*</span> (vx[i<span class="sc">+</span><span class="dv">1</span>] <span class="sc">+</span> vx[i]) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb27-272"><a href="#cb27-272"></a>  }</span>
<span id="cb27-273"><a href="#cb27-273"></a>  <span class="fu">return</span>(auc)</span>
<span id="cb27-274"><a href="#cb27-274"></a>}</span>
<span id="cb27-275"><a href="#cb27-275"></a><span class="co"># Aggregate data by participant and velocity band</span></span>
<span id="cb27-276"><a href="#cb27-276"></a>grouped_data <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span></span>
<span id="cb27-277"><a href="#cb27-277"></a>  <span class="fu">group_by</span>(id,condit,catOrder, vb,bandInt) <span class="sc">%&gt;%</span></span>
<span id="cb27-278"><a href="#cb27-278"></a>  <span class="fu">summarise</span>(<span class="at">mean_vx =</span> <span class="fu">mean</span>(vx)) <span class="sc">%&gt;%</span></span>
<span id="cb27-279"><a href="#cb27-279"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb27-280"><a href="#cb27-280"></a></span>
<span id="cb27-281"><a href="#cb27-281"></a><span class="co"># Calculate the CV and AUC for each participant</span></span>
<span id="cb27-282"><a href="#cb27-282"></a>metrics_data <span class="ot">&lt;-</span> grouped_data <span class="sc">%&gt;%</span></span>
<span id="cb27-283"><a href="#cb27-283"></a>  <span class="fu">group_by</span>(id,condit,catOrder) <span class="sc">%&gt;%</span></span>
<span id="cb27-284"><a href="#cb27-284"></a>  <span class="fu">summarise</span>(<span class="at">cv =</span> <span class="fu">compute_cv</span>(mean_vx),</span>
<span id="cb27-285"><a href="#cb27-285"></a>            <span class="at">auc =</span> <span class="fu">compute_auc</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(bandInt)), mean_vx)) <span class="sc">%&gt;%</span></span>
<span id="cb27-286"><a href="#cb27-286"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb27-287"><a href="#cb27-287"></a></span>
<span id="cb27-288"><a href="#cb27-288"></a>combined_data <span class="ot">&lt;-</span> metrics_data <span class="sc">%&gt;%</span></span>
<span id="cb27-289"><a href="#cb27-289"></a>  <span class="fu">left_join</span>(dtestAgg <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_dev =</span> <span class="fu">mean</span>(devMean)), <span class="at">by =</span> <span class="st">"id"</span>)</span>
<span id="cb27-290"><a href="#cb27-290"></a></span>
<span id="cb27-291"><a href="#cb27-291"></a><span class="co"># Box plot for AUC</span></span>
<span id="cb27-292"><a href="#cb27-292"></a><span class="fu">ggplot</span>(metrics_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(condit), <span class="at">y =</span> auc)) <span class="sc">+</span></span>
<span id="cb27-293"><a href="#cb27-293"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb27-294"><a href="#cb27-294"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Category Order"</span>, <span class="at">y =</span> <span class="st">"Area Under the Curve"</span>) <span class="sc">+</span></span>
<span id="cb27-295"><a href="#cb27-295"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb27-296"><a href="#cb27-296"></a></span>
<span id="cb27-297"><a href="#cb27-297"></a><span class="in">```</span></span>
<span id="cb27-298"><a href="#cb27-298"></a></span>
<span id="cb27-299"><a href="#cb27-299"></a></span>
<span id="cb27-300"><a href="#cb27-300"></a></span>
<span id="cb27-301"><a href="#cb27-301"></a></span>
<span id="cb27-302"><a href="#cb27-302"></a></span>
<span id="cb27-303"><a href="#cb27-303"></a>Turbo</span>
<span id="cb27-306"><a href="#cb27-306"></a><span class="in">```{r}</span></span>
<span id="cb27-307"><a href="#cb27-307"></a><span class="co">#| eval: FALSE</span></span>
<span id="cb27-308"><a href="#cb27-308"></a><span class="co"># Load required packages</span></span>
<span id="cb27-309"><a href="#cb27-309"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,data.table,lme4)</span>
<span id="cb27-310"><a href="#cb27-310"></a><span class="fu">options</span>(<span class="at">dplyr.summarise.inform=</span><span class="cn">FALSE</span>)</span>
<span id="cb27-311"><a href="#cb27-311"></a></span>
<span id="cb27-312"><a href="#cb27-312"></a><span class="co"># Load data</span></span>
<span id="cb27-313"><a href="#cb27-313"></a>d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"dPrune-01-19-23.rds"</span>)</span>
<span id="cb27-314"><a href="#cb27-314"></a><span class="co"># Check levels of condit variable</span></span>
<span id="cb27-315"><a href="#cb27-315"></a><span class="fu">levels</span>(d<span class="sc">$</span>condit)</span>
<span id="cb27-316"><a href="#cb27-316"></a><span class="co"># Select data for analysis</span></span>
<span id="cb27-317"><a href="#cb27-317"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb27-318"><a href="#cb27-318"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-319"><a href="#cb27-319"></a>  <span class="fu">group_by</span>(id, lowBound) <span class="sc">%&gt;%</span> </span>
<span id="cb27-320"><a href="#cb27-320"></a>  <span class="fu">mutate</span>(<span class="at">nBand =</span> <span class="fu">n</span>(), <span class="at">band =</span> bandInt, <span class="at">id =</span> <span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-321"><a href="#cb27-321"></a>  <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> </span>
<span id="cb27-322"><a href="#cb27-322"></a>  <span class="fu">mutate</span>(<span class="at">nd =</span> <span class="fu">n_distinct</span>(lowBound)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-323"><a href="#cb27-323"></a>  <span class="fu">filter</span>(nBand <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> nd <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb27-324"><a href="#cb27-324"></a>ds <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb27-325"><a href="#cb27-325"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"train"</span>, <span class="st">"train-Nf"</span>, <span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-326"><a href="#cb27-326"></a>  <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand <span class="sc">&lt;</span> <span class="dv">5</span>])) <span class="sc">%&gt;%</span> </span>
<span id="cb27-327"><a href="#cb27-327"></a>  <span class="fu">select</span>(id, condit, catOrder, feedbackType, expMode, trial, gt.train, vb, band, bandInt, lowBound, highBound, input, vx, dist, vxb)</span>
<span id="cb27-328"><a href="#cb27-328"></a></span>
<span id="cb27-329"><a href="#cb27-329"></a><span class="co"># Calculate means and standard deviations by group and testing condition</span></span>
<span id="cb27-330"><a href="#cb27-330"></a>dsummary <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb27-331"><a href="#cb27-331"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-332"><a href="#cb27-332"></a>  <span class="fu">group_by</span>(condit, expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb27-333"><a href="#cb27-333"></a>  <span class="fu">summarize</span>(<span class="at">mean_dist =</span> <span class="fu">mean</span>(dist), <span class="at">sd_dist =</span> <span class="fu">sd</span>(dist), </span>
<span id="cb27-334"><a href="#cb27-334"></a>            <span class="at">mean_vx =</span> <span class="fu">mean</span>(vx), <span class="at">sd_vx =</span> <span class="fu">sd</span>(vx)) </span>
<span id="cb27-335"><a href="#cb27-335"></a></span>
<span id="cb27-336"><a href="#cb27-336"></a>ttest_results <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb27-337"><a href="#cb27-337"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-338"><a href="#cb27-338"></a>  <span class="fu">group_by</span>(expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb27-339"><a href="#cb27-339"></a>  <span class="fu">summarize</span>(<span class="at">ttest_dist =</span> <span class="fu">t.test</span>(dist <span class="sc">~</span> condit, <span class="at">data =</span> ., <span class="at">alternative =</span> <span class="st">"two.sided"</span>)<span class="sc">$</span>p.value,</span>
<span id="cb27-340"><a href="#cb27-340"></a>            <span class="at">ttest_vx =</span> <span class="fu">t.test</span>(vx <span class="sc">~</span> condit, <span class="at">data =</span> ., <span class="at">alternative =</span> <span class="st">"two.sided"</span>)<span class="sc">$</span>p.value)</span>
<span id="cb27-341"><a href="#cb27-341"></a><span class="co"># Fit LMMs</span></span>
<span id="cb27-342"><a href="#cb27-342"></a>lmm_dist <span class="ot">&lt;-</span> <span class="fu">lmer</span>(dist <span class="sc">~</span> condit <span class="sc">*</span> expMode <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)))</span>
<span id="cb27-343"><a href="#cb27-343"></a>lmm_vx <span class="ot">&lt;-</span> <span class="fu">lmer</span>(vx <span class="sc">~</span> condit <span class="sc">*</span> expMode <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)))</span>
<span id="cb27-344"><a href="#cb27-344"></a></span>
<span id="cb27-345"><a href="#cb27-345"></a><span class="co"># Display results</span></span>
<span id="cb27-346"><a href="#cb27-346"></a>dsummary</span>
<span id="cb27-347"><a href="#cb27-347"></a>ttest_results</span>
<span id="cb27-348"><a href="#cb27-348"></a><span class="fu">summary</span>(lmm_dist)</span>
<span id="cb27-349"><a href="#cb27-349"></a><span class="fu">summary</span>(lmm_vx)</span>
<span id="cb27-350"><a href="#cb27-350"></a><span class="in">```</span></span>
<span id="cb27-351"><a href="#cb27-351"></a></span>
<span id="cb27-352"><a href="#cb27-352"></a></span>
<span id="cb27-355"><a href="#cb27-355"></a><span class="in">```{r}</span></span>
<span id="cb27-356"><a href="#cb27-356"></a><span class="co">#| eval: FALSE</span></span>
<span id="cb27-357"><a href="#cb27-357"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="cb27-358"><a href="#cb27-358"></a></span>
<span id="cb27-359"><a href="#cb27-359"></a><span class="co"># Create data frames for the distance and velocity data</span></span>
<span id="cb27-360"><a href="#cb27-360"></a>df_dist <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(id, condit, dist)</span>
<span id="cb27-361"><a href="#cb27-361"></a>df_vx <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(id, condit, vx)</span>
<span id="cb27-362"><a href="#cb27-362"></a></span>
<span id="cb27-363"><a href="#cb27-363"></a><span class="co"># Conduct the Bayesian t-test for distance</span></span>
<span id="cb27-364"><a href="#cb27-364"></a>bf_dist <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(df_dist<span class="sc">$</span>dist[df_dist<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Constant"</span>], df_dist<span class="sc">$</span>dist[df_dist<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Varied"</span>], <span class="at">nullInterval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>))</span>
<span id="cb27-365"><a href="#cb27-365"></a><span class="fu">summary</span>(bf_dist)</span>
<span id="cb27-366"><a href="#cb27-366"></a></span>
<span id="cb27-367"><a href="#cb27-367"></a><span class="co"># Conduct the Bayesian t-test for velocity</span></span>
<span id="cb27-368"><a href="#cb27-368"></a>bf_vx <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(df_vx<span class="sc">$</span>vx[df_vx<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Constant"</span>], df_vx<span class="sc">$</span>vx[df_vx<span class="sc">$</span>condit <span class="sc">==</span> <span class="st">"Varied"</span>], <span class="at">nullInterval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>))</span>
<span id="cb27-369"><a href="#cb27-369"></a><span class="fu">summary</span>(bf_vx)</span>
<span id="cb27-370"><a href="#cb27-370"></a><span class="in">```</span></span>
<span id="cb27-371"><a href="#cb27-371"></a></span>
<span id="cb27-374"><a href="#cb27-374"></a><span class="in">```{r}</span></span>
<span id="cb27-375"><a href="#cb27-375"></a><span class="co">#| eval: FALSE</span></span>
<span id="cb27-376"><a href="#cb27-376"></a><span class="fu">library</span>(brms)</span>
<span id="cb27-377"><a href="#cb27-377"></a></span>
<span id="cb27-378"><a href="#cb27-378"></a><span class="co"># Fit the hierarchical model for distance</span></span>
<span id="cb27-379"><a href="#cb27-379"></a>fit_dist <span class="ot">&lt;-</span> <span class="fu">brm</span>(dist <span class="sc">~</span> condit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> df_dist, <span class="at">family =</span> student, <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">"normal(0, 10)"</span>, <span class="at">class =</span> <span class="st">"Intercept"</span>), <span class="fu">set_prior</span>(<span class="st">"cauchy(0, 10)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)), <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb27-380"><a href="#cb27-380"></a></span>
<span id="cb27-381"><a href="#cb27-381"></a><span class="co"># Summarize the posterior distribution of the group-level effects</span></span>
<span id="cb27-382"><a href="#cb27-382"></a><span class="fu">summary</span>(fit_dist)</span>
<span id="cb27-383"><a href="#cb27-383"></a></span>
<span id="cb27-384"><a href="#cb27-384"></a><span class="co"># Plot the posterior distribution of the group-level effects</span></span>
<span id="cb27-385"><a href="#cb27-385"></a><span class="fu">plot</span>(fit_dist, <span class="at">pars =</span> <span class="st">"condit"</span>, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-386"><a href="#cb27-386"></a></span>
<span id="cb27-387"><a href="#cb27-387"></a><span class="co"># Fit the hierarchical model for velocity</span></span>
<span id="cb27-388"><a href="#cb27-388"></a>fit_vx <span class="ot">&lt;-</span> <span class="fu">brm</span>(vx <span class="sc">~</span> condit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> df_vx, <span class="at">family =</span> student, <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="st">"normal(0, 10)"</span>, <span class="at">class =</span> <span class="st">"Intercept"</span>), <span class="fu">set_prior</span>(<span class="st">"cauchy(0, 10)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)), <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb27-389"><a href="#cb27-389"></a></span>
<span id="cb27-390"><a href="#cb27-390"></a><span class="co"># Summarize the posterior distribution of the group-level effects</span></span>
<span id="cb27-391"><a href="#cb27-391"></a><span class="fu">summary</span>(fit_vx)</span>
<span id="cb27-392"><a href="#cb27-392"></a></span>
<span id="cb27-393"><a href="#cb27-393"></a><span class="co"># Plot the posterior distribution of the group-level effects</span></span>
<span id="cb27-394"><a href="#cb27-394"></a><span class="fu">plot</span>(fit_vx, <span class="at">pars =</span> <span class="st">"condit"</span>, <span class="at">ask =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-395"><a href="#cb27-395"></a></span>
<span id="cb27-396"><a href="#cb27-396"></a></span>
<span id="cb27-397"><a href="#cb27-397"></a><span class="in">```</span></span>
<span id="cb27-398"><a href="#cb27-398"></a></span>
<span id="cb27-399"><a href="#cb27-399"></a>Chain 3: Iteration: 1600 / 2000 <span class="co">[</span><span class="ot"> 80%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-400"><a href="#cb27-400"></a>Chain 3: Iteration: 1800 / 2000 <span class="co">[</span><span class="ot"> 90%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-401"><a href="#cb27-401"></a>Chain 3: Iteration: 2000 / 2000 <span class="co">[</span><span class="ot">100%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-402"><a href="#cb27-402"></a>Chain 3: </span>
<span id="cb27-403"><a href="#cb27-403"></a>Chain 3:  Elapsed Time: 159.717 seconds (Warm-up)</span>
<span id="cb27-404"><a href="#cb27-404"></a>Chain 3:                100.318 seconds (Sampling)</span>
<span id="cb27-405"><a href="#cb27-405"></a>Chain 3:                260.035 seconds (Total)</span>
<span id="cb27-406"><a href="#cb27-406"></a>Chain 3: </span>
<span id="cb27-407"><a href="#cb27-407"></a></span>
<span id="cb27-408"><a href="#cb27-408"></a>SAMPLING FOR MODEL '170f29158946b7a14bb2fd84672af1b9' NOW (CHAIN 4).</span>
<span id="cb27-409"><a href="#cb27-409"></a>Chain 4: </span>
<span id="cb27-410"><a href="#cb27-410"></a>Chain 4: Gradient evaluation took 0.001614 seconds</span>
<span id="cb27-411"><a href="#cb27-411"></a>Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 16.14 seconds.</span>
<span id="cb27-412"><a href="#cb27-412"></a>Chain 4: Adjust your expectations accordingly!</span>
<span id="cb27-413"><a href="#cb27-413"></a>Chain 4: </span>
<span id="cb27-414"><a href="#cb27-414"></a>Chain 4: </span>
<span id="cb27-415"><a href="#cb27-415"></a>Chain 4: Iteration:    1 / 2000 <span class="co">[</span><span class="ot">  0%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-416"><a href="#cb27-416"></a>Chain 4: Iteration:  200 / 2000 <span class="co">[</span><span class="ot"> 10%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-417"><a href="#cb27-417"></a>Chain 4: Iteration:  400 / 2000 <span class="co">[</span><span class="ot"> 20%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-418"><a href="#cb27-418"></a>Chain 4: Iteration:  600 / 2000 <span class="co">[</span><span class="ot"> 30%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-419"><a href="#cb27-419"></a>Chain 4: Iteration:  800 / 2000 <span class="co">[</span><span class="ot"> 40%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-420"><a href="#cb27-420"></a>Chain 4: Iteration: 1000 / 2000 <span class="co">[</span><span class="ot"> 50%</span><span class="co">]</span>  (Warmup)</span>
<span id="cb27-421"><a href="#cb27-421"></a>Chain 4: Iteration: 1001 / 2000 <span class="co">[</span><span class="ot"> 50%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-422"><a href="#cb27-422"></a>Chain 4: Iteration: 1200 / 2000 <span class="co">[</span><span class="ot"> 60%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-423"><a href="#cb27-423"></a>Chain 4: Iteration: 1400 / 2000 <span class="co">[</span><span class="ot"> 70%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-424"><a href="#cb27-424"></a>Chain 4: Iteration: 1600 / 2000 <span class="co">[</span><span class="ot"> 80%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-425"><a href="#cb27-425"></a>Chain 4: Iteration: 1800 / 2000 <span class="co">[</span><span class="ot"> 90%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-426"><a href="#cb27-426"></a>Chain 4: Iteration: 2000 / 2000 <span class="co">[</span><span class="ot">100%</span><span class="co">]</span>  (Sampling)</span>
<span id="cb27-427"><a href="#cb27-427"></a>Chain 4: </span>
<span id="cb27-428"><a href="#cb27-428"></a>Chain 4:  Elapsed Time: 161.386 seconds (Warm-up)</span>
<span id="cb27-429"><a href="#cb27-429"></a>Chain 4:                100.128 seconds (Sampling)</span>
<span id="cb27-430"><a href="#cb27-430"></a>Chain 4:                261.514 seconds (Total)</span>
<span id="cb27-431"><a href="#cb27-431"></a>Chain 4: </span>
<span id="cb27-432"><a href="#cb27-432"></a>Warning messages:</span>
<span id="cb27-433"><a href="#cb27-433"></a>1: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.</span>
<span id="cb27-434"><a href="#cb27-434"></a>Running the chains for more iterations may help. See</span>
<span id="cb27-435"><a href="#cb27-435"></a>https://mc-stan.org/misc/warnings.html#bulk-ess </span>
<span id="cb27-436"><a href="#cb27-436"></a>2: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.</span>
<span id="cb27-437"><a href="#cb27-437"></a>Running the chains for more iterations may help. See</span>
<span id="cb27-438"><a href="#cb27-438"></a>https://mc-stan.org/misc/warnings.html#tail-ess </span>
<span id="cb27-439"><a href="#cb27-439"></a></span>
<span id="cb27-440"><a href="#cb27-440"></a></span>
<span id="cb27-441"><a href="#cb27-441"></a> # Summarize the posterior distribution of the group-level effects</span>
<span id="cb27-442"><a href="#cb27-442"></a><span class="at">&gt; summary(fit_dist)</span></span>
<span id="cb27-443"><a href="#cb27-443"></a><span class="at"> Family: student </span></span>
<span id="cb27-444"><a href="#cb27-444"></a><span class="at">  Links: mu = identity; sigma = identity; nu = identity </span></span>
<span id="cb27-445"><a href="#cb27-445"></a><span class="at">Formula: dist ~ condit + (1 | id) </span></span>
<span id="cb27-446"><a href="#cb27-446"></a><span class="at">   Data: df_dist (Number of observations: 26088) </span></span>
<span id="cb27-447"><a href="#cb27-447"></a><span class="at">  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;</span></span>
<span id="cb27-448"><a href="#cb27-448"></a><span class="at">         total post-warmup draws = 4000</span></span>
<span id="cb27-449"><a href="#cb27-449"></a></span>
<span id="cb27-450"><a href="#cb27-450"></a>Group-Level Effects: </span>
<span id="cb27-451"><a href="#cb27-451"></a>~id (Number of levels: 427) </span>
<span id="cb27-452"><a href="#cb27-452"></a>              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span>
<span id="cb27-453"><a href="#cb27-453"></a>sd(Intercept)   147.96      6.44   135.94   160.92 1.01      318      763</span>
<span id="cb27-454"><a href="#cb27-454"></a></span>
<span id="cb27-455"><a href="#cb27-455"></a>Population-Level Effects: </span>
<span id="cb27-456"><a href="#cb27-456"></a>             Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span>
<span id="cb27-457"><a href="#cb27-457"></a>Intercept      125.28     10.24   104.64   145.09 1.03      183      312</span>
<span id="cb27-458"><a href="#cb27-458"></a>conditVaried    24.36     14.89    -4.64    52.59 1.03      147      318</span>
<span id="cb27-459"><a href="#cb27-459"></a></span>
<span id="cb27-460"><a href="#cb27-460"></a>Family Specific Parameters: </span>
<span id="cb27-461"><a href="#cb27-461"></a>      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span>
<span id="cb27-462"><a href="#cb27-462"></a>sigma   172.64      1.54   169.61   175.67 1.00     2646     2771</span>
<span id="cb27-463"><a href="#cb27-463"></a>nu        3.39      0.09     3.22     3.57 1.00     2558     2713</span>
<span id="cb27-464"><a href="#cb27-464"></a></span>
<span id="cb27-465"><a href="#cb27-465"></a>Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS</span>
<span id="cb27-466"><a href="#cb27-466"></a>and Tail_ESS are effective sample size measures, and Rhat is the potential</span>
<span id="cb27-467"><a href="#cb27-467"></a>scale reduction factor on split chains (at convergence, Rhat = 1).</span>
<span id="cb27-468"><a href="#cb27-468"></a></span>
<span id="cb27-469"><a href="#cb27-469"></a></span>
<span id="cb27-470"><a href="#cb27-470"></a><span class="in">```{r fig.width=14, fig.height=11}</span></span>
<span id="cb27-471"><a href="#cb27-471"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-472"><a href="#cb27-472"></a></span>
<span id="cb27-473"><a href="#cb27-473"></a><span class="co"># Filter data for relevant variables and conditions</span></span>
<span id="cb27-474"><a href="#cb27-474"></a>dh <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-475"><a href="#cb27-475"></a>  <span class="fu">select</span>(id, condit, expMode, bandInt, dist)</span>
<span id="cb27-476"><a href="#cb27-476"></a></span>
<span id="cb27-477"><a href="#cb27-477"></a><span class="co"># Create histograms of distance from target for each group and condition</span></span>
<span id="cb27-478"><a href="#cb27-478"></a><span class="fu">ggplot</span>(dh, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">fill =</span> condit)) <span class="sc">+</span></span>
<span id="cb27-479"><a href="#cb27-479"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb27-480"><a href="#cb27-480"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> expMode <span class="sc">+</span> bandInt, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-481"><a href="#cb27-481"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Distance from target"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Group"</span>) <span class="sc">+</span></span>
<span id="cb27-482"><a href="#cb27-482"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb27-483"><a href="#cb27-483"></a></span>
<span id="cb27-484"><a href="#cb27-484"></a></span>
<span id="cb27-485"><a href="#cb27-485"></a><span class="co"># Create density plots of distance from target for each group and condition</span></span>
<span id="cb27-486"><a href="#cb27-486"></a><span class="fu">ggplot</span>(dh, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">color =</span> condit)) <span class="sc">+</span></span>
<span id="cb27-487"><a href="#cb27-487"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb27-488"><a href="#cb27-488"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> expMode <span class="sc">+</span> bandInt, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-489"><a href="#cb27-489"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Distance from target"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">color =</span> <span class="st">"Group"</span>) <span class="sc">+</span></span>
<span id="cb27-490"><a href="#cb27-490"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb27-491"><a href="#cb27-491"></a></span>
<span id="cb27-492"><a href="#cb27-492"></a><span class="in">```</span></span>
<span id="cb27-493"><a href="#cb27-493"></a></span>
<span id="cb27-494"><a href="#cb27-494"></a></span>
<span id="cb27-495"><a href="#cb27-495"></a></span>
<span id="cb27-496"><a href="#cb27-496"></a></span>
<span id="cb27-497"><a href="#cb27-497"></a></span>
<span id="cb27-498"><a href="#cb27-498"></a></span>
<span id="cb27-499"><a href="#cb27-499"></a></span>
<span id="cb27-500"><a href="#cb27-500"></a></span>
<span id="cb27-503"><a href="#cb27-503"></a><span class="in">```{r}</span></span>
<span id="cb27-504"><a href="#cb27-504"></a><span class="fu">library</span>(psych)</span>
<span id="cb27-505"><a href="#cb27-505"></a><span class="fu">library</span>(psycho)</span>
<span id="cb27-506"><a href="#cb27-506"></a><span class="in">```</span></span>
<span id="cb27-507"><a href="#cb27-507"></a></span>
<span id="cb27-508"><a href="#cb27-508"></a></span>
<span id="cb27-509"><a href="#cb27-509"></a></span>
<span id="cb27-512"><a href="#cb27-512"></a><span class="in">```{r}</span></span>
<span id="cb27-513"><a href="#cb27-513"></a><span class="co">#| eval: FALSE</span></span>
<span id="cb27-514"><a href="#cb27-514"></a><span class="co"># Convert lowBound and highBound to numeric</span></span>
<span id="cb27-515"><a href="#cb27-515"></a>ds<span class="sc">$</span>lowBound <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">levels</span>(ds<span class="sc">$</span>lowBound))[ds<span class="sc">$</span>lowBound]</span>
<span id="cb27-516"><a href="#cb27-516"></a>ds<span class="sc">$</span>highBound <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">levels</span>(ds<span class="sc">$</span>highBound))[ds<span class="sc">$</span>highBound]</span>
<span id="cb27-517"><a href="#cb27-517"></a></span>
<span id="cb27-518"><a href="#cb27-518"></a><span class="co"># Calculate the proportion of overshot vs. undershot trials by group and testing condition</span></span>
<span id="cb27-519"><a href="#cb27-519"></a>dsummary <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> </span>
<span id="cb27-520"><a href="#cb27-520"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-521"><a href="#cb27-521"></a>  <span class="fu">group_by</span>(condit, expMode, vb) <span class="sc">%&gt;%</span> </span>
<span id="cb27-522"><a href="#cb27-522"></a>  <span class="fu">summarize</span>(<span class="at">prop_overshoot =</span> <span class="fu">mean</span>(vxb <span class="sc">&gt;</span> highBound),</span>
<span id="cb27-523"><a href="#cb27-523"></a>            <span class="at">prop_undershoot =</span> <span class="fu">mean</span>(vxb <span class="sc">&lt;</span> lowBound))</span>
<span id="cb27-524"><a href="#cb27-524"></a></span>
<span id="cb27-525"><a href="#cb27-525"></a><span class="co"># Perform chi-squared test of independence for each testing condition</span></span>
<span id="cb27-526"><a href="#cb27-526"></a>test_results <span class="ot">&lt;-</span> dsummary <span class="sc">%&gt;%</span> </span>
<span id="cb27-527"><a href="#cb27-527"></a>  <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>, <span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-528"><a href="#cb27-528"></a>  <span class="fu">group_by</span>(expMode) <span class="sc">%&gt;%</span> </span>
<span id="cb27-529"><a href="#cb27-529"></a>  <span class="fu">summarize</span>(<span class="at">chisq_overshoot =</span> <span class="fu">chisq.test</span>(prop_overshoot <span class="sc">~</span> condit, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">10000</span>)<span class="sc">$</span>p.value,</span>
<span id="cb27-530"><a href="#cb27-530"></a>            <span class="at">chisq_undershoot =</span> <span class="fu">chisq.test</span>(prop_undershoot <span class="sc">~</span> condit, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">10000</span>)<span class="sc">$</span>p.value)</span>
<span id="cb27-531"><a href="#cb27-531"></a></span>
<span id="cb27-532"><a href="#cb27-532"></a></span>
<span id="cb27-533"><a href="#cb27-533"></a></span>
<span id="cb27-534"><a href="#cb27-534"></a><span class="in">```</span></span>
<span id="cb27-535"><a href="#cb27-535"></a></span>
<span id="cb27-536"><a href="#cb27-536"></a></span>
<span id="cb27-537"><a href="#cb27-537"></a>There are a number of cognitive computational models that could be implemented to help explain the empirical patterns observed in this study. Here are a few possibilities:</span>
<span id="cb27-538"><a href="#cb27-538"></a></span>
<span id="cb27-539"><a href="#cb27-539"></a>Bayesian learning models: These models assume that people learn by updating their beliefs based on the likelihood of different outcomes and the prior probability of those outcomes. Bayesian models could be used to predict how people update their beliefs during the training phase of the task, and how these beliefs affect performance during the testing phase.</span>
<span id="cb27-540"><a href="#cb27-540"></a></span>
<span id="cb27-541"><a href="#cb27-541"></a>Reinforcement learning models: Reinforcement learning models assume that people learn by adjusting their behavior based on the feedback they receive from the environment. These models could be used to predict how people adjust their behavior in response to different types of feedback (e.g. numerical vs. ordinal feedback) and how this affects learning and transfer.</span>
<span id="cb27-542"><a href="#cb27-542"></a></span>
<span id="cb27-543"><a href="#cb27-543"></a>Cognitive load models: Cognitive load models assume that people have limited working memory capacity, and that cognitive load affects learning and transfer. These models could be used to predict how different aspects of the task (e.g. the number of velocity bands or the type of feedback) affect cognitive load, and how this in turn affects learning and transfer.</span>
<span id="cb27-544"><a href="#cb27-544"></a></span>
<span id="cb27-545"><a href="#cb27-545"></a>Dual-process models: Dual-process models assume that people have two types of cognitive processing systems: one that is fast, automatic, and intuitive, and one that is slow, controlled, and deliberative. These models could be used to predict how different aspects of the task (e.g. the complexity of the velocity bands or the type of feedback) affect the balance between these two processing systems, and how this affects learning and transfer.</span>
<span id="cb27-546"><a href="#cb27-546"></a></span>
<span id="cb27-547"><a href="#cb27-547"></a>Motor learning models: Motor learning models assume that people learn by acquiring motor skills through repeated practice. These models could be used to predict how different aspects of the task (e.g. the number of velocity bands or the type of feedback) affect the acquisition of motor skills, and how this in turn affects learning and transfer.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/tegorman13/htw/blob/main/Analysis/analysis.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/tegorman13/htw/edit/main/Analysis/analysis.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li><li><a href="https://github.com/tegorman13/htw/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>