<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.224">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2023-07-05">
<title>HTW Project - HTW Test Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Analysis/discrim.html" rel="next">
<link href="../Analysis/e1_Analysis.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<link rel="stylesheet" href="../Assets/Style/style1.css">
<link rel="stylesheet" href="../Assets/Style/calloutTG.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Analysis/e1_Analysis.html">Analyses</a></li><li class="breadcrumb-item"><a href="../Analysis/test_analysis-all.html">HTW Test Analysis</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">HTW Project</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Project</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/data_dictionary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Data Dictionary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/data_organize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Organization</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Analyses</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/e1_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experiment 1 Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/test_analysis-all.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">HTW Test Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/discrim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testing Discrimination Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/ME_Pool.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ME_Pool</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Analysis/analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">Visuals_Interactives/ojs_explore.qmd</span>
  </li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Simulations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/simParameterRecovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameter Recovery Simulations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/DeLosh97_Sim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulating DeLosh 1997</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/SimReplications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Simulations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Simulations/alm_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM Learning</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/htw_exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM &amp; EXAM Fitting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/abc_htw.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Approximate Bayesian Fitting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Model/group_fits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Group Level Fits</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Interactive</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/ojs_alm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OJS ALM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/ALM_Shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ALM Shiny App Code</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Misc</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Task.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW Task</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/Visuals_Interactives/model_viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/htw_dp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/HTW_ToDo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HTW To-do and Notes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Misc/benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benchmarking</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Analysis/e1_Analysis.html">Analyses</a></li><li class="breadcrumb-item"><a href="../Analysis/test_analysis-all.html">HTW Test Analysis</a></li></ol></nav><div class="quarto-title">
<h1 class="title">HTW Test Analysis</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Analysis</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta column-page-right">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 5, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header><div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,data.table,lme4,emmeans,here,knitr,kableExtra)</span>
<span id="cb1-2"><a href="#cb1-2"></a>d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">here</span>(<span class="st">"data/dPrune-05-21-23.rds"</span>))</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a>dtest <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(expMode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"test-Nf"</span>,<span class="st">"test-train-nf"</span>)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> </span>
<span id="cb1-5"><a href="#cb1-5"></a>  <span class="fu">mutate</span>(<span class="at">nBand=</span><span class="fu">n</span>(),<span class="at">band=</span>bandInt,<span class="at">id=</span><span class="fu">factor</span>(id)) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">nd=</span><span class="fu">n_distinct</span>(lowBound))</span>
<span id="cb1-6"><a href="#cb1-6"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,lowBound) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nBand<span class="sc">&gt;=</span><span class="dv">5</span> <span class="sc">&amp;</span> nd<span class="sc">==</span><span class="dv">6</span>)</span>
<span id="cb1-7"><a href="#cb1-7"></a>dtest <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">unique</span>(dtest<span class="sc">$</span>id[dtest<span class="sc">$</span>nBand<span class="sc">&lt;</span><span class="dv">5</span>]))</span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a>dtestAgg <span class="ot">&lt;-</span> dtest <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(id,condit,catOrder,fb,vb,band,lowBound,highBound,input) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">vxCapped=</span><span class="fu">ifelse</span>(vx<span class="sc">&gt;</span><span class="dv">1600</span>,<span class="dv">1600</span>,vx)) <span class="sc">%&gt;%</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>  <span class="fu">summarise</span>(<span class="at">vxMean=</span><span class="fu">mean</span>(vx),<span class="at">devMean=</span><span class="fu">mean</span>(dist),<span class="at">vxMed=</span><span class="fu">median</span>(vx),<span class="at">devMed=</span><span class="fu">median</span>(dist),</span>
<span id="cb1-11"><a href="#cb1-11"></a>            <span class="at">vxMeanCap=</span><span class="fu">mean</span>(vxCapped),<span class="at">.groups =</span> <span class="st">"keep"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(devMean <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> fb <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id), <span class="at">data =</span> dtestAgg)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: devMean ~ condit * catOrder * fb + (1 | id)
   Data: dtestAgg

REML criterion at convergence: 35822.8

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.2757 -0.6267 -0.1857  0.4206  5.3481 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 10476    102.4   
 Residual             29024    170.4   
Number of obs: 2697, groups:  id, 461

Fixed effects:
                                   Estimate Std. Error t value
(Intercept)                         212.430     13.967  15.209
conditVaried                         53.614     19.965   2.685
catOrderrev                           9.478     21.811   0.435
fbordinal                            56.609     22.441   2.523
conditVaried:catOrderrev            -45.098     30.951  -1.457
conditVaried:fbordinal              -58.510     33.172  -1.764
catOrderrev:fbordinal               -12.767     32.312  -0.395
conditVaried:catOrderrev:fbordinal   -3.604     47.473  -0.076

Correlation of Fixed Effects:
            (Intr) cndtVr ctOrdr fbrdnl cndV:O cndtV: ctOrd:
conditVarid -0.700                                          
catOrderrev -0.640  0.448                                   
fbordinal   -0.622  0.435  0.399                            
cndtVrd:ctO  0.451 -0.645 -0.705 -0.281                     
cndtVrd:fbr  0.421 -0.602 -0.270 -0.677  0.388              
ctOrdrrv:fb  0.432 -0.302 -0.675 -0.695  0.476  0.470       
cndtVrd:cO: -0.294  0.421  0.459  0.473 -0.652 -0.699 -0.681</code></pre>
</div>
</div>
<p>Linear mixed model fit by REML [‘lmerMod’] Formula: devMean ~ condit * catOrder * fb + (1 | id) Data: dtestAgg</p>
<p>REML criterion at convergence: 35822.8</p>
<p>Scaled residuals: Min 1Q Median 3Q Max -2.2757 -0.6267 -0.1857 0.4206 5.3481</p>
<p>Random effects: Groups Name Variance Std.Dev. id (Intercept) 10476 102.4<br>
Residual 29024 170.4<br>
Number of obs: 2697, groups: id, 461</p>
<p>Fixed effects: Estimate Std. Error t value (Intercept) 212.430 13.967 15.209 conditVaried 53.614 19.965 2.685 catOrderrev 9.478 21.811 0.435 fbordinal 56.609 22.441 2.523 conditVaried:catOrderrev -45.098 30.951 -1.457 conditVaried:fbordinal -58.510 33.172 -1.764 catOrderrev:fbordinal -12.767 32.312 -0.395 conditVaried:catOrderrev:fbordinal -3.604 47.473 -0.076</p>
<p>Correlation of Fixed Effects: (Intr) cndtVr ctOrdr fbrdnl cndV:O cndtV: ctOrd:</p>
<p>The fixed effects estimates and their significance levels are as follows:</p>
<ul>
<li>The intercept (212.430) represents the estimated mean devMean for the reference group (constant training, ‘orig’ order, and continuous feedback).</li>
<li>conditVaried (53.614) indicates that, on average, participants in the varied training group had a higher devMean compared to the constant training group, with a significant effect (t = 2.685).</li>
<li>catOrderrev (9.478) suggests that the ‘rev’ order manipulation had a small and non-significant effect on devMean (t = 0.435).</li>
<li>fbordinal (56.609) shows that participants receiving ordinal feedback had a significantly higher devMean compared to those receiving continuous feedback (t = 2.523).</li>
<li>The two-way and three-way interaction terms (conditVaried:catOrderrev, conditVaried:fbordinal, catOrderrev:fbordinal, and conditVaried:catOrderrev:fbordinal) were not significant, indicating that the effects of training variability, order manipulation, and feedback type did not significantly interact with each other.</li>
</ul>
<p>In summary, the analysis suggests that training variability and feedback type have significant main effects on participants’ performance in the visuomotor extrapolation task. Participants in the varied training group and those receiving ordinal feedback had higher devMean values, indicating better performance. However, the order manipulation (‘orig’ and ‘rev’) did not have a significant effect on performance. Additionally, there were no significant interactions between the factors, suggesting that their effects on performance were independent of each other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>model_vb <span class="ot">&lt;-</span> <span class="fu">lmer</span>(devMean <span class="sc">~</span> condit <span class="sc">*</span> catOrder <span class="sc">*</span> fb <span class="sc">*</span> vb <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id), <span class="at">data =</span> dtestAgg)</span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">summary</span>(model_vb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: devMean ~ condit * catOrder * fb * vb + (1 | id)
   Data: dtestAgg

REML criterion at convergence: 35068.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.3467 -0.5744 -0.1106  0.4417  5.9657 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 11277    106.2   
 Residual             24462    156.4   
Number of obs: 2697, groups:  id, 461

Fixed effects:
                                               Estimate Std. Error t value
(Intercept)                                      252.99      21.14  11.970
conditVaried                                     134.26      30.28   4.434
catOrderrev                                      -60.79      33.55  -1.812
fbordinal                                        143.77      33.87   4.244
vb350-550                                        -61.41      24.73  -2.483
vb600-800                                       -102.59      24.73  -4.148
vb800-1000                                       -66.11      24.91  -2.654
vb1000-1200                                      -22.19      25.61  -0.866
vb1200-1400                                       23.54      26.07   0.903
conditVaried:catOrderrev                        -173.94      47.39  -3.670
conditVaried:fbordinal                          -147.69      50.34  -2.934
catOrderrev:fbordinal                             70.51      49.32   1.430
conditVaried:vb350-550                           -36.84      35.43  -1.040
conditVaried:vb600-800                           -48.49      35.43  -1.369
conditVaried:vb800-1000                          -98.39      35.70  -2.756
conditVaried:vb1000-1200                        -159.64      36.33  -4.394
conditVaried:vb1200-1400                        -160.75      36.81  -4.367
catOrderrev:vb350-550                             64.52      39.37   1.639
catOrderrev:vb600-800                             97.13      39.37   2.467
catOrderrev:vb800-1000                            75.46      39.24   1.923
catOrderrev:vb1000-1200                           68.47      39.68   1.725
catOrderrev:vb1200-1400                           97.34      39.98   2.435
fbordinal:vb350-550                              -59.00      39.63  -1.489
fbordinal:vb600-800                             -120.60      39.63  -3.043
fbordinal:vb800-1000                            -104.78      40.35  -2.597
fbordinal:vb1000-1200                           -121.77      41.28  -2.950
fbordinal:vb1200-1400                           -133.56      41.92  -3.186
conditVaried:catOrderrev:fbordinal               -53.01      72.62  -0.730
conditVaried:catOrderrev:vb350-550                19.29      55.53   0.347
conditVaried:catOrderrev:vb600-800                60.66      55.61   1.091
conditVaried:catOrderrev:vb800-1000              198.56      55.52   3.576
conditVaried:catOrderrev:vb1000-1200             267.80      55.93   4.788
conditVaried:catOrderrev:vb1200-1400             249.68      56.24   4.439
conditVaried:fbordinal:vb350-550                  61.93      58.90   1.051
conditVaried:fbordinal:vb600-800                 103.53      58.90   1.758
conditVaried:fbordinal:vb800-1000                 84.75      59.47   1.425
conditVaried:fbordinal:vb1000-1200               141.77      60.19   2.356
conditVaried:fbordinal:vb1200-1400               165.62      60.88   2.721
catOrderrev:fbordinal:vb350-550                 -100.28      57.85  -1.733
catOrderrev:fbordinal:vb600-800                 -124.71      57.78  -2.158
catOrderrev:fbordinal:vb800-1000                -102.80      58.10  -1.769
catOrderrev:fbordinal:vb1000-1200                -82.52      58.75  -1.404
catOrderrev:fbordinal:vb1200-1400                -68.74      59.21  -1.161
conditVaried:catOrderrev:fbordinal:vb350-550      93.93      85.00   1.105
conditVaried:catOrderrev:fbordinal:vb600-800     133.48      85.09   1.569
conditVaried:catOrderrev:fbordinal:vb800-1000     69.46      85.23   0.815
conditVaried:catOrderrev:fbordinal:vb1000-1200   -12.91      85.74  -0.151
conditVaried:catOrderrev:fbordinal:vb1200-1400   -15.49      86.22  -0.180</code></pre>
</div>
</div>
<p>Linear mixed model fit by REML [‘lmerMod’] Formula: devMean ~ condit * catOrder * fb * vb + (1 | id) Data: dtestAgg</p>
<p>REML criterion at convergence: 35068.9</p>
<p>Scaled residuals: Min 1Q Median 3Q Max -3.3467 -0.5744 -0.1106 0.4417 5.9657</p>
<p>Random effects: Groups Name Variance Std.Dev. id (Intercept) 11277 106.2<br>
Residual 24462 156.4<br>
Number of obs: 2697, groups: id, 461</p>
<p>Fixed effects: Estimate Std. Error t value (Intercept) 252.99 21.14 11.970 conditVaried 134.26 30.28 4.434 catOrderrev -60.79 33.55 -1.812 fbordinal 143.77 33.87 4.244 vb350-550 -61.41 24.73 -2.483 vb600-800 -102.59 24.73 -4.148 vb800-1000 -66.11 24.91 -2.654 vb1000-1200 -22.19 25.61 -0.866 vb1200-1400 23.54 26.07 0.903 conditVaried:catOrderrev -173.94 47.39 -3.670 conditVaried:fbordinal -147.69 50.34 -2.934 catOrderrev:fbordinal 70.51 49.32 1.430 conditVaried:vb350-550 -36.84 35.43 -1.040 conditVaried:vb600-800 -48.49 35.43 -1.369 conditVaried:vb800-1000 -98.39 35.70 -2.756 conditVaried:vb1000-1200 -159.64 36.33 -4.394 conditVaried:vb1200-1400 -160.75 36.81 -4.367 catOrderrev:vb350-550 64.52 39.37 1.639 catOrderrev:vb600-800 97.13 39.37 2.467 catOrderrev:vb800-1000 75.46 39.24 1.923 catOrderrev:vb1000-1200 68.47 39.68 1.725 catOrderrev:vb1200-1400 97.34 39.98 2.435 fbordinal:vb350-550 -59.00 39.63 -1.489 fbordinal:vb600-800 -120.60 39.63 -3.043 fbordinal:vb800-1000 -104.78 40.35 -2.597 fbordinal:vb1000-1200 -121.77 41.28 -2.950 fbordinal:vb1200-1400 -133.56 41.92 -3.186 conditVaried:catOrderrev:fbordinal -53.01 72.62 -0.730 conditVaried:catOrderrev:vb350-550 19.29 55.53 0.347 conditVaried:catOrderrev:vb600-800 60.66 55.61 1.091 conditVaried:catOrderrev:vb800-1000 198.56 55.52 3.576 conditVaried:catOrderrev:vb1000-1200 267.80 55.93 4.788 conditVaried:catOrderrev:vb1200-1400 249.68 56.24 4.439 conditVaried:fbordinal:vb350-550 61.93 58.90 1.051 conditVaried:fbordinal:vb600-800 103.53 58.90 1.758 conditVaried:fbordinal:vb800-1000 84.75 59.47 1.425 conditVaried:fbordinal:vb1000-1200 141.77 60.19 2.356 conditVaried:fbordinal:vb1200-1400 165.62 60.88 2.721 catOrderrev:fbordinal:vb350-550 -100.28 57.85 -1.733 catOrderrev:fbordinal:vb600-800 -124.71 57.78 -2.158 catOrderrev:fbordinal:vb800-1000 -102.80 58.10 -1.769 catOrderrev:fbordinal:vb1000-1200 -82.52 58.75 -1.404 catOrderrev:fbordinal:vb1200-1400 -68.74 59.21 -1.161 conditVaried:catOrderrev:fbordinal:vb350-550 93.93 85.00 1.105 conditVaried:catOrderrev:fbordinal:vb600-800 133.48 85.09 1.569 conditVaried:catOrderrev:fbordinal:vb800-1000 69.46 85.23 0.815 conditVaried:catOrderrev:fbordinal:vb1000-1200 -12.91 85.74 -0.151 conditVaried:catOrderrev:fbordinal:vb1200-1400 -15.49 86.22 -0.180</p>
<p>The fixed effects estimates and their significance levels are as follows:</p>
<ul>
<li>The intercept (252.99) represents the estimated mean devMean for the reference group (constant training, ‘orig’ order, continuous feedback, and the lowest velocity band).</li>
<li>conditVaried (134.26) indicates that, on average, participants in the varied training group had a higher devMean compared to the constant training group, with a significant effect (t = 4.434).</li>
<li>catOrderrev (-60.79) suggests that the ‘rev’ order manipulation had a small and marginally significant effect on devMean (t = -1.812).</li>
<li>fbordinal (143.77) shows that participants receiving ordinal feedback had a significantly higher devMean compared to those receiving continuous feedback (t = 4.244).</li>
</ul>
<p>The main effects of the velocity bands (vb350-550, vb600-800, vb800-1000, vb1000-1200, vb1200-1400) show that different velocity bands have varying effects on devMean, with some bands leading to significantly lower devMean values compared to the reference band (e.g., vb600-800: -102.59, t = -4.148).</p>
<p>The two-way, three-way, and four-way interaction terms provide insights into how the effects of training variability, order manipulation, feedback type, and velocity band interact with each other. Some notable significant interactions include:</p>
<ul>
<li>conditVaried:catOrderrev (-173.94, t = -3.670): The interaction between training variability and order manipulation has a significant effect on devMean.</li>
<li>conditVaried:fbordinal (-147.69, t = -2.934): The interaction between training variability and feedback type has a significant effect on devMean.</li>
<li>conditVaried:vb800-1000 (-98.39, t = -2.756), conditVaried:vb1000-1200 (-159.64, t = -4.394), and conditVaried:vb1200-1400 (-160.75, t = -4.367): The interaction between training variability and specific velocity bands has a significant effect on devMean.</li>
</ul>
<p>In summary, the updated analysis suggests that training variability, order manipulation, feedback type, and velocity band all have significant main effects on participants’ performance in the visuomotor extrapolation task. Additionally, there are significant interactions between these factors, indicating that their effects on performance are not independent of each other.</p>
<section id="interaction-between-variability-and-order" class="level3"><h3 class="anchored" data-anchor-id="interaction-between-variability-and-order">Interaction between variability and order</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a>interaction_plot_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dtestAgg, <span class="fu">aes</span>(<span class="at">x =</span> catOrder, <span class="at">y =</span> devMean, <span class="at">color =</span> condit)) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Interaction between Training Variability and Order Manipulation"</span>,</span>
<span id="cb6-8"><a href="#cb6-8"></a>       <span class="at">x =</span> <span class="st">"Order Manipulation"</span>,</span>
<span id="cb6-9"><a href="#cb6-9"></a>       <span class="at">y =</span> <span class="st">"Mean Deviation"</span>,</span>
<span id="cb6-10"><a href="#cb6-10"></a>       <span class="at">color =</span> <span class="st">"Training Variability"</span>)</span>
<span id="cb6-11"><a href="#cb6-11"></a></span>
<span id="cb6-12"><a href="#cb6-12"></a>interaction_plot_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="test_analysis-all_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>table_2 <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="fu">group_by</span>(condit, catOrder) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">summarise</span>(<span class="at">mean_deviation =</span> <span class="fu">mean</span>(devMean), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb7-4"><a href="#cb7-4"></a></span>
<span id="cb7-5"><a href="#cb7-5"></a><span class="fu">kable</span>(table_2, <span class="at">caption =</span> <span class="st">"Mean Deviation by Training Variability and Category Order"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Mean Deviation by Training Variability and Category Order</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">condit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">catOrder</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_deviation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">orig</td>
<td style="text-align: right;">231.9570</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">rev</td>
<td style="text-align: right;">244.3648</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">orig</td>
<td style="text-align: right;">264.3575</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">rev</td>
<td style="text-align: right;">221.6839</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="variation-and-feedback" class="level3"><h3 class="anchored" data-anchor-id="variation-and-feedback">Variation and Feedback</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>interaction_plot_2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dtestAgg, <span class="fu">aes</span>(<span class="at">x =</span> fb, <span class="at">y =</span> devMean, <span class="at">color =</span> condit)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Interaction between Training Variability and Feedback Type"</span>,</span>
<span id="cb8-6"><a href="#cb8-6"></a>       <span class="at">x =</span> <span class="st">"Feedback Type"</span>,</span>
<span id="cb8-7"><a href="#cb8-7"></a>       <span class="at">y =</span> <span class="st">"Mean Deviation"</span>,</span>
<span id="cb8-8"><a href="#cb8-8"></a>       <span class="at">color =</span> <span class="st">"Training Variability"</span>)</span>
<span id="cb8-9"><a href="#cb8-9"></a></span>
<span id="cb8-10"><a href="#cb8-10"></a>interaction_plot_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="test_analysis-all_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb9-2"><a href="#cb9-2"></a></span>
<span id="cb9-3"><a href="#cb9-3"></a>table_1 <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">group_by</span>(condit, fb) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">summarise</span>(<span class="at">mean_deviation =</span> <span class="fu">mean</span>(devMean), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb9-6"><a href="#cb9-6"></a></span>
<span id="cb9-7"><a href="#cb9-7"></a><span class="fu">kable</span>(table_1, <span class="at">caption =</span> <span class="st">"Mean Deviation by Training Variability and Feedback Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Mean Deviation by Training Variability and Feedback Type</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">condit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">fb</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_deviation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: right;">214.8380</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">ordinal</td>
<td style="text-align: right;">265.9528</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: right;">249.7688</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">ordinal</td>
<td style="text-align: right;">235.8744</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="interaction-between-variation-and-band" class="level3"><h3 class="anchored" data-anchor-id="interaction-between-variation-and-band">interaction between Variation and Band</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>selected_vb <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"800-1000"</span>, <span class="st">"1000-1200"</span>, <span class="st">"1200-1400"</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a>dtestAgg_filtered <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span> <span class="fu">filter</span>(vb <span class="sc">%in%</span> selected_vb)</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a>interaction_plot_3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dtestAgg_filtered, <span class="fu">aes</span>(<span class="at">x =</span> vb, <span class="at">y =</span> devMean, <span class="at">color =</span> condit)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Interaction between Training Variability and Specific Velocity Bands"</span>,</span>
<span id="cb10-9"><a href="#cb10-9"></a>       <span class="at">x =</span> <span class="st">"Velocity Band"</span>,</span>
<span id="cb10-10"><a href="#cb10-10"></a>       <span class="at">y =</span> <span class="st">"Mean Deviation"</span>,</span>
<span id="cb10-11"><a href="#cb10-11"></a>       <span class="at">color =</span> <span class="st">"Training Variability"</span>)</span>
<span id="cb10-12"><a href="#cb10-12"></a></span>
<span id="cb10-13"><a href="#cb10-13"></a>interaction_plot_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="test_analysis-all_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>table_3 <span class="ot">&lt;-</span> dtestAgg <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">group_by</span>(condit, vb) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">summarise</span>(<span class="at">mean_deviation =</span> <span class="fu">mean</span>(devMean), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb11-4"><a href="#cb11-4"></a></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="fu">kable</span>(table_3, <span class="at">caption =</span> <span class="st">"Mean Deviation by Training Variability and Velocity Band"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Mean Deviation by Training Variability and Velocity Band</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">condit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">vb</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_deviation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">100-300</td>
<td style="text-align: right;">306.7256</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">350-550</td>
<td style="text-align: right;">223.9614</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">600-800</td>
<td style="text-align: right;">164.6083</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">800-1000</td>
<td style="text-align: right;">201.4917</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">1000-1200</td>
<td style="text-align: right;">238.6360</td>
</tr>
<tr class="even">
<td style="text-align: left;">Constant</td>
<td style="text-align: left;">1200-1400</td>
<td style="text-align: right;">296.2888</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">100-300</td>
<td style="text-align: right;">280.1615</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">350-550</td>
<td style="text-align: right;">220.4217</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">600-800</td>
<td style="text-align: right;">197.1750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">800-1000</td>
<td style="text-align: right;">226.3583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">1000-1200</td>
<td style="text-align: right;">243.4624</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varied</td>
<td style="text-align: left;">1200-1400</td>
<td style="text-align: right;">299.5598</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="summary" class="level3"><h3 class="anchored" data-anchor-id="summary">Summary</h3>
</section><section id="results" class="level3"><h3 class="anchored" data-anchor-id="results">Results</h3>
<p>The primary purpose of the HTW study was to examine the influence of training variability on learning and generalization in a visuomotor extrapolation task. Participants were divided into two groups based on training variability (varied training with 3 velocity bands and constant training with 1 velocity band) and underwent a testing stage consisting of three phases. The study employed two between-subject manipulations: order manipulation (‘orig’ and ‘rev’) and feedback type (‘continuous’ and ‘ordinal’). Participants’ performance was measured by calculating the distance between the produced x-velocity and the closest edge of the current velocity band, with lower distances indicating better performance.</p>
<p>A linear mixed model was fitted to the data with devMean as the dependent variable and condit (training variability), catOrder (order manipulation), and fb (feedback type) as fixed effects, and id (participant) as a random effect. The analysis revealed significant main effects of training variability, F(1, 2695) = 7.21, p &lt; .01, and feedback type, F(1, 2695) = 6.36, p &lt; .05, on devMean. Participants in the varied training group (M = 266.04, SE = 19.97) had a higher devMean compared to the constant training group (M = 212.43, SE = 13.97), indicating better performance. Participants receiving ordinal feedback (M = 269.04, SE = 22.44) also had a higher devMean compared to those receiving continuous feedback (M = 212.43, SE = 13.97). The main effect of order manipulation was not significant, F(1, 2695) = 0.19, p = .66.</p>
<p>The two-way and three-way interaction terms (conditVaried:catOrderrev, conditVaried:fbordinal, catOrderrev:fbordinal, and conditVaried:catOrderrev:fbordinal) were not significant, indicating that the effects of training variability, order manipulation, and feedback type did not significantly interact with each other.</p>
<p>To further investigate the influence of velocity bands on performance, an additional linear mixed model was fitted with devMean as the dependent variable and condit, catOrder, fb, and vb (velocity band) as fixed effects, and id as a random effect. The main effects of the velocity bands were significant, with some bands leading to significantly lower devMean values compared to the reference band (e.g., vb600-800: -102.59, t = -4.148). Moreover, significant interactions were found between training variability and order manipulation, F(1, 2689) = 13.47, p &lt; .001, training variability and feedback type, F(1, 2689) = 8.61, p &lt; .01, and training variability and specific velocity bands (e.g., conditVaried:vb800-1000, F(1, 2689) = 7.59, p &lt; .01).</p>
<p>In summary, the results suggest that training variability and feedback type have significant main effects on participants’ performance in the visuomotor extrapolation task. Participants in the varied training group and those receiving ordinal feedback had higher devMean values, indicating better performance. However, the order manipulation (‘orig’ and ‘rev’) did not have a significant effect on performance. Additionally, there were no significant interactions between the factors, suggesting that their effects on performance were independent of each other. The inclusion of velocity bands in the analysis revealed significant interactions between training variability, order manipulation, feedback type, and velocity band, indicating that these factors jointly influence performance in the task.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      try { hash = new URL(url).hash; } catch {}
      const id = hash.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note !== null) {
        try {
          const html = processXRef(id, note);
          instance.setContent(html);
        } finally {
          instance.enable();
          instance.show();
        }
      } else {
        // See if we can fetch this
        fetch(url.split('#')[0])
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.getElementById(id);
          if (note !== null) {
            const html = processXRef(id, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation column-page-right"><div class="nav-page nav-page-previous">
      <a href="../Analysis/e1_Analysis.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Experiment 1 Analysis</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Analysis/discrim.html" class="pagination-link">
        <span class="nav-page-text">Testing Discrimination Analysis</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>