---
title: "HTW"
short-title: "Variability and Extrapolation"
date: 10-11-2023
author:
- name: Thomas Gorman
  affiliation: Indiana University
  url: www.tegorman13.github.io
  email: tegorman@iu.edu
  orcid: 0000-0001-5366-5442
- name: Rob Goldstone
  affiliation: Indiana University
  url: www.pc.cogs.indiana.edu 
  email: rgoldsto@indiana.edu
  orcid: 0000-0001-8357-8358
abstract: |
  In project 1, we applied model-based techniques to quantify and control for the similarity between training and testing experience, which in turn enabled us to account for the difference between varied and constant training via an extended version of a similarity based generalization model. In project 2, we will go a step further, implementing a full process model capable of both 1) producing novel responses and 2) modeling behavior in both the learning and testing stages of the experiment. Project 2 also places a greater emphasis on extrapolation performance following training - as varied training has often been purported to be particularly beneficial in such situations. 
keywords:
  - Learning Generalization
  - Function Learning
  - Visuomotor learning
  - Training Variability
code-repo: "Access the code, data, and analysis at <https://github.com/tegorman13/htw>"
bibliography: ../Assets/Bib/Dissertation.bib
link-citations: true
---

<link href="manuscript_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="manuscript_files/libs/tabwid-1.1.3/tabwid.js"></script>


# Introduction

In project 1, I applied model-based techniques to quantify and control for the similarity between training and testing experience, which in turn enabled us to account for the difference between varied and constant training via an extended version of a similarity based generalization model. In project 2, we will go a step further, implementing a full process model capable of both 1) producing novel responses and 2) modeling behavior in both the learning and testing stages of the experiment. Project 2 also places a greater emphasis on extrapolation performance following training. Although varied training has often been purported to be particularly beneficial for generalization or transfer, few experiments have compared varied and constant training in contexts with unambiguous extrapolation testing.

## Function Learning and Extrapolation

The study of human function learning investigates how people learn relationships between continuous input and output values. Function learning is studied both in tasks where individuals are exposed to a sequence of input/output pairs ([DeLosh et al., 1997](#ref-deloshExtrapolationSineQua1997); [McDaniel et al., 2013](#ref-mcdanielEffectsSpacedMassed2013)), or situations where observers are presented with a an incomplete scatterplot or line graph and make predictions about regions of the plot that don't contain data ([Ciccione & Dehaene, 2021](#ref-ciccioneCanHumansPerform2021a); [Courrieu, 2012](#ref-courrieuQuickApproximationBivariate2012); [Said & Fischer, 2021](#ref-saidExtrapolationAccuracyUnderestimates2021); [Schulz et al., 2020](#ref-schulzCommunicatingCompositionalPatterns2020)).

Carroll ([1963](#ref-carrollFunctionalLearningLearning1963)) conducted the earliest work on function learning. Input stimuli and output responses were both lines of varying length. The correct output response was related to the length of the input line by a linear, quadratic, or random function. Participants in the linear and quadratic performed above chance levels during extrapolation testing, with those in the linear condition performing the best overall. Carroll argued that these results were best explained by a ruled based model wherein learners form an abstract representation of the underlying function. Subsequent work by Brehmer ([1974](#ref-brehmerHypothesesRelationsScaled1974)),testing a wider array of functional forms, provided further evidence for superior extrapolation in tasks with linear functions. Brehmer argued that individuals start out with an assumption of a linear function, but given sufficient error will progressively test alternative hypothesis with polynomials of greater degree. Koh & Meyer ([1991](#ref-kohFunctionLearningInduction1991)) employed a visuomotor function learning task, wherein participants were trained on examples from an unknown function relating the length of an input line to the duration of a response (time between keystrokes). In this domain, participants performed best when the relation between line length and response duration was determined by a power, as opposed to linear function. Koh & Meyer developed the log-polynomial adaptive-regression model to account for their results.

The first significant challenge to the rule-based accounts of function learning was put forth by DeLosh et al. ([1997](#ref-deloshExtrapolationSineQua1997)) . In their task, participants learned to associate stimulus magnitudes with response magnitudes that were related via either linear, exponential, or quadratic function. Participants approached ceiling performance by the end of training in each function condition, and were able to correctly respond in interpolation testing trials. All three conditions demonstrated some capacity for extrapolation, however participants in the linear condition tended to underestimate the true function, while exponential and quadratic participants reliably overestimated the true function on extrapolation trials. Extrapolation and interpolation performance are depicted in <a href="#fig-delosh-extrap" class="quarto-xref">Figure 1</a>.

The authors evaluated both of the rule-based models introduced in earlier research (with some modifications enabling trial-by-trial learning). The polynomial hypothesis testing model ([Brehmer, 1974](#ref-brehmerHypothesesRelationsScaled1974); [Carroll, 1963](#ref-carrollFunctionalLearningLearning1963)) tended to mimic the true function closely in extrapolation, and thus offered a poor account of the human data. The log-polynomial adaptive regression model ([Koh & Meyer, 1991](#ref-kohFunctionLearningInduction1991)) was able to mimic some of the systematic deviations produced by human subjects, but also predicted overestimation in cases where underestimation occurred.

The authors also introduced two new function-learning models. The Associative Learning Model (ALM) and the extrapolation-association model (EXAM). ALM is a two layer connectionist model adapted from the ALCOVE model in the category learning literature ([Kruschke, 1992](#ref-kruschkeALCOVEExemplarbasedConnectionist1992)). ALM belongs to the general class of radial-basis function neural networks, and can be considered a similarity-based model in the sense that the nodes in the input layer of the network are activated as a function of distance. The EXAM model retains the same similarity based activation and associative learning mechanisms as ALM, while being augmented with a linear rule response mechanism. When presented with novel stimuli, EXAM will retrieve the most similar input-output examples encountered during training, and from those examples compute a local slope. ALM was able to provide a good account of participant training and interpolation data in all three function conditions, however it was unable to extrapolate. EXAM, on the other hand, was able to reproduce both the extrapolation underestimation, as well as the quadratic and exponential overestimation patterns exhibited by the human participants. Subsequent research identified some limitations in EXAM's ability to account for cases where human participants learn and extrapolate sinusoidal function Bott & Heit ([2004](#ref-bottNonmonotonicExtrapolationFunction2004)) or to scenarios where different functions apply to different regions of the input space Kalish et al. ([2004](#ref-kalishPopulationLinearExperts2004)), though EXAM has been shown to provide a good account of human learning and extrapolation in tasks with bi-linear, V shaped input spaces Mcdaniel et al. ([2009](#ref-mcdanielPredictingTransferPerformance2009)).

![](manuscript.markdown_strict_files/figure-markdown_strict/fig-delosh-extrap-1.jpeg)

# Methods

## Participants

Data was collected from 647 participants (after exclusions). The results shown below consider data from subjects in our initial experiment, which consisted of 196 participants (106 constant, 90 varied). The follow-up experiments entailed minor manipulations: 1) reversing the velocity bands that were trained on vs. novel during testing; 2) providing ordinal rather than numerical feedback during training (e.g. correct, too low, too high). The data from these subsequent experiments are largely consistently with our initial results shown below.

## Task

We developed a novel visuomotor extrapolation task, termed the Hit The Wall task, wherein participants learned to launch a projectile such that it hit a rectangle at the far end of the screen with an appropriate amount of force. Although the projectile had both x and y velocity components, only the x-dimension was relevant for the task.  <a href="https://pcl.sitehost.iu.edu/tg/HTW/HTW_Index.html?sonaid=" target="_blank">Link to task demo</a>

## Procedure

The HTW task involved launching projectiles to hit a target displayed on the computer screen. Participants completed a total of 90 trials during the training stage. In the varied training condition, participants encountered three velocity bands (800-1000, 1000-1200, and 1200-1400). In contrast, participants in the constant training condition encountered only one velocity band (800-1000).

During the training stage, participants in both conditions also completed "no feedback" trials, where they received no information about their performance. These trials were randomly interleaved with the regular training trials.

Following the training stage, participants proceeded to the testing stage, which consisted of three phases. In the first phase, participants completed "no-feedback" testing from three novel extrapolation bands (100-300, 350-550, and 600-800), with each band consisting of 15 trials.

In the second phase of testing, participants completed "no-feedback" testing from the three velocity bands used during the training stage (800-1000, 1000-1200, and 1200-1400). In the constant training condition, two of these bands were novel, while in the varied training condition, all three bands were encountered during training.

The third and final phase of testing involved "feedback" testing for each of the three extrapolation bands (100-300, 350-550, and 600-800), with each band consisting of 10 trials. Participants received feedback on their performance during this phase.

Throughout the experiment, participants' performance was measured by calculating the distance between the produced x-velocity of the projectiles and the closest edge of the current velocity band. Lower distances indicated better performance.

After completing the experiment, participants were debriefed and provided with an opportunity to ask questions about the study.

``` dot
digraph {
  graph [layout = dot, rankdir = LR]

  // define the global styles of the nodes
  node [shape = rectangle, style = filled]

  data1 [label = " Varied Training \n800-1000\n1000-1200\n1200-1400", fillcolor = "#FF0000"]
  data2 [label = " Constant Training \n800-1000", fillcolor = "#00A08A"]
  Test3 [label = "    Final Test \n  Novel With Feedback  \n100-300\n350-550\n600-800", fillcolor = "#ECCBAE"]

  // edge definitions with the node IDs
  data1 -> Test1
  data2 -> Test1

  subgraph cluster {
    label = "Test Phase \n(Counterbalanced Order)"
    Test1 [label = "Test  \nNovel Bands \n100-300\n350-550\n600-800", fillcolor = "#ECCBAE"]
    Test2 [label = "  Test \n  Varied Training Bands  \n800-1000\n1000-1200\n1200-1400", fillcolor = "#ECCBAE"]
    Test1 -> Test2
  }

  Test2 -> Test3
}
```

<svg width="576" height="240" viewbox="0.00 0.00 643.85 174.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 170)">
<polygon fill="white" stroke="transparent" points="-4,4 -4,-170 639.85,-170 639.85,4 -4,4"></polygon>
<g id="clust1" class="cluster">
<title>cluster</title>
<polygon fill="none" stroke="black" points="152.49,-8 152.49,-158 455,-158 455,-8 152.49,-8"></polygon>
<text text-anchor="middle" x="303.74" y="-141.4" font-family="Times,serif" font-size="14.00">Test Phase </text>
<text text-anchor="middle" x="303.74" y="-124.6" font-family="Times,serif" font-size="14.00">(Counterbalanced Order)</text>
</g>
<!-- data1 -->
<g id="node1" class="node">
<title>data1</title>
<polygon fill="#ff0000" stroke="black" points="118.54,-137.7 5.95,-137.7 5.95,-62.3 118.54,-62.3 118.54,-137.7"></polygon>
<text text-anchor="middle" x="62.24" y="-121" font-family="Times,serif" font-size="14.00"> Varied Training </text>
<text text-anchor="middle" x="62.24" y="-104.2" font-family="Times,serif" font-size="14.00">800-1000</text>
<text text-anchor="middle" x="62.24" y="-87.4" font-family="Times,serif" font-size="14.00">1000-1200</text>
<text text-anchor="middle" x="62.24" y="-70.6" font-family="Times,serif" font-size="14.00">1200-1400</text>
</g>
<!-- Test1 -->
<g id="node4" class="node">
<title>Test1</title>
<polygon fill="#eccbae" stroke="black" points="252.81,-108 160.38,-108 160.38,-16 252.81,-16 252.81,-108"></polygon>
<text text-anchor="middle" x="206.59" y="-91.4" font-family="Times,serif" font-size="14.00">Test &nbsp;</text>
<text text-anchor="middle" x="206.59" y="-74.6" font-family="Times,serif" font-size="14.00">Novel Bands </text>
<text text-anchor="middle" x="206.59" y="-57.8" font-family="Times,serif" font-size="14.00">100-300</text>
<text text-anchor="middle" x="206.59" y="-41" font-family="Times,serif" font-size="14.00">350-550</text>
<text text-anchor="middle" x="206.59" y="-24.2" font-family="Times,serif" font-size="14.00">600-800</text>
</g>
<!-- data1&#45;&gt;Test1 -->
<g id="edge1" class="edge">
<title>data1-&gt;Test1</title>
<path fill="none" stroke="black" d="M118.69,-85.2C129.1,-82.42 139.98,-79.51 150.39,-76.74"></path>
<polygon fill="black" stroke="black" points="151.43,-80.08 160.19,-74.12 149.62,-73.32 151.43,-80.08"></polygon>
</g>
<!-- data2 -->
<g id="node2" class="node">
<title>data2</title>
<polygon fill="#00a08a" stroke="black" points="124.73,-44.6 -0.24,-44.6 -0.24,-3.4 124.73,-3.4 124.73,-44.6"></polygon>
<text text-anchor="middle" x="62.24" y="-28.2" font-family="Times,serif" font-size="14.00"> Constant Training </text>
<text text-anchor="middle" x="62.24" y="-11.4" font-family="Times,serif" font-size="14.00">800-1000</text>
</g>
<!-- data2&#45;&gt;Test1 -->
<g id="edge2" class="edge">
<title>data2-&gt;Test1</title>
<path fill="none" stroke="black" d="M124.85,-40.45C133.39,-42.72 142.11,-45.05 150.51,-47.3"></path>
<polygon fill="black" stroke="black" points="149.64,-50.68 160.2,-49.88 151.44,-43.92 149.64,-50.68"></polygon>
</g>
<!-- Test3 -->
<g id="node3" class="node">
<title>Test3</title>
<polygon fill="#eccbae" stroke="black" points="635.77,-108 483.07,-108 483.07,-16 635.77,-16 635.77,-108"></polygon>
<text text-anchor="middle" x="559.42" y="-91.4" font-family="Times,serif" font-size="14.00"> &nbsp;&nbsp;&nbsp;Final Test </text>
<text text-anchor="middle" x="559.42" y="-74.6" font-family="Times,serif" font-size="14.00"> &nbsp;Novel With Feedback &nbsp;</text>
<text text-anchor="middle" x="559.42" y="-57.8" font-family="Times,serif" font-size="14.00">100-300</text>
<text text-anchor="middle" x="559.42" y="-41" font-family="Times,serif" font-size="14.00">350-550</text>
<text text-anchor="middle" x="559.42" y="-24.2" font-family="Times,serif" font-size="14.00">600-800</text>
</g>
<!-- Test2 -->
<g id="node5" class="node">
<title>Test2</title>
<polygon fill="#eccbae" stroke="black" points="447.15,-108 288.55,-108 288.55,-16 447.15,-16 447.15,-108"></polygon>
<text text-anchor="middle" x="367.85" y="-91.4" font-family="Times,serif" font-size="14.00"> &nbsp;Test </text>
<text text-anchor="middle" x="367.85" y="-74.6" font-family="Times,serif" font-size="14.00"> &nbsp;Varied Training Bands &nbsp;</text>
<text text-anchor="middle" x="367.85" y="-57.8" font-family="Times,serif" font-size="14.00">800-1000</text>
<text text-anchor="middle" x="367.85" y="-41" font-family="Times,serif" font-size="14.00">1000-1200</text>
<text text-anchor="middle" x="367.85" y="-24.2" font-family="Times,serif" font-size="14.00">1200-1400</text>
</g>
<!-- Test1&#45;&gt;Test2 -->
<g id="edge3" class="edge">
<title>Test1-&gt;Test2</title>
<path fill="none" stroke="black" d="M252.8,-62C260.95,-62 269.7,-62 278.59,-62"></path>
<polygon fill="black" stroke="black" points="278.67,-65.5 288.67,-62 278.67,-58.5 278.67,-65.5"></polygon>
</g>
<!-- Test2&#45;&gt;Test3 -->
<g id="edge4" class="edge">
<title>Test2-&gt;Test3</title>
<path fill="none" stroke="black" d="M447.05,-62C455.55,-62 464.24,-62 472.83,-62"></path>
<polygon fill="black" stroke="black" points="472.84,-65.5 482.84,-62 472.84,-58.5 472.84,-65.5"></polygon>
</g>
</g>
</svg>

## Analyses Strategy

All data processing and statistical analyses were performed in R version 4.31 Team ([2020](#ref-rcoreteamLanguageEnvironmentStatistical2020)). To assess differences between groups, we used Bayesian Mixed Effects Regression. Model fitting was performed with the brms package in R Bürkner ([2017](#ref-burknerBrmsPackageBayesian2017)), and descriptive stats and tables were extracted with the BayestestR package ([**makowskiBayestestRDescribingEffects2019a?**](#ref-makowskiBayestestRDescribingEffects2019a)). Mixed effects regression enables us to take advantage of partial pooling, simultaneously estimating parameters at the individual and group level. Our use of Bayesian, rather than frequentist methods allows us to directly quantify the uncertainty in our parameter estimates, as well as circumventing convergence issues common to the frequentist analogues of our mixed models. For each model, we report the median values of the posterior distribution, and 95% credible intervals.

Each model was set to run with 4 chains, 5000 iterations per chain, with the first 2500 of which were discarded as warmup chains. Rhat values were generally within an acceptable range, with values \<=1.02 (see appendix for diagnostic plots). We used uninformative priors for the fixed effects of the model (condition and velocity band), and weakly informative Student T distributions for for the random effects.

We compared varied and constant performance across two measures, deviation and discrimination. Deviation was quantified as the absolute deviation from the nearest boundary of the velocity band, or set to 0 if the throw velocity fell anywhere inside the target band. Thus, when the target band was 600-800, throws of 400, 650, and 1100 would result in deviation values of 200, 0, and 300, respectively. Discrimination was measured by fitting a linear model to the testing throws of each subjects, with the lower end of the target velocity band as the predicted variable, and the x velocity produced by the participants as the predictor variable. Participants who reliably discriminated between velocity bands tended to have positive slopes with values ~1, while participants who made throws irrespective of the current target band would have slopes ~0.

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  254 |    148 | 298 |
| 350-550   | Extrapolation |  191 |    110 | 229 |
| 600-800   | Extrapolation |  150 |     84 | 184 |
| 800-1000  | Trained       |  184 |    106 | 242 |
| 1000-1200 | Extrapolation |  233 |    157 | 282 |
| 1200-1400 | Extrapolation |  287 |    214 | 290 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  386 |    233 | 426 |
| 350-550   | Extrapolation |  285 |    149 | 340 |
| 600-800   | Extrapolation |  234 |    144 | 270 |
| 800-1000  | Trained       |  221 |    149 | 248 |
| 1000-1200 | Trained       |  208 |    142 | 226 |
| 1200-1400 | Trained       |  242 |    182 | 235 |

## Results

### Testing Phase - No feedback.

In the first part of the testing phase, participants are tested from each of the velocity bands, and receive no feedback after each throw.

#### Deviation From Target Band

Descriptive summaries testing deviation data are provided in <a href="#tbl-e1-test-nf-deviation" class="quarto-xref">Table 1</a> and <a href="#fig-e1-test-dev" class="quarto-xref">Figure 3</a>. To model differences in accuracy between groups, we used Bayesian mixed effects regression models to the trial level data from the testing phase. The primary model predicted the absolute deviation from the target velocity band (dist) as a function of training condition (condit), target velocity band (band), and their interaction, with random intercepts and slopes for each participant (id).

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-test-dev-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   205.09 |        136.86 |        274.06 | 1.00 |
| conditVaried |   157.44 |         60.53 |        254.90 | 1.00 |
| Band         |     0.01 |         -0.07 |          0.08 | 0.57 |
| condit\*Band |    -0.16 |         -0.26 |         -0.06 | 1.00 |

| contrast          | Band |   value |  lower |  upper |   pd |
|:------------------|-----:|--------:|-------:|-------:|-----:|
| Constant - Varied |  100 | -141.49 | -229.2 | -53.83 | 1.00 |
| Constant - Varied |  350 | -101.79 | -165.6 | -36.32 | 1.00 |
| Constant - Varied |  600 |  -62.02 | -106.2 | -14.77 | 1.00 |
| Constant - Varied |  800 |  -30.11 |  -65.1 |   6.98 | 0.94 |
| Constant - Varied | 1000 |    2.05 |  -33.5 |  38.41 | 0.54 |
| Constant - Varied | 1200 |   33.96 |  -11.9 |  81.01 | 0.92 |

The model predicting absolute deviation (dist) showed clear effects of both training condition and target velocity band (Table X). Overall, the varied training group showed a larger deviation relative to the constant training group (β = 157.44, 95% CI \[60.53, 254.9\]). Deviation also depended on target velocity band, with lower bands showing less deviation. See <a href="#tbl-e1-bmm-dist" class="quarto-xref">Table 2</a> for full model output.

#### Discrimination between bands

In addition to accuracy/deviation, we also assessed the ability of participants to reliably discriminate between the velocity bands (i.e. responding differently when prompted for band 600-800 than when prompted for band 150-350). <a href="#tbl-e1-test-nf-vx" class="quarto-xref">Table 3</a> shows descriptive statistics of this measure, and Figure 1 visualizes the full distributions of throws for each combination of condition and velocity band. To quantify discrimination, we again fit Bayesian Mixed Models as above, but this time the dependent variable was the raw x velocity generated by participants on each testing trial.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-test-vx-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  524 |    448 | 327 |
| 350-550   | Extrapolation |  659 |    624 | 303 |
| 600-800   | Extrapolation |  770 |    724 | 300 |
| 800-1000  | Trained       | 1001 |    940 | 357 |
| 1000-1200 | Extrapolation | 1167 |   1104 | 430 |
| 1200-1400 | Extrapolation | 1283 |   1225 | 483 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  664 |    533 | 448 |
| 350-550   | Extrapolation |  768 |    677 | 402 |
| 600-800   | Extrapolation |  876 |    813 | 390 |
| 800-1000  | Trained       | 1064 |   1029 | 370 |
| 1000-1200 | Trained       | 1180 |   1179 | 372 |
| 1200-1400 | Trained       | 1265 |   1249 | 412 |

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   408.55 |        327.00 |        490.61 | 1.00 |
| conditVaried |   164.05 |         45.50 |        278.85 | 1.00 |
| Band         |     0.71 |          0.62 |          0.80 | 1.00 |
| condit\*Band |    -0.14 |         -0.26 |         -0.01 | 0.98 |

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   478.47 |        404.00 |        551.45 | 1.00 |
| conditVaried |   142.04 |         37.17 |        247.59 | 1.00 |
| Band         |     0.50 |          0.42 |          0.57 | 1.00 |
| condit\*Band |    -0.07 |         -0.17 |          0.04 | 0.89 |

See <a href="#tbl-e1-bmm-vx" class="quarto-xref">Table 4</a> for the full model results. The estimated coefficient for training condition ($B$ = 164.05, 95% CrI \[45.5, 278.85\]) suggests that the varied group tends to produce harder throws than the constant group, but is not in and of itself useful for assessing discrimination. Most relevant to the issue of discrimination is the slope on Velocity Band ($B$ = 0.71, 95% CrI \[0.62, 0.8\]). Although the median slope does fall underneath the ideal of value of 1, the fact that the 95% credible interval does not contain 0 provides strong evidence that participants exhibited some discrimination between bands. The estimate for the interaction between slope and condition ($B$ = -0.14, 95% CrI \[-0.26, -0.01\]), suggests that the discrimination was somewhat modulated by training condition, with the varied participants showing less senitivity between vands than the constant condition. This difference is depicted visually in <a href="#fig-e1-bmm-vx" class="quarto-xref">Figure 5</a>.@tbl-e1-slope-quartile shows the average slope coefficients for varied and constant participants separately for each quartile. The constant participant participants appear to have larger slopes across quartiles, but the difference between conditions may be less pronounced for the top quartiles of subjects who show the strongest discrimination. Figure <a href="#fig-e1-bmm-bx2" class="quarto-xref">Figure 6</a> shows the distributions of slope values for each participant, and the compares the probability density of slope coefficients between training conditions. <a href="#fig-e1-indv-slopes" class="quarto-xref">Figure 7</a>

The second model, which focused solely on extrapolation bands, revealed similar patterns. The Velocity Band term ($B$ = 0.5, 95% CrI \[0.42, 0.57\]) still demonstrates a high degree of discrimination ability. However, the posterior distribution for interaction term ($B$ = -0.07, 95% CrI \[-0.17, 0.04\] ) does across over 0, suggesting that the evidence for decreased discrimination ability for the varied participants is not as strong when considering only the three extrapolation bands.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-bmm-vx-1.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-bmm-vx" />

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-bmm-vx-2.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-bmm-vx" />

| Condition | Q_0%\_mean | Q_25%\_mean | Q_50%\_mean | Q_75%\_mean | Q_100%\_mean |
|:----------|-----------:|------------:|------------:|------------:|-------------:|
| Constant  |     -0.109 |       0.475 |       0.690 |       0.930 |          1.4 |
| Varied    |     -0.194 |       0.266 |       0.587 |       0.899 |          1.3 |

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-bmm-bx2-1.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-bmm-bx2" />

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-bmm-bx2-2.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-bmm-bx2" />

test

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-indv-slopes-1.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-indv-slopes" />

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e1-indv-slopes-2.jpeg" style="width:100.0%" data-fig-align="center" data-ref-parent="fig-e1-indv-slopes" />

# Experiment 2

<a href="#fig-design-e2" class="quarto-xref">Figure 8</a> illustrates the design of Experiment 2. The stages of the experiment (i.e. training, testing no-feedback, test with feedback), are identical to that of Experiment 1. The only change is that Experiment 2 participants train, and then test, on bands in the reverse order of Experiment 1 (i.e. training on the softer bands; and testing on the harder bands).

``` dot
digraph {
  graph [layout = dot, rankdir = LR]

  // define the global styles of the nodes
  node [shape = rectangle, style = filled]

  data1 [label = " Varied Training \n100-300\n350-550\n600-800", fillcolor = "#FF0000"]
  data2 [label = " Constant Training \n600-800", fillcolor = "#00A08A"]
  Test3 [label = "    Final Test \n  Novel With Feedback  \n800-1000\n1000-1200\n1200-1400", fillcolor = "#ECCBAE"]

  // edge definitions with the node IDs
  data1 -> Test1
  data2 -> Test1
  subgraph cluster {
    label = "Test Phase \n(Counterbalanced Order)"
    Test1 [label = "Test  \nNovel Bands  \n800-1000\n1000-1200\n1200-1400", fillcolor = "#ECCBAE"]
    Test2 [label = "  Test \n  Varied Training Bands  \n100-300\n350-550\n600-800", fillcolor = "#ECCBAE"]
    Test1 -> Test2
  }

  Test2 -> Test3
}
```

<svg width="576" height="240" viewbox="0.00 0.00 647.35 174.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 170)">
<polygon fill="white" stroke="transparent" points="-4,4 -4,-170 643.35,-170 643.35,4 -4,4"></polygon>
<g id="clust1" class="cluster">
<title>cluster</title>
<polygon fill="none" stroke="black" points="152.49,-8 152.49,-158 458.5,-158 458.5,-8 152.49,-8"></polygon>
<text text-anchor="middle" x="305.49" y="-141.4" font-family="Times,serif" font-size="14.00">Test Phase </text>
<text text-anchor="middle" x="305.49" y="-124.6" font-family="Times,serif" font-size="14.00">(Counterbalanced Order)</text>
</g>
<!-- data1 -->
<g id="node1" class="node">
<title>data1</title>
<polygon fill="#ff0000" stroke="black" points="118.54,-137.7 5.95,-137.7 5.95,-62.3 118.54,-62.3 118.54,-137.7"></polygon>
<text text-anchor="middle" x="62.24" y="-121" font-family="Times,serif" font-size="14.00"> Varied Training </text>
<text text-anchor="middle" x="62.24" y="-104.2" font-family="Times,serif" font-size="14.00">100-300</text>
<text text-anchor="middle" x="62.24" y="-87.4" font-family="Times,serif" font-size="14.00">350-550</text>
<text text-anchor="middle" x="62.24" y="-70.6" font-family="Times,serif" font-size="14.00">600-800</text>
</g>
<!-- Test1 -->
<g id="node4" class="node">
<title>Test1</title>
<polygon fill="#eccbae" stroke="black" points="256.06,-108 160.63,-108 160.63,-16 256.06,-16 256.06,-108"></polygon>
<text text-anchor="middle" x="208.34" y="-91.4" font-family="Times,serif" font-size="14.00">Test &nbsp;</text>
<text text-anchor="middle" x="208.34" y="-74.6" font-family="Times,serif" font-size="14.00">Novel Bands &nbsp;</text>
<text text-anchor="middle" x="208.34" y="-57.8" font-family="Times,serif" font-size="14.00">800-1000</text>
<text text-anchor="middle" x="208.34" y="-41" font-family="Times,serif" font-size="14.00">1000-1200</text>
<text text-anchor="middle" x="208.34" y="-24.2" font-family="Times,serif" font-size="14.00">1200-1400</text>
</g>
<!-- data1&#45;&gt;Test1 -->
<g id="edge1" class="edge">
<title>data1-&gt;Test1</title>
<path fill="none" stroke="black" d="M118.54,-85.42C129.01,-82.66 139.97,-79.77 150.49,-76.99"></path>
<polygon fill="black" stroke="black" points="151.62,-80.31 160.4,-74.38 149.83,-73.55 151.62,-80.31"></polygon>
</g>
<!-- data2 -->
<g id="node2" class="node">
<title>data2</title>
<polygon fill="#00a08a" stroke="black" points="124.73,-44.6 -0.24,-44.6 -0.24,-3.4 124.73,-3.4 124.73,-44.6"></polygon>
<text text-anchor="middle" x="62.24" y="-28.2" font-family="Times,serif" font-size="14.00"> Constant Training </text>
<text text-anchor="middle" x="62.24" y="-11.4" font-family="Times,serif" font-size="14.00">600-800</text>
</g>
<!-- data2&#45;&gt;Test1 -->
<g id="edge2" class="edge">
<title>data2-&gt;Test1</title>
<path fill="none" stroke="black" d="M124.77,-40.23C133.35,-42.49 142.13,-44.8 150.61,-47.04"></path>
<polygon fill="black" stroke="black" points="149.84,-50.46 160.41,-49.62 151.63,-43.69 149.84,-50.46"></polygon>
</g>
<!-- Test3 -->
<g id="node3" class="node">
<title>Test3</title>
<polygon fill="#eccbae" stroke="black" points="639.27,-108 486.57,-108 486.57,-16 639.27,-16 639.27,-108"></polygon>
<text text-anchor="middle" x="562.92" y="-91.4" font-family="Times,serif" font-size="14.00"> &nbsp;&nbsp;&nbsp;Final Test </text>
<text text-anchor="middle" x="562.92" y="-74.6" font-family="Times,serif" font-size="14.00"> &nbsp;Novel With Feedback &nbsp;</text>
<text text-anchor="middle" x="562.92" y="-57.8" font-family="Times,serif" font-size="14.00">800-1000</text>
<text text-anchor="middle" x="562.92" y="-41" font-family="Times,serif" font-size="14.00">1000-1200</text>
<text text-anchor="middle" x="562.92" y="-24.2" font-family="Times,serif" font-size="14.00">1200-1400</text>
</g>
<!-- Test2 -->
<g id="node5" class="node">
<title>Test2</title>
<polygon fill="#eccbae" stroke="black" points="450.65,-108 292.05,-108 292.05,-16 450.65,-16 450.65,-108"></polygon>
<text text-anchor="middle" x="371.35" y="-91.4" font-family="Times,serif" font-size="14.00"> &nbsp;Test </text>
<text text-anchor="middle" x="371.35" y="-74.6" font-family="Times,serif" font-size="14.00"> &nbsp;Varied Training Bands &nbsp;</text>
<text text-anchor="middle" x="371.35" y="-57.8" font-family="Times,serif" font-size="14.00">100-300</text>
<text text-anchor="middle" x="371.35" y="-41" font-family="Times,serif" font-size="14.00">350-550</text>
<text text-anchor="middle" x="371.35" y="-24.2" font-family="Times,serif" font-size="14.00">600-800</text>
</g>
<!-- Test1&#45;&gt;Test2 -->
<g id="edge3" class="edge">
<title>Test1-&gt;Test2</title>
<path fill="none" stroke="black" d="M256.35,-62C264.51,-62 273.22,-62 282.07,-62"></path>
<polygon fill="black" stroke="black" points="282.09,-65.5 292.09,-62 282.09,-58.5 282.09,-65.5"></polygon>
</g>
<!-- Test2&#45;&gt;Test3 -->
<g id="edge4" class="edge">
<title>Test2-&gt;Test3</title>
<path fill="none" stroke="black" d="M450.55,-62C459.05,-62 467.74,-62 476.33,-62"></path>
<polygon fill="black" stroke="black" points="476.34,-65.5 486.34,-62 476.34,-58.5 476.34,-65.5"></polygon>
</g>
</g>
</svg>

## E2 Results

### Testing Phase - No feedback.

In the first part of the testing phase, participants are tested from each of the velocity bands, and receive no feedback after each throw.

#### Deviation From Target Band

Descriptive summaries testing deviation data are provided in <a href="#tbl-e2-test-nf-deviation" class="quarto-xref">Table 6</a> and <a href="#fig-e2-test-dev" class="quarto-xref">Figure 9</a>.
To model differences in accuracy between groups, we used Bayesian mixed effects regression models to the trial level data from the testing phase. The primary model predicted the absolute deviation from the target velocity band (dist) as a function of training condition (condit), target velocity band (band), and their interaction, with random intercepts and slopes for each participant (id).

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  206 |     48 | 317 |
| 350-550   | Extrapolation |  194 |     86 | 268 |
| 600-800   | Trained       |  182 |    112 | 240 |
| 800-1000  | Extrapolation |  200 |    129 | 233 |
| 1000-1200 | Extrapolation |  238 |    190 | 234 |
| 1200-1400 | Extrapolation |  311 |    254 | 288 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Trained       |  153 |     25 | 266 |
| 350-550   | Trained       |  138 |     53 | 233 |
| 600-800   | Trained       |  160 |    120 | 183 |
| 800-1000  | Extrapolation |  261 |    207 | 257 |
| 1000-1200 | Extrapolation |  305 |    258 | 273 |
| 1200-1400 | Extrapolation |  363 |    314 | 297 |

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e2-test-dev-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   151.71 |         90.51 |        215.86 | 1.00 |
| conditVaried |   -70.33 |       -156.87 |         16.66 | 0.94 |
| Band         |     0.10 |          0.02 |          0.18 | 1.00 |
| condit\*Band |     0.12 |          0.02 |          0.23 | 0.99 |

| contrast          | Band | value |  lower |  upper |   pd |
|:------------------|-----:|------:|-------:|-------:|-----:|
| Constant - Varied |  100 |  57.6 |  -20.5 | 135.32 | 0.93 |
| Constant - Varied |  350 |  26.6 |  -30.9 |  83.84 | 0.83 |
| Constant - Varied |  600 |  -4.3 |  -46.7 |  38.52 | 0.58 |
| Constant - Varied |  800 | -29.3 |  -69.4 |  11.29 | 0.92 |
| Constant - Varied | 1000 | -54.6 | -101.1 |  -5.32 | 0.98 |
| Constant - Varied | 1200 | -79.6 | -139.5 | -15.45 | 0.99 |

The model predicting absolute deviation showed a modest tendency for the varied training group to have lower deviation compared to the constant training group (β = -70.33, 95% CI \[-156.87, 16.66\]),with 94% of the posterior distribution being less than 0. This suggests a potential benefit of training with variation, though the evidence is not definitive.

#### Discrimination between Velocity Bands

In addition to accuracy/deviation. We also assessed the ability of participants to reliably discriminate between the velocity bands (i.e. responding differently when prompted for band 600-800 than when prompted for band 150-350). <a href="#tbl-e2-test-nf-vx" class="quarto-xref">Table 8</a> shows descriptive statistics of this measure, and Figure 1 visualizes the full distributions of throws for each combination of condition and velocity band. To quantify discrimination, we again fit Bayesian Mixed Models as above, but this time the dependent variable was the raw x velocity generated by participants.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e2-test-vx-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  457 |    346 | 354 |
| 350-550   | Extrapolation |  597 |    485 | 368 |
| 600-800   | Trained       |  728 |    673 | 367 |
| 800-1000  | Extrapolation |  953 |    913 | 375 |
| 1000-1200 | Extrapolation | 1064 |   1012 | 408 |
| 1200-1400 | Extrapolation | 1213 |   1139 | 493 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Trained       |  410 |    323 | 297 |
| 350-550   | Trained       |  582 |    530 | 303 |
| 600-800   | Trained       |  696 |    641 | 316 |
| 800-1000  | Extrapolation |  910 |    848 | 443 |
| 1000-1200 | Extrapolation | 1028 |    962 | 482 |
| 1200-1400 | Extrapolation | 1095 |   1051 | 510 |

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   362.64 |        274.85 |        450.02 | 1.00 |
| conditVaried |    -8.56 |       -133.97 |        113.98 | 0.55 |
| Band         |     0.71 |          0.58 |          0.84 | 1.00 |
| condit\*Band |    -0.06 |         -0.24 |          0.13 | 0.73 |

See <a href="#tbl-e2-bmm-vx" class="quarto-xref">Table 9</a> for the full model results.

When examining discrimination ability using the model predicting raw x-velocity, the results were less clear than those of the absolute deviation analysis. The slope on Velocity Band (β = 0.71, 95% CrI \[0.58, 0.84\]) indicates that participants showed good discrimination between bands overall. However, the interaction term suggested this effect was not modulated by training condition (β = -0.06, 95% CrI \[-0.24, 0.13\]) Thus, while varied training may provide some advantage for accuracy, both training conditions seem to have similar abilities to discriminate between velocity bands.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e2-bmm-vx-1.jpeg" style="width:100.0%" data-fig-align="center" />

# Experiment 3

The major manipulation adjustment of experiment 3 is for participants to receive ordinal feedback during training, in contrast to the continuous feedback of the earlier experiments. Ordinal feedback informs participants whether a throw was too soft, too hard, or fell within the target velocity range. Experiment 3 participants were randomly assigned to both a training condition (Constant vs. Varied) and a Band Order condition (original order used in Experiment 1, or the Reverse order of Experiment 2).

## Results

### Testing Phase - No feedback.

In the first part of the testing phase, participants are tested from each of the velocity bands, and receive no feedback after each throw. Note that these no-feedback testing trials are identical to those of Experiment 1 and 2, as the ordinal feedback only occurs during the training phase, and final testing phase, of Experiment 3.

#### Deviation From Target Band

Descriptive summaries testing deviation data are provided in <a href="#tbl-e3-test-nf-deviation" class="quarto-xref">Table 10</a> and <a href="#fig-e3-test-dev" class="quarto-xref">Figure 12</a>.
To model differences in accuracy between groups, we fit Bayesian mixed effects regression models to the trial level data from the testing phase. The primary model predicted the absolute deviation from the target velocity band (dist) as a function of training condition (condit), target velocity band (band), and their interaction, with random intercepts and slopes for each participant (id).

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  396 |    325 | 350 |
| 350-550   | Extrapolation |  278 |    176 | 299 |
| 600-800   | Extrapolation |  173 |    102 | 215 |
| 800-1000  | Trained       |  225 |    126 | 284 |
| 1000-1200 | Extrapolation |  253 |    192 | 271 |
| 1200-1400 | Extrapolation |  277 |    210 | 262 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  383 |    254 | 385 |
| 350-550   | Extrapolation |  287 |    154 | 318 |
| 600-800   | Extrapolation |  213 |    140 | 244 |
| 800-1000  | Trained       |  199 |    142 | 209 |
| 1000-1200 | Trained       |  222 |    163 | 221 |
| 1200-1400 | Trained       |  281 |    227 | 246 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  403 |    334 | 383 |
| 350-550   | Extrapolation |  246 |    149 | 287 |
| 600-800   | Trained       |  155 |     82 | 209 |
| 800-1000  | Extrapolation |  207 |    151 | 241 |
| 1000-1200 | Extrapolation |  248 |    220 | 222 |
| 1200-1400 | Extrapolation |  322 |    281 | 264 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Trained       |  153 |      0 | 307 |
| 350-550   | Trained       |  147 |     55 | 258 |
| 600-800   | Trained       |  159 |    107 | 192 |
| 800-1000  | Extrapolation |  221 |    160 | 235 |
| 1000-1200 | Extrapolation |  244 |    185 | 235 |
| 1200-1400 | Extrapolation |  324 |    264 | 291 |

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e3-test-dev-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |   pd |
|:-------------|---------:|--------------:|--------------:|-----:|
| Intercept    |   306.47 |        243.89 |        368.75 | 1.00 |
| conditVaried |   -90.65 |       -182.79 |          3.75 | 0.97 |
| Band         |    -0.07 |         -0.13 |          0.00 | 0.97 |
| condit\*Band |     0.09 |         -0.01 |          0.19 | 0.96 |

The effect of training condition in Experiment 3 showed a similar pattern to Experiment 2, with the varied group tending to have lower deviation than the constant group (β = -90.65, 95% CrI \[-182.79, 3.75\]), with 97% of the posterior distribution falling under 0.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e3-bmm-dist-1.jpeg" style="width:100.0%" data-fig-align="center" />

#### Discrimination between Velocity Bands

In addition to accuracy/deviation. We also assessed the ability of participants to reliably discriminate between the velocity bands (i.e. responding differently when prompted for band 600-800 than when prompted for band 150-350). <a href="#tbl-e3-test-nf-vx" class="quarto-xref">Table 12</a> shows descriptive statistics of this measure, and Figure 1 visualizes the full distributions of throws for each combination of condition and velocity band. To quantify discrimination, we again fit Bayesian Mixed Models as above, but this time the dependent variable was the raw x velocity generated by participants.

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-e3-test-vx-1.jpeg" style="width:100.0%" data-fig-align="center" />

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  680 |    625 | 370 |
| 350-550   | Extrapolation |  771 |    716 | 357 |
| 600-800   | Extrapolation |  832 |    786 | 318 |
| 800-1000  | Trained       | 1006 |    916 | 417 |
| 1000-1200 | Extrapolation | 1149 |   1105 | 441 |
| 1200-1400 | Extrapolation | 1180 |   1112 | 443 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  667 |    554 | 403 |
| 350-550   | Extrapolation |  770 |    688 | 383 |
| 600-800   | Extrapolation |  869 |    814 | 358 |
| 800-1000  | Trained       |  953 |    928 | 359 |
| 1000-1200 | Trained       | 1072 |   1066 | 388 |
| 1200-1400 | Trained       | 1144 |   1093 | 426 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Extrapolation |  684 |    634 | 406 |
| 350-550   | Extrapolation |  729 |    679 | 350 |
| 600-800   | Trained       |  776 |    721 | 318 |
| 800-1000  | Extrapolation |  941 |    883 | 387 |
| 1000-1200 | Extrapolation | 1014 |    956 | 403 |
| 1200-1400 | Extrapolation | 1072 |   1014 | 442 |

| Band      | Band Type     | Mean | Median |  Sd |
|:----------|:--------------|-----:|-------:|----:|
| 100-300   | Trained       |  392 |    270 | 343 |
| 350-550   | Trained       |  540 |    442 | 343 |
| 600-800   | Trained       |  642 |    588 | 315 |
| 800-1000  | Extrapolation |  943 |    899 | 394 |
| 1000-1200 | Extrapolation | 1081 |   1048 | 415 |
| 1200-1400 | Extrapolation | 1185 |   1129 | 500 |

| Term         | Estimate | 95% CrI Lower | 95% CrI Upper |  pd |
|:-------------|---------:|--------------:|--------------:|----:|
| Intercept    |   607.67 |        536.02 |        679.87 |   1 |
| conditVaried |  -167.76 |       -277.14 |        -64.08 |   1 |
| Band         |     0.44 |          0.35 |          0.52 |   1 |
| condit\*Band |     0.18 |          0.06 |          0.31 |   1 |

See <a href="#tbl-e3-bmm-vx" class="quarto-xref">Table 13</a> for the full model results.

Slope estimates for experiment 3 suggest that participants were capable of distinguishing between velocity bands even when provided only ordinal feedback during training (β = 0.44, 95% CrI \[0.35, 0.52\]). Unlike the previous two experiments, the posterior distribution for the interaction between condition and band was consistently positive, suggestive of superior discrimination for the varied participants
β = 0.18, 95% CrI \[0.06, 0.31\].

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-alm-diagram-1.jpeg" style="width:100.0%" data-fig-align="center" />



|                    | **ALM Response Generation**                                        |                                                                                               |
|------------------|-----------------------------|-------------------------|
| Input Activation   | $a_i(X) = \frac{e^{-c(X-X_i)^2}}{\sum_{k=1}^M e^{-c(X-X_k)^2}}$    | Input nodes activate as a function of Gaussian similarity to stimulus                         |
| Output Activation  | $O_j(X) = \sum_{k=1}^M w_{ji} \cdot a_i(X)$                        | Output unit $O_j$ activation is the weighted sum of input activations and association weights |
| Output Probability | $P[Y_j|X] = \frac{O_j(X)}{\sum_{k=1}^M O_k(X)}$                    | The response, $Y_j$ probabilites computed via Luce's choice rule                              |
| Mean Output        | $m(X) = \sum_{j=1}^L Y_j \cdot \frac{O_j(x)}{\sum_{k=1}^M O_k(X)}$ | Weighted average of probabilities determines response to X                                    |
|                    | **ALM Learning**                                                   |                                                                                               |
| Feedback           | $f_j(Z) = e^{-c(Z-Y_j)^2}$                                         | feedback signal Z computed as similarity between ideal response and observed response         |
| magnitude of error | $\Delta_{ji}=(f_{j}(Z)-o_{j}(X))a_{i}(X)$                          | Delta rule to update weights.                                                                 |
| Update Weights     | $w_{ji}^{new}=w_{ji}+\eta\Delta_{ji}$                              | Updates scaled by learning rate parameter $\eta$.                                             |
|                    | **EXAM Extrapolation**                                             |                                                                                               |
| Instance Retrieval | $P[X_i|X] = \frac{a_i(X)}{\sum_{k=1}^M a_k(X)}$                    | Novel test stimulus $X$ activates input nodes $X_i$                                           |
| Slope Computation  | $S =$ $\frac{m(X_{1})-m(X_{2})}{X_{1}-X_{2}}$                      | Slope value, $S$ computed from nearest training instances                                     |
| Response           | $E[Y|X_i] = m(X_i) + S \cdot [X - X_i]$                            | ALM response $m(X_i)$ adjusted by slope.                                                      |



# Modeling

In project 1, I applied model-based techniques to quantify and control for the similarity between training and testing experience, which in turn enabled us to account for the difference between varied and constant training via an extended version of a similarity based generalization model. In project 2, I will go a step further, implementing a full process model capable of both 1) producing novel responses and 2) modeling behavior in both the learning and testing stages of the experiment. For this purpose, we will apply the associative learning model (ALM) and the EXAM model of function learning (DeLosh 1997). ALM is a simple connectionist learning model which closely resembles Kruschke's ALCOVE model (Kruscke 1992), with modifications to allow for the generation of continuous responses.

## ALM & Exam Description

DeLosh et al. ([1997](#ref-deloshExtrapolationSineQua1997)) introduced the associative learning model (ALM), a connectionist model within the popular class of radial-basis networks. ALM was inspired by, and closely resembles Kruschke's influential ALCOVE model of categorization ([Kruschke, 1992](#ref-kruschkeALCOVEExemplarbasedConnectionist1992)).

ALM is a localist neural network model, with each input node corresponding to a particular stimulus, and each output node corresponding to a particular response value. The units in the input layer activate as a function of their Gaussian similarity to the input stimulus. So, for example, an input stimulus of value 55 would induce maximal activation of the input unit tuned to 55. Depending on thevalue of the generalization parameter, the nearby units (e.g. 54 and 56; 53 and 57) may also activate to some degree. ALM is structured with input and output nodes that correspond to regions of the stimulus space, and response space, respectively. The units in the input layer activate as a function of their similarity to a presented stimulus. As was the case with the exemplar-based models, similarity in ALM is exponentially decaying function of distance. The input layer is fully connected to the output layer, and the activation for any particular output node is simply the weighted sum of the connection weights between that node and the input activations. The network then produces a response by taking the weighted average of the output units (recall that each output unit has a value corresponding to a particular response). During training, the network receives feedback which activates each output unit as a function of its distance from the ideal level of activation necessary to produce the correct response. The connection weights between input and output units are then updated via the standard delta learning rule, where the magnitude of weight changes are controlled by a learning rate parameter.

See <a href="#tbl-alm-exam" class="quarto-xref">Table 14</a> for a full specification of the equations that define ALM and EXAM.

## Model Fitting and Comparison

Following the procedure used by Mcdaniel et al. ([2009](#ref-mcdanielPredictingTransferPerformance2009)), we will assess the ability of both ALM and EXAM to account for the empirical data when fitting the models to 1) only the training data, and 2) both training and testing data. Models were fit to the aggregated participant data by minimizing the root-mean squared deviation (RMSE). Because ALM has been shown to do poorly at accounting for human patterns extrapolation ([DeLosh et al., 1997](#ref-deloshExtrapolationSineQua1997)), we will also generate predictions from the EXAM model for the testing stage. EXAM which operates identically to ALM during training, but includes a linear extrapolation mechanism for generating novel responses during testing.

For the hybrid model, predictions are computed by first generating separate predictions from ALM and EXAM, and then combining them using the following equation: $\hat{y} = (1 - w) \cdot alm.pred + w \cdot exam.pred$. For the grid search, the weight parameter is varied from 0 to 1, and the resulting RMSE is recorded.

Each model was fit to the data in 3 different ways. 1) To just the testing data, 2) Both the training and testing data, 3) Only the training data. In all cases, the model only updates its weights during the training phase, and the weights are frozen during the testing phase. In all cases, only the ALM model generates predictions during the training phase. For the testing phase, all 3 models are used to generate predictions.



<div class="tabwid"><style>.cl-44db62be{}.cl-44d78f86{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-44d91f04{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-44d929f4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d929fe{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d92a08{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d92a09{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d92a12{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d92a13{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44d92a14{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-44db62be'><thead><tr style="overflow-wrap:break-word;"><th  colspan="8"class="cl-44d929f4"><p class="cl-44d91f04"><span class="cl-44d78f86"> </span></p></th></tr><tr style="overflow-wrap:break-word;"><th  colspan="2"class="cl-44d929fe"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></th><th class="cl-44d92a08"><p class="cl-44d91f04"><span class="cl-44d78f86">Constant</span></p></th><th  colspan="2"class="cl-44d92a08"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></th><th class="cl-44d92a08"><p class="cl-44d91f04"><span class="cl-44d78f86">Varied</span></p></th><th  colspan="2"class="cl-44d92a08"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-44d92a09"><p class="cl-44d91f04"><span class="cl-44d78f86">Model</span></p></th><th class="cl-44d92a09"><p class="cl-44d91f04"><span class="cl-44d78f86">Fit Method</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">c</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">lr</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">w</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">c</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">lr</span></p></th><th class="cl-44d92a12"><p class="cl-44d91f04"><span class="cl-44d78f86">w</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">ALM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test Only</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.000</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.100</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.134</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">2.030</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">ALM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test &amp; Train</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.047</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.080</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.067</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.100</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">ALM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Train Only</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.060</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.100</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.047</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.080</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">EXAM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test Only</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.007</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">1.327</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.409</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">1.910</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">EXAM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test &amp; Train</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.081</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.161</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.074</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.100</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">EXAM</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Train Only</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.060</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.100</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.047</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.080</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Hybrid</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test Only</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.008</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">1.580</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">1</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.395</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">2.017</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.64</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Hybrid</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">Test &amp; Train</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.067</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.134</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">1</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.134</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">2.017</span></p></td><td class="cl-44d92a13"><p class="cl-44d91f04"><span class="cl-44d78f86">0.79</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">Hybrid</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">Train Only</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0.042</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0.067</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0.042</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0.067</span></p></td><td class="cl-44d92a14"><p class="cl-44d91f04"><span class="cl-44d78f86">0.00</span></p></td></tr></tbody></table></div>

### Testing Observations vs. Predictions

<div class="tabwid"><style>.cl-44f9e09a{}.cl-44f68f12{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-44f7e678{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-44f7e682{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:0;padding-top:0;padding-left:0;padding-right:0;line-height: 1;background-color:transparent;}.cl-44f7e683{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-44f7e68c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:0;padding-top:0;padding-left:0;padding-right:0;line-height: 1;background-color:transparent;}.cl-44f7e68d{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-44f7e696{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:0;padding-top:0;padding-left:0;padding-right:0;line-height: 1;background-color:transparent;}.cl-44f7e697{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-44f7ef92{width:1.096in;background-color:transparent;vertical-align: bottom;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7ef9c{width:0.705in;background-color:transparent;vertical-align: bottom;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7ef9d{width:0.079in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efa6{width:0.646in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efa7{width:0.705in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efb0{width:0.561in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efb1{width:1.096in;background-color:transparent;vertical-align: bottom;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efba{width:0.705in;background-color:transparent;vertical-align: bottom;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efbb{width:0.079in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efc4{width:0.646in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efc5{width:0.705in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efc6{width:0.561in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efce{width:1.096in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efd8{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efe2{width:0.079in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efe3{width:0.646in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efec{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7efed{width:0.561in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7eff6{width:1.096in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7eff7{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f000{width:0.079in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f001{width:0.646in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f00a{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f014{width:0.561in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f015{width:1.096in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f016{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f01e{width:0.079in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f028{width:0.646in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f029{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f032{width:0.561in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f033{width:1.096in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f03c{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f03d{width:0.646in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f03e{width:0.705in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-44f7f046{width:0.561in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-44f9e09a'><thead><tr style="overflow-wrap:break-word;"><th  rowspan="2"class="cl-44f7ef92"><p class="cl-44f7e678"><span class="cl-44f68f12">Fit_Method</span></p></th><th  rowspan="2"class="cl-44f7ef9c"><p class="cl-44f7e678"><span class="cl-44f68f12">Model</span></p></th><th class="cl-44f7ef9d"><p class="cl-44f7e682"><span class="cl-44f68f12"></span></p></th><th  colspan="2"class="cl-44f7efa6"><p class="cl-44f7e683"><span class="cl-44f68f12">Constant</span></p></th><th class="cl-44f7ef9d"><p class="cl-44f7e682"><span class="cl-44f68f12"></span></p></th><th  colspan="2"class="cl-44f7efb0"><p class="cl-44f7e683"><span class="cl-44f68f12">Varied</span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-44f7efbb"><p class="cl-44f7e68c"><span class="cl-44f68f12"></span></p></th><th class="cl-44f7efc4"><p class="cl-44f7e683"><span class="cl-44f68f12">ME</span></p></th><th class="cl-44f7efc5"><p class="cl-44f7e683"><span class="cl-44f68f12">RMSE</span></p></th><th class="cl-44f7efbb"><p class="cl-44f7e68c"><span class="cl-44f68f12"></span></p></th><th class="cl-44f7efc6"><p class="cl-44f7e683"><span class="cl-44f68f12">ME</span></p></th><th class="cl-44f7efc5"><p class="cl-44f7e683"><span class="cl-44f68f12">RMSE</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td  rowspan="3"class="cl-44f7efce"><p class="cl-44f7e68d"><span class="cl-44f68f12">Test Only</span></p></td><td class="cl-44f7efd8"><p class="cl-44f7e68d"><span class="cl-44f68f12">ALM</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efe3"><p class="cl-44f7e697"><span class="cl-44f68f12">223.8</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">348.0</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efed"><p class="cl-44f7e697"><span class="cl-44f68f12">56.3</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">95.4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7efd8"><p class="cl-44f7e68d"><span class="cl-44f68f12">EXAM</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efe3"><p class="cl-44f7e697"><span class="cl-44f68f12">-59.2</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">127.5</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efed"><p class="cl-44f7e697"><span class="cl-44f68f12">-6.0</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">45.9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7efd8"><p class="cl-44f7e68d"><span class="cl-44f68f12">Hybrid</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efe3"><p class="cl-44f7e697"><span class="cl-44f68f12">-58.2</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">127.4</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efed"><p class="cl-44f7e697"><span class="cl-44f68f12">-3.0</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">33.8</span></p></td></tr><tr style="overflow-wrap:break-word;"><td  rowspan="3"class="cl-44f7eff6"><p class="cl-44f7e68d"><span class="cl-44f68f12">Test &amp; Train</span></p></td><td class="cl-44f7eff7"><p class="cl-44f7e68d"><span class="cl-44f68f12">ALM</span></p></td><td class="cl-44f7f000"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f001"><p class="cl-44f7e697"><span class="cl-44f68f12">193.2</span></p></td><td class="cl-44f7f00a"><p class="cl-44f7e697"><span class="cl-44f68f12">328.7</span></p></td><td class="cl-44f7f000"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f014"><p class="cl-44f7e697"><span class="cl-44f68f12">82.3</span></p></td><td class="cl-44f7f00a"><p class="cl-44f7e697"><span class="cl-44f68f12">106.6</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7eff7"><p class="cl-44f7e68d"><span class="cl-44f68f12">EXAM</span></p></td><td class="cl-44f7f000"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f001"><p class="cl-44f7e697"><span class="cl-44f68f12">-28.8</span></p></td><td class="cl-44f7f00a"><p class="cl-44f7e697"><span class="cl-44f68f12">132.1</span></p></td><td class="cl-44f7f000"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f014"><p class="cl-44f7e697"><span class="cl-44f68f12">13.2</span></p></td><td class="cl-44f7f00a"><p class="cl-44f7e697"><span class="cl-44f68f12">60.2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7f016"><p class="cl-44f7e68d"><span class="cl-44f68f12">Hybrid</span></p></td><td class="cl-44f7f01e"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f028"><p class="cl-44f7e697"><span class="cl-44f68f12">-16.7</span></p></td><td class="cl-44f7f029"><p class="cl-44f7e697"><span class="cl-44f68f12">136.7</span></p></td><td class="cl-44f7f01e"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f032"><p class="cl-44f7e697"><span class="cl-44f68f12">16.7</span></p></td><td class="cl-44f7f029"><p class="cl-44f7e697"><span class="cl-44f68f12">46.5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td  rowspan="3"class="cl-44f7f033"><p class="cl-44f7e68d"><span class="cl-44f68f12">Train Only</span></p></td><td class="cl-44f7efd8"><p class="cl-44f7e68d"><span class="cl-44f68f12">ALM</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efe3"><p class="cl-44f7e697"><span class="cl-44f68f12">194.5</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">329.2</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efed"><p class="cl-44f7e697"><span class="cl-44f68f12">86.3</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">109.1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7efd8"><p class="cl-44f7e68d"><span class="cl-44f68f12">EXAM</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efe3"><p class="cl-44f7e697"><span class="cl-44f68f12">75.3</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">199.9</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7efed"><p class="cl-44f7e697"><span class="cl-44f68f12">17.5</span></p></td><td class="cl-44f7efec"><p class="cl-44f7e697"><span class="cl-44f68f12">65.4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-44f7f03c"><p class="cl-44f7e68d"><span class="cl-44f68f12">Hybrid</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f03d"><p class="cl-44f7e697"><span class="cl-44f68f12">197.5</span></p></td><td class="cl-44f7f03e"><p class="cl-44f7e697"><span class="cl-44f68f12">330.4</span></p></td><td class="cl-44f7efe2"><p class="cl-44f7e696"><span class="cl-44f68f12"></span></p></td><td class="cl-44f7f046"><p class="cl-44f7e697"><span class="cl-44f68f12">88.3</span></p></td><td class="cl-44f7f03e"><p class="cl-44f7e697"><span class="cl-44f68f12">110.3</span></p></td></tr></tbody></table></div>

## Varied Testing Predictions

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-model-preds-varied-1.jpeg" style="width:100.0%" data-fig-align="center" />

<div class="tabwid"><style>.cl-4568df68{}.cl-4564df80{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4564df94{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4564df95{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:rgba(245, 222, 179, 1.00);}.cl-456679d0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-45668466{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668467{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668470{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668471{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4566847a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4566847b{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668484{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668485{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4566848e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668498{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45668499{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684a2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684ac{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684ad{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684b6{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684c0{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684c1{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684ca{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684d4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684d5{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684de{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-456684df{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4568df68'><thead><tr style="overflow-wrap:break-word;"><th  colspan="3"class="cl-45668466"><p class="cl-456679d0"><span class="cl-4564df80"></span></p></th><th class="cl-45668470"><p class="cl-456679d0"><span class="cl-4564df80">ALM</span></p></th><th class="cl-45668471"><p class="cl-456679d0"><span class="cl-4564df80"></span></p></th><th class="cl-45668470"><p class="cl-456679d0"><span class="cl-4564df80">EXAM</span></p></th><th class="cl-45668471"><p class="cl-456679d0"><span class="cl-4564df80"></span></p></th><th class="cl-45668470"><p class="cl-456679d0"><span class="cl-4564df80">Hybrid</span></p></th><th class="cl-4566847a"><p class="cl-456679d0"><span class="cl-4564df80"></span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-4566847b"><p class="cl-456679d0"><span class="cl-4564df80">Fit Method</span></p></th><th class="cl-4566847b"><p class="cl-456679d0"><span class="cl-4564df80">X</span></p></th><th class="cl-45668484"><p class="cl-456679d0"><span class="cl-4564df80">Observed</span></p></th><th class="cl-45668485"><p class="cl-456679d0"><span class="cl-4564df80">Predicted</span></p></th><th class="cl-4566848e"><p class="cl-456679d0"><span class="cl-4564df80">Residual</span></p></th><th class="cl-45668485"><p class="cl-456679d0"><span class="cl-4564df80">Predicted</span></p></th><th class="cl-4566848e"><p class="cl-456679d0"><span class="cl-4564df80">Residual</span></p></th><th class="cl-45668485"><p class="cl-456679d0"><span class="cl-4564df80">Predicted</span></p></th><th class="cl-45668498"><p class="cl-456679d0"><span class="cl-4564df80">Residual</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">100</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">663</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">-12</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">716</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">-53</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">708</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">-45</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">350</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">764</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">89</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">817</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">-53</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">792</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df95">-28</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">600</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">884</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">209</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">895</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">-11</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">875</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df95">9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">800</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,083</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,078</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">5</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">83</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,091</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">-8</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,196</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,202</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">-6</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,199</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">-3</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,204</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">-8</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df80">Test Only</span></p></td><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df80">1,200</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df80">1,283</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,230</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df80">53</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,282</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df95">1</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,221</span></p></td><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df80">62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df94">100</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df80">663</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df95">-12</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">716</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df80">-53</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">707</span></p></td><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df80">-44</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">350</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">764</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">89</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">817</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">-53</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">788</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df95">-24</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">600</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">884</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">209</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">902</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">-18</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">851</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">33</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">800</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,083</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">83</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">83</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,004</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df95">79</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,196</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,163</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">33</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,165</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">31</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,196</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df95">0</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df80">Test &amp; Train</span></p></td><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df80">1,200</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df80">1,283</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,191</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df80">92</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,194</span></p></td><td class="cl-456684b6"><p class="cl-456679d0"><span class="cl-4564df80">89</span></p></td><td class="cl-456684c0"><p class="cl-456679d0"><span class="cl-4564df80">1,227</span></p></td><td class="cl-456684ad"><p class="cl-456679d0"><span class="cl-4564df95">56</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df94">100</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df80">663</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df95">-12</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">716</span></p></td><td class="cl-456684ca"><p class="cl-456679d0"><span class="cl-4564df80">-53</span></p></td><td class="cl-456684d4"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684c1"><p class="cl-456679d0"><span class="cl-4564df95">-12</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">350</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">764</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">89</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">817</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">-53</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">89</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df94">600</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">884</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">209</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">905</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">-21</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">675</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">209</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">800</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,083</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">83</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">83</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">999</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">84</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">1,000</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df80">1,196</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,150</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">46</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,150</span></p></td><td class="cl-456684a2"><p class="cl-456679d0"><span class="cl-4564df95">46</span></p></td><td class="cl-456684ac"><p class="cl-456679d0"><span class="cl-4564df80">1,143</span></p></td><td class="cl-45668499"><p class="cl-456679d0"><span class="cl-4564df80">53</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-456684d5"><p class="cl-456679d0"><span class="cl-4564df80">Train Only</span></p></td><td class="cl-456684d5"><p class="cl-456679d0"><span class="cl-4564df80">1,200</span></p></td><td class="cl-456684de"><p class="cl-456679d0"><span class="cl-4564df80">1,283</span></p></td><td class="cl-456684df"><p class="cl-456679d0"><span class="cl-4564df80">1,180</span></p></td><td class="cl-456684de"><p class="cl-456679d0"><span class="cl-4564df95">103</span></p></td><td class="cl-456684df"><p class="cl-456679d0"><span class="cl-4564df80">1,180</span></p></td><td class="cl-456684de"><p class="cl-456679d0"><span class="cl-4564df95">103</span></p></td><td class="cl-456684df"><p class="cl-456679d0"><span class="cl-4564df80">1,176</span></p></td><td class="cl-456684d5"><p class="cl-456679d0"><span class="cl-4564df80">107</span></p></td></tr></tbody></table></div>

## Constant Testing Predictions

<img src="manuscript.markdown_strict_files/figure-markdown_strict/fig-model-preds-constant-1.jpeg" style="width:100.0%" data-fig-align="center" />

<div class="tabwid"><style>.cl-45d28bde{}.cl-45ceda2a{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-45ceda34{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-45ceda3e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:rgba(245, 222, 179, 1.00);}.cl-45d04b8a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-45d055f8{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05602{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05603{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0560c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0560d{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05616{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05617{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05620{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05621{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0562a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0562b{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05634{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05635{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05636{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0563e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0563f{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05648{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05649{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05652{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05653{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d0565c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-45d05666{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-45d28bde'><thead><tr style="overflow-wrap:break-word;"><th  colspan="3"class="cl-45d055f8"><p class="cl-45d04b8a"><span class="cl-45ceda2a"></span></p></th><th class="cl-45d05603"><p class="cl-45d04b8a"><span class="cl-45ceda2a">ALM</span></p></th><th class="cl-45d0560c"><p class="cl-45d04b8a"><span class="cl-45ceda2a"></span></p></th><th class="cl-45d05603"><p class="cl-45d04b8a"><span class="cl-45ceda2a">EXAM</span></p></th><th class="cl-45d0560c"><p class="cl-45d04b8a"><span class="cl-45ceda2a"></span></p></th><th class="cl-45d05603"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Hybrid</span></p></th><th class="cl-45d0560d"><p class="cl-45d04b8a"><span class="cl-45ceda2a"></span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-45d05616"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Fit Method</span></p></th><th class="cl-45d05616"><p class="cl-45d04b8a"><span class="cl-45ceda2a">X</span></p></th><th class="cl-45d05617"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Observed</span></p></th><th class="cl-45d05620"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Predicted</span></p></th><th class="cl-45d05621"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Residual</span></p></th><th class="cl-45d05620"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Predicted</span></p></th><th class="cl-45d05621"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Residual</span></p></th><th class="cl-45d05620"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Predicted</span></p></th><th class="cl-45d0562a"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Residual</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">100</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">527</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-148</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">717</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-190</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">717</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-190</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">350</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">666</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-9</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">822</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-156</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">821</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-155</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">600</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">780</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">105</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">927</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-147</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">926</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-146</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">800</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">980</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">305</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,010</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-30</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,009</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-29</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,000</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,163</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">488</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,094</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">69</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,093</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test Only</span></p></td><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,200</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,277</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda2a">602</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,178</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda3e">99</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,176</span></p></td><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda2a">101</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda34">100</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda2a">527</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-148</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">712</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-185</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">711</span></p></td><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-184</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">350</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">666</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-9</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">806</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-140</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">800</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-134</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">600</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">780</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">105</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">900</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-120</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">889</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-109</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">800</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">980</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">859</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">121</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">975</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">5</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">960</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">20</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,000</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,163</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">488</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,049</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">114</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,031</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">132</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Test &amp; Train</span></p></td><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,200</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,277</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda2a">602</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,124</span></p></td><td class="cl-45d0563e"><p class="cl-45d04b8a"><span class="cl-45ceda3e">153</span></p></td><td class="cl-45d0563f"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,102</span></p></td><td class="cl-45d05636"><p class="cl-45d04b8a"><span class="cl-45ceda2a">175</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda34">100</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda2a">527</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-148</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">697</span></p></td><td class="cl-45d05649"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-170</span></p></td><td class="cl-45d05652"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05648"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-148</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">350</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">666</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-9</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">752</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">-86</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">600</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">780</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">105</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">807</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">-27</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">105</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">800</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">980</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">851</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">129</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">851</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">129</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">833</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">147</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,000</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,163</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda2a">488</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">895</span></p></td><td class="cl-45d05634"><p class="cl-45d04b8a"><span class="cl-45ceda3e">268</span></p></td><td class="cl-45d05635"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0562b"><p class="cl-45d04b8a"><span class="cl-45ceda2a">488</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-45d05653"><p class="cl-45d04b8a"><span class="cl-45ceda2a">Train Only</span></p></td><td class="cl-45d05653"><p class="cl-45d04b8a"><span class="cl-45ceda34">1,200</span></p></td><td class="cl-45d0565c"><p class="cl-45d04b8a"><span class="cl-45ceda2a">1,277</span></p></td><td class="cl-45d05666"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d0565c"><p class="cl-45d04b8a"><span class="cl-45ceda2a">602</span></p></td><td class="cl-45d05666"><p class="cl-45d04b8a"><span class="cl-45ceda2a">939</span></p></td><td class="cl-45d0565c"><p class="cl-45d04b8a"><span class="cl-45ceda3e">338</span></p></td><td class="cl-45d05666"><p class="cl-45d04b8a"><span class="cl-45ceda2a">675</span></p></td><td class="cl-45d05653"><p class="cl-45d04b8a"><span class="cl-45ceda2a">602</span></p></td></tr></tbody></table></div>

# EXAM fit learning curves

# References

Bott, L., & Heit, E. (2004). Nonmonotonic Extrapolation in Function Learning. *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *30*(1), 38--50. <https://doi.org/10.1037/0278-7393.30.1.38>

Brehmer, B. (1974). Hypotheses about relations between scaled variables in the learning of probabilistic inference tasks. *Organizational Behavior and Human Performance*, *11*(1), 1--27. <https://doi.org/10.1016/0030-5073(74)90002-6>

Bürkner, P.-C. (2017). Brms: An R Package for Bayesian Multilevel Models Using Stan. *Journal of Statistical Software*, *80*, 1--28. <https://doi.org/10.18637/jss.v080.i01>

Carroll, J. D. (1963). Functional Learning: The Learning of Continuous Functional Mappings Relating Stimulus and Response Continua. *ETS Research Bulletin Series*, *1963*(2), i--144. <https://doi.org/10.1002/j.2333-8504.1963.tb00958.x>

Ciccione, L., & Dehaene, S. (2021). Can humans perform mental regression on a graph? Accuracy and bias in the perception of scatterplots. *Cognitive Psychology*, *128*, 101406. <https://doi.org/10.1016/j.cogpsych.2021.101406>

Courrieu, P. (2012). Quick approximation of bivariate functions. *British Journal of Mathematical and Statistical Psychology*, *65*(1), 89--121. <https://doi.org/10.1111/j.2044-8317.2011.02016.x>

DeLosh, E. L., McDaniel, M. A., & Busemeyer, J. R. (1997). Extrapolation: The Sine Qua Non for Abstraction in Function Learning. *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *23*(4), 19. <https://doi.org/10.1037/0278-7393.23.4.968>

Kalish, M. L., Lewandowsky, S., & Kruschke, J. K. (2004). Population of Linear Experts: Knowledge Partitioning and Function Learning. *Psychological Review*, *111*(4), 1072--1099. <https://doi.org/10.1037/0033-295X.111.4.1072>

Koh, K., & Meyer, D. E. (1991). Function learning: Induction of continuous stimulus-response relations. *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *17*(5), 811. <https://doi.org/10.1037/0278-7393.17.5.811>

Kruschke, J. K. (1992). ALCOVE: An exemplar-based connectionist model of Category Learning. *Psychological Review*, *99*(1). <https://doi.org/10.1037/0033-295X.99.1.22>

Mcdaniel, M. A., Dimperio, E., Griego, J. A., & Busemeyer, J. R. (2009). Predicting transfer performance: A comparison of competing function learning models. *Journal of Experimental Psychology. Learning, Memory, and Cognition*, *35*, 173--195. <https://doi.org/10.1037/a0013982>

McDaniel, M. A., Fadler, C. L., & Pashler, H. (2013). Effects of spaced versus massed training in function learning. *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *39*(5), 1417--1432. <https://doi.org/10.1037/a0032184>

Said, N., & Fischer, H. (2021). Extrapolation accuracy underestimates rule learning: Evidence from the function-learning paradigm. *Acta Psychologica*, *218*, 103356. <https://doi.org/10.1016/j.actpsy.2021.103356>

Schulz, E., Quiroga, F., & Gershman, S. J. (2020). Communicating Compositional Patterns. *Open Mind*, *4*, 25--39. <https://doi.org/10.1162/opmi_a_00032>

Team, R. C. (2020). *R: A Language and Environment for Statistical Computing*. R: A Language and Environment for Statistical Computing.
